name: Web Tests
description: Runs Blink Web Tests.
inputs:
  test_artifacts_key:
    description: "Artifact key used to store test artifacts."
    required: true
  test_results_key:
    description: "Artifact key used to store test results."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
    - name: Extract Artifacts
      shell: bash
      run: |
        set -x
        # The web tests fail when not run from the source folder. Use the existing checkout.
        cd src/
        tar xf ../test_artifacts.tar.gz
    - name: Run Web Tests
      id: run-tests
      shell: bash
      env:
        # TODO: Once fixed this should be expanded to include more tests.
        TEST_PATH: wpt_internal/cobalt/crash-log
      run: |
        set -x
        env
        cd src/

        # Web-tests expect dump_syms and minidump_stackwalk to be present at the root of the out folder.
        out_dir="out/${{ matrix.platform}}_${{ matrix.config }}"
        cp ${out_dir}/clang_x64/{dump_syms,minidump_stackwalk} ${out_dir}/

        RESULTS_DIR="out/${{ matrix.platform}}_${{ matrix.config }}/layout-test-results"
        echo "RESULTS_DIR=${RESULTS_DIR}" >> $GITHUB_ENV

        third_party/blink/tools/run_web_tests.py \
          --driver-logging \
          --additional-driver-flag="--no-sandbox" \
          --debug \
          --no-show-results \
          --target ${{ matrix.platform}}_${{ matrix.config }} \
          ${TEST_PATH}

        echo "Finished running tests..."
    - name: Archive Test Results
      if: always() && contains(fromJson('["success", "failed"]'), steps.run-tests.outcome)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_results_key }}
        path: src/${{ env.RESULTS_DIR }}/*
