name: Web Tests
description: Runs Blink Web Tests.
inputs:
  test_artifacts_key:
    description: "Artifact key used to store test artifacts."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
    - name: Extract Artifacts
      shell: bash
      run: |
        set -x
        mkdir web-tests/
        cd web-tests/
        tar xf ../test_artifacts.tar.gz
    - name: Run Web Tests
      id: run-tests
      shell: bash
      run: |
        set -x
        env
        cd web-tests/

        # Web-tests expect dump_syms and minidump_stackwalk to be present at the root of the out folder.
        cp out/${{ matrix.platform}}_${{ matrix.config }}/clang_x64/{dump_syms,minidump_stackwalk} \
          out/${{ matrix.platform}}_${{ matrix.config }}/

        third_party/blink/tools/run_web_tests.py \
          --driver-logging \
          --additional-driver-flag="--no-sandbox" \
          --debug \
          -t linux-x64x11-no-starboard_devel \
          wpt_internal/cobalt/crash-log

        echo "Finished running tests..."
