name: Web Tests
description: Runs Blink Web Tests.
inputs:
  test_artifacts_key:
    description: "Artifact key used to store test artifacts."
    required: true
  # test_results_key:
  #   description: "Artifact key used to store test results."
  #   required: true
  # num_gtest_shards:
  #   description: "Total number of shards used to run the steps in this file."
  #   required: true
runs:
  using: "composite"
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
    - name: Extract Artifacts
      shell: bash
      run: |
        set -x
        mkdir web-tests/
        cd web-tests/
        tar xvf ../test_artifacts.tar.gz
    - name: Run Web Tests
      id: run-tests
      shell: bash
      run: |
        set -x
        env
        cd web-tests/

        # Web-tests expect dump_syms and minidump_stackwalk to be present at the root of the out folder.
        cp out/${{ matrix.platform}}_${{ matrix.config }}/clang_x64/* out/${{ matrix.platform}}_${{ matrix.config }}/

        third_party/blink/tools/run_web_tests.py --debug -t ${{ matrix.platform}}_${{ matrix.config }}/ wpt_internal/cobalt/crash-log

        echo "Finished running tests..."
