#!/usr/bin/env python3
#
# Copyright 2023 The Cobalt Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Detects incorrect standard library uses in the Cobalt layer.

It uses the 'nm' tool to look at the weak/undefined symbols
in the resulting cobalt shared library. Since everything should go through
Starboard, most weak or undefined symbols are "Starboard leaks" where we are
accidentally calling the system libraries when we shouldn't.

This script will load a file that contains a list of Allowed C99 Symbols that
are not considered leaks. Additionally, it will also try to read in a list of
libraries to ignore when searching for leaks. These symbols and libraries cannot
be overridden and the only way to include them in the output is to remove them
from these files.

This script can also make use of a manifest file: the set of currently known
leaking symbols for the build. This script can also be used to update the
manifest. --manifest can be used to output an updated manifest and the output
can be redirected to the build's manifest file.

Exits with 1 if run in --submit-check mode and any leaks are either introduced
or removed compared with the manifest, otherwise exits with 0.
"""

import argparse
import collections
import logging
import os
import re
import subprocess
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir))

import paths  # pylint: disable=wrong-import-position

# pylint: disable=line-too-long
_API_LEAK_DETECTOR_TITLE = """    ___    ____  ____   __               __      ____       __            __
   /   |  / __ \\/  _/  / /   ___  ____ _/ /__   / __ \\___  / /____  _____/ /_____  _____
  / /| | / /_/ // /   / /   / _ \\/ __ `/ //_/  / / / / _ \\/ __/ _ \\/ ___/ __/ __ \\/ ___/
 / ___ |/ ____// /   / /___/  __/ /_/ / ,<    / /_/ /  __/ /_/  __/ /__/ /_/ /_/ / /
/_/  |_/_/   /___/  /_____/\\___/\\__,_/_/|_|  /_____/\\___/\\__/\\___/\\___/\\__/\\____/_/
"""
# pylint: enable=line-too-long

# Leaks will be checked against this build.

_DEFAULT_PLATFORM = 'evergreen-x64'
_DEFAULT_CONFIG = 'gold'
_DEFAULT_TARGET = 'cobalt'
_DEFAULT_SB_VERSION = 17

_RE_LIB = re.compile(r'lib.*\.a$')
_RE_OBJ = re.compile(r'.*\.o$')
_RE_FILE = re.compile(r'\/\/.*\.[hcp]+$')
_RE_SYMBOL_AND_ANY_VERSION_INFO = re.compile(r'(([^@]+)@@?(.+))|([^@]+)')
_RE_ALLOWED_C99_SYMBOL = re.compile(r'^\*\s(.*)$')

# Manifests can be automatically generated by the tool but files for allowlisted
# libraries and C99 symbols should be edited by hand.
_LIBRARIES_TO_IGNORE_PATH = os.path.join(
    os.path.dirname(__file__), 'libraries_to_ignore')
_ALLOWED_C99_SYMBOLS_PATH = os.path.join(paths.STARBOARD_ROOT, 'doc', 'c99.md')
_DEFAULT_RELATIVE_MANIFEST_FOLDER = 'evergreen'

# Messages placed at the header of auto-generated files.
_MANIFEST_HEADER = ('# Manifest of Leaking Files\n\n' +
                    '# This file was auto-generated using ' +
                    'api_leak_detector.py.\n')

# Values to stand in for unknown libraries and source files.
_UNKNOWN_LIBRARIES = 'unknown_library(ies)'
_UNKNOWN_SOURCE_FILES = 'unknown_source_file(s)'

# Allowed POSIX symbols in Starboard 16
_ALLOWED_SB_GE_16_POSIX_SYMBOLS = [
    '__errno_location',
    'accept',
    'access',
    'aligned_alloc',
    'asctime_r',
    'bind',
    'calloc',
    'chmod',
    'clock_gettime',
    'clock_nanosleep',
    'close',
    'closedir',
    'connect',
    'dup',
    'dup2',
    'epoll_create',
    'epoll_create1',
    'epoll_ctl',
    'epoll_wait',
    'eventfd',
    'fchmod',
    'fchown',
    'fcntl',
    'fdopendir',
    'free',
    'freeaddrinfo',
    'freeifaddrs',
    'fdatasync',
    'fstat',
    'fstatat',
    'fsync',
    'ftruncate',
    'gai_strerror',
    'getaddrinfo',
    'getauxval',
    'getcwd',
    'geteuid',
    'getifaddrs',
    'getpeername',
    'getpid',
    'getrandom',
    'getrlimit',
    'getsockname',
    'getsockopt',
    'getuid',
    'gmtime_r',
    'isatty',
    'kill',
    'link',
    'listen',
    'lseek',
    'madvise',
    'malloc',
    'malloc_usable_size',
    'mincore',
    'mkdir',
    'mkdtemp',
    'mkostemp',
    'mkstemp',
    'mmap',
    'mprotect',
    'msync',
    'munmap',
    'openat',
    'opendir',
    'pathconf',
    'pause',
    'pipe',
    'pipe2',
    'poll',
    'posix_memalign',
    'prctl',
    'pread',
    'pthread_attr_destroy',
    'pthread_attr_getdetachstate',
    'pthread_attr_getschedpolicy',
    'pthread_attr_getscope',
    'pthread_attr_getstack',
    'pthread_attr_getstacksize',
    'pthread_attr_init',
    'pthread_attr_setdetachstate',
    'pthread_attr_setschedpolicy',
    'pthread_attr_setscope',
    'pthread_attr_setstack',
    'pthread_attr_setstacksize',
    'pthread_cond_broadcast',
    'pthread_cond_destroy',
    'pthread_cond_init',
    'pthread_cond_signal',
    'pthread_cond_timedwait',
    'pthread_cond_wait',
    'pthread_condattr_destroy',
    'pthread_condattr_getclock',
    'pthread_condattr_init',
    'pthread_condattr_setclock',
    'pthread_create',
    'pthread_detach',
    'pthread_equal',
    'pthread_getattr_np',
    'pthread_getname_np',
    'pthread_getschedparam',
    'pthread_getspecific',
    'pthread_join',
    'pthread_key_create',
    'pthread_key_delete',
    'pthread_kill',
    'pthread_mutex_destroy',
    'pthread_mutex_init',
    'pthread_mutex_lock',
    'pthread_mutex_trylock',
    'pthread_mutex_unlock',
    'pthread_mutexattr_destroy',
    'pthread_mutexattr_getpshared',
    'pthread_mutexattr_gettype',
    'pthread_mutexattr_init',
    'pthread_mutexattr_setpshared',
    'pthread_mutexattr_settype',
    'pthread_once',
    'pthread_rwlock_destroy',
    'pthread_rwlock_init',
    'pthread_rwlock_rdlock',
    'pthread_rwlock_tryrdlock',
    'pthread_rwlock_trywrlock',
    'pthread_rwlock_unlock',
    'pthread_rwlock_wrlock',
    'pthread_self',
    'pthread_setname_np',
    'pthread_setschedparam',
    'pthread_setspecific',
    'pthread_sigmask',
    'pwrite',
    'raise',
    'rand',
    'rand_r',
    'read',
    'readdir',
    'readdir_r',
    'readlink',
    'readv',
    'realpath',
    'realloc',
    'recv',
    'recvfrom',
    'recvmmsg',
    'recvmsg',
    'rename',
    'sched_getaffinity',
    'sched_get_priority_max',
    'sched_get_priority_min',
    'sched_yield',
    'select',
    'sem_destroy',
    'sem_init',
    'sem_post',
    'sem_timedwait',
    'sem_wait',
    'send',
    'sendmsg',
    'sendto',
    'setpriority',
    'setsockopt',
    'shutdown',
    'sigaction',
    'signal',
    'snprintf',
    'socket',
    'socketpair',
    'sprintf',
    'srand',
    'statvfs',
    'statx',
    'strftime_l',
    'symlink',
    'sysconf',
    'uname',
    'unlinkat',
    'usleep',
    'utimensat',
    'vfwprintf',
    'vsnprintf',
    'vsscanf',
    'vswprintf',
    'write',
    'writev',

    # TODO: b/476129004 - __clock_gettime64 is weakly defined for 32-bit arm
    # platforms.
    '__clock_gettime64',
]


def DiffWithManifest(leaked_symbols, manifest_path):
  manifest_symbols = LoadManifest(manifest_path)
  introduced = leaked_symbols.difference(manifest_symbols)
  removed = manifest_symbols.difference(leaked_symbols)
  return introduced, removed


def FindLibraries(config_path):
  """Returns all non-ignored static libraries in the build config directory."""
  print('Loading libraries to ignore...', file=sys.stderr)
  libs_to_ignore = LoadLibrariesToIgnore()

  libs = []
  print(f'Searching {config_path} for static libraries', file=sys.stderr)
  for root, _, filenames in os.walk(config_path):
    for filename in filenames:
      abs_path = os.path.join(root, filename)
      if _RE_LIB.match(filename) and filename not in libs_to_ignore:
        libs.append(abs_path)
  return libs


def ObjectFilesToIgnore(config_path):
  """Returns all object files contained in ignored static libraries."""
  print('Loading libraries to ignore...', file=sys.stderr)
  libs_to_ignore = LoadLibrariesToIgnore()

  objs = set()
  print(f'Searching {config_path} for static libraries', file=sys.stderr)
  for root, _, filenames in os.walk(config_path):
    for filename in filenames:
      abs_path = os.path.join(root, filename)
      if _RE_LIB.match(filename) and filename in libs_to_ignore:
        ar_output = RunCommand(['ar', '-t', abs_path])
        objs.update(ar_output.splitlines())
  return objs


def FindLeakingSourceFiles(leaking_symbols, nm_output, config_path):
  r"""Collects and formats all filenames that have leaks in the nm output.

  This function works by iterating through the provided output, keeping track
  of the current file it is in by maintaining a filename variable. When a
  valid leaking symbol is found, it will add the current filename to the set
  of files that contain the specified leak. Once the entire output has been
  iterated across, the dictionary of leaks to sets of files is returned.

  Args:
    leaking_symbols: A list of all of the symbols that are valid leaks.
    nm_output: The output from 'nm -u' being ran against a static library.
    config_path: Absolute path of the config build directory

  Returns:
    A dictionary that maps symbols to a set of filenames that are leaking the
    symbol.
  """
  files = {}
  filename = None
  for line in ProcessNmOutput(nm_output, True):
    if config_path in line:

      # See the description above to understand what the string manipulation
      # below is accomplishing.
      try:
        filename = '//' + os.path.relpath(line, paths.REPOSITORY_ROOT)
      except IndexError as e:
        print(line)
        raise e
      filename = filename.removesuffix(':')
      continue
    elif filename and line and line in leaking_symbols:
      files_set = files.get(line, set())
      files_set.add(filename)
      files[line] = files_set
  return files


def InversedKeys(nested_dict):
  """Returns a copy of a 2D dict with its inner and outer keys swapped."""
  inverse = collections.defaultdict(dict)
  for outer_key, outer_value in nested_dict.items():
    for inner_key, inner_value in outer_value.items():
      inverse[inner_key][outer_key] = inner_value

  return inverse


def FindLeakLocations(leaked_symbols, config_path, only_grep, use_ripgrep):
  """Returns the static libraries and source files leaked APIs are used in.

  Args:
    leaked_symbols: The set of leaked symbols found in the Cobalt layer.
    config_path: The path to the build config directory.
    only_grep: If true, skip searching static libraries and just look for
               symbols in object files.
    use_ripgrep: If true, use ripgrep instead of grep.

  Returns:
    A dict from leaked symbol to dict from static library to the set of source
    files using the leak.
  """
  leaking_files = {}
  libs_to_symbols = {}
  obj_files_in_libs = set()

  if only_grep:
    # We still need to ignore files associated with ignored libraries.
    obj_files_in_libs = ObjectFilesToIgnore(config_path)
    print(
        f'Found {len(obj_files_in_libs)} object files in ignored libraries.',
        file=sys.stderr)
  else:
    print('Collecting static libraries...', file=sys.stderr)
    libs = FindLibraries(config_path)
    print(f'Found {len(libs)} static libraries.', file=sys.stderr)

    print('Searching the static libraries for leaks...', file=sys.stderr)
    print(
        'This may take some time. Use --only-grep to skip this step.',
        file=sys.stderr)
    for i, lib in enumerate(libs):
      # Progress
      if i > 0:
        # Clear previous line
        print('\x1b[1A', file=sys.stderr, end='')
        print('\x1b[2K', file=sys.stderr, end='')
      print(f'[{i + 1}/{len(libs)}] {os.path.basename(lib)}', file=sys.stderr)

      # Get a list of .o files in the .a file so we can ignore them later.
      ar_output = RunCommand(['ar', '-t', lib])
      obj_files_in_libs.update(ar_output.splitlines())

      # Check for undefined symbols in the lib
      libname = os.path.basename(lib)
      nm_output = RunCommand(['nm', '-u', lib])
      libs_to_symbols[libname] = set()
      for symbol in ProcessNmOutput(nm_output):
        if symbol not in leaked_symbols:
          continue
        libs_to_symbols[libname].add(symbol)
      if not libs_to_symbols[libname]:
        del libs_to_symbols[libname]
        continue
      leaking_files[libname] = FindLeakingSourceFiles(libs_to_symbols[libname],
                                                      nm_output, config_path)
      if not leaking_files[libname]:
        del leaking_files[libname]

  # Not all symbols are packaged into lib*.a files, so we also need to grep for
  # them in .o files.
  leaking_files[_UNKNOWN_LIBRARIES] = {}
  if not use_ripgrep:
    print(
        'Tip: Install ripgrep (rg) and use the --ripgrep arg for 10x faster'
        ' processing.',
        file=sys.stderr)
  for i, symbol in enumerate(leaked_symbols):
    # Progress
    if i > 0:
      # Clear previous line
      print('\x1b[1A', file=sys.stderr, end='')
      print('\x1b[2K', file=sys.stderr, end='')
    print(
        f'[{i + 1}/{len(leaked_symbols)}] Searching for {symbol}...',
        file=sys.stderr)
    if use_ripgrep:
      grep_output = RunCommand(
          ['rg', '-uuu', '-l', '-a', '-g', '!{*.ninja}', symbol, config_path])
    else:
      grep_output = RunCommand(
          ['grep', '-r', '-l', '-a', '--exclude=*.ninja', symbol, config_path])
    leaking_files[_UNKNOWN_LIBRARIES][symbol] = set(
        '//' + os.path.relpath(filename, paths.REPOSITORY_ROOT)
        for filename in set(grep_output.splitlines()) - obj_files_in_libs)

  return InversedKeys(leaking_files)


def LoadAllowedC99Symbols():
  allowed_c99_symbols = set()

  with open(_ALLOWED_C99_SYMBOLS_PATH, encoding='utf-8') as f:
    for line in f:
      line = line.strip()
      m = _RE_ALLOWED_C99_SYMBOL.match(line)
      if m:
        allowed_c99_symbols.add(m.group(1))

  return allowed_c99_symbols


def LoadManifest(manifest_path):
  symbols = set()

  with open(manifest_path, encoding='utf-8') as f:
    for line in f:
      line = line.strip()
      if line and line[0] != '#':
        symbols.add(line)

  return symbols


def LoadLibrariesToIgnore():
  # We should *always* ignore libstarboard_platform.a.
  libs = set(['libstarboard_platform.a'])

  # Read in the ignored libraries.
  try:
    with open(_LIBRARIES_TO_IGNORE_PATH, 'r', encoding='utf-8') as f:
      for line in f:
        line = line.strip()
        if not line or line[0] == '#':
          continue
        else:
          libs.add(line)
  except IOError as e:
    print(f"Error opening {_LIBRARIES_TO_IGNORE_PATH}: '{e}'", file=sys.stderr)
    print('Continuing...', file=sys.stderr)
  return libs


def ParseArgs():
  """Parse all of the arguments provided on the command line."""
  parser = argparse.ArgumentParser()
  mode = parser.add_mutually_exclusive_group(required=True)
  mode.add_argument(
      '--submit-check',
      help='Checks if any leaked symbols are entirely introduced or removed.',
      action='store_true')
  mode.add_argument(
      '--inspect',
      help='Outputs all currently leaking symbols and their uses.',
      action='store_true')
  mode.add_argument(
      '--manifest',
      help='Outputs all currently leaking symbols.',
      action='store_true')
  parser.add_argument(
      '-p',
      '--platform',
      default=_DEFAULT_PLATFORM,
      help="Device platform, eg 'evergreen-x64-sbversion-12'.")
  parser.add_argument(
      '-c',
      '--config',
      default=_DEFAULT_CONFIG,
      help="Build config (eg, 'gold','qa' or 'devel')")
  parser.add_argument(
      '-t',
      '--target',
      help="Build target to check (eg, 'cobalt' or 'd8')",
      default=_DEFAULT_TARGET)
  parser.add_argument(
      '--relative-manifest-path',
      help='Path to the manifest to use, relative to api_leak_detector dir.')
  parser.add_argument(
      '--sb_api_version',
      help='The Starboard version',
      type=int,
      default=_DEFAULT_SB_VERSION)
  parser.add_argument(
      '--only-grep',
      help='Skip nm parsing of static libraries and only grep for symbols in '
      'object files. Output will not be grouped by library.',
      action='store_true')
  parser.add_argument(
      '--ripgrep',
      help='Use ripgrep (rg) instead of grep.',
      action='store_true')
  return parser.parse_args()


def PrettyPrint(output, indent=0, inc=2, file=sys.stderr):
  """Alternative to pprint that produces better output for our use case."""
  if isinstance(output, dict):
    if indent == 0:
      newline = 1
    else:
      newline = 0
    for key, value in sorted(output.items()):
      print('{}{}{}'.format('\n' * newline, ' ' * indent, key), file=file)
      PrettyPrint(value, indent + inc)
  elif isinstance(output, set):
    for value in sorted(output):
      print(f"{' ' * indent}{value}", file=file)
  else:
    print(f"{' ' * indent}{output}", file=file)


def ProcessNmOutput(nm_output, collect_files=False):
  """Parses the 'nm' output and collects the matched and unresolved symbols.

  This function retains all of the allowlisted libraries that were loaded on
  startup.

  Args:
    nm_output: The output from a previously ran 'nm -u' command.
    collect_files: Identifies whether or not to include files in the results.
      This increases the reusability of the function (see
      FindLeakingSourceFiles).

  Yields:
    Unresolved symbols that match _RE_SYMBOL_AND_ANY_VERSION_INFO.
  """
  for line in nm_output.splitlines():
    line = line.lstrip()
    contents = line.split(' ', 1)
    if len(contents) == 1:
      if collect_files:
        yield contents[0]
      continue
    results = _RE_SYMBOL_AND_ANY_VERSION_INFO.match(contents[1]).groups()
    if results[3]:  # True if the symbol has no associated version information.
      yield results[3]
    elif results[1]:  # True if the symbol does have version information.
      yield results[1]
    else:
      print(f'Invalid line in nm output: {line}', file=sys.stderr)


def RunCommand(args, cwd=None):
  """Runs a command, returning its stdout and printing stderr on failure."""
  arg_string = ' '.join(args)
  logging.info('Running: %s', arg_string)
  try:
    result = subprocess.run(
        args,
        check=True,
        capture_output=True,
        text=True,
        encoding='utf-8',
        cwd=cwd)
    return result.stdout
  except subprocess.CalledProcessError as e:
    print(f'ERROR: Failed to run `${arg_string}`', file=sys.stderr)
    print(f'Exit Code: {e.returncode}', file=sys.stderr)
    if e.stdout:
      print('--- stdout ---', file=sys.stderr)
      print(e.stdout, file=sys.stderr)
    if e.stderr:
      print('--- stderr ---', file=sys.stderr)
      print(e.stderr, file=sys.stderr)
    raise


def main():
  args = ParseArgs()
  config_dir = f'{args.platform}_{args.config}'
  config_path = os.path.join(paths.BUILD_OUTPUT_ROOT, config_dir)
  obj_path = os.path.join(config_path, 'obj')
  if not args.relative_manifest_path:
    prefix = '' if args.config in ['qa', 'gold'] else 'dev_'
    args.relative_manifest_path = os.path.join(
        _DEFAULT_RELATIVE_MANIFEST_FOLDER, f'{prefix}manifest')
  manifest_path = os.path.join(
      os.path.dirname(__file__), args.relative_manifest_path)

  print(_API_LEAK_DETECTOR_TITLE, file=sys.stderr)
  print(
      'Analyzing for Starboard version ', args.sb_api_version, file=sys.stderr)
  print('Loading allowed C99 symbols...', file=sys.stderr)
  allowed_c99_symbols = LoadAllowedC99Symbols()

  print(f'Building {config_dir} if necessary...', file=sys.stderr)
  RunCommand(['autoninja', '-C', config_path, args.target],
             cwd=paths.REPOSITORY_ROOT)

  # Use the library at lib.unstripped if available, as if that's around it
  # means the top-level one has been stripped of symbols.
  file_name = f'lib{args.target}.so'
  binary_path = os.path.join(config_path, 'lib.unstripped', file_name)
  if not os.path.exists(binary_path):
    binary_path = os.path.join(config_path, file_name)
  print(f'Analyzing: {binary_path}', file=sys.stderr)

  # Get all of the unresolved symbols of the binary.
  nm_output = RunCommand([
      'nm',
      '-u',
      '-C',  # Demangle C++ symbols
      binary_path
  ])

  # Build a set from all of the unresolved symbols that have the allowlisted and
  # Starboard functions and extern configuration variables filtered out.
  def IsSbSymbol(symbol):
    return symbol.startswith('Sb') or symbol.startswith('kSb')

  def IsAllowedPosixSymbol(symbol, sb_api_version: int):
    if sb_api_version in [16, 17]:
      return symbol in _ALLOWED_SB_GE_16_POSIX_SYMBOLS
    else:
      return False

  def IsAllowedSymbol(symbol):
    if symbol in allowed_c99_symbols:
      return True

    if IsSbSymbol(symbol):
      return True

    if IsAllowedPosixSymbol(symbol, sb_api_version=args.sb_api_version):
      return True

    return False

  leaked_symbols = set(
      symbol for symbol in ProcessNmOutput(nm_output) \
          if not IsAllowedSymbol(symbol)
  )

  if args.manifest:
    print('Done!', file=sys.stderr)
    print(_MANIFEST_HEADER)
    PrettyPrint(leaked_symbols, file=sys.stdout)
    return 0

  if args.submit_check:
    introduced, removed = DiffWithManifest(leaked_symbols, manifest_path)
    if introduced:
      PrettyPrint({
          'Leaks introduced:':
              FindLeakLocations(introduced, obj_path, args.only_grep,
                                args.ripgrep)
      })
      print(
          '\nPlease see advice for addressing new leaks at go/cobalt-api-leaks.'
      )
    else:
      print('\nNo leaks were introduced.', file=sys.stderr)

    if removed:
      PrettyPrint({'Leaks removed:': removed})
      print('\nPlease delete removed leaks from the manifest file: '
            f'{args.relative_manifest_path}.')
    else:
      print('No leaks were removed.', file=sys.stderr)

    # We counterintuitively still want to fail even if leaks are only removed
    # so that a CL author knows to update the manifest.
    return 1 if introduced or removed else 0

  if args.inspect:
    if leaked_symbols:
      PrettyPrint(
          FindLeakLocations(leaked_symbols, obj_path, args.only_grep,
                            args.ripgrep))
    else:
      print('No leaks found!', file=sys.stderr)
    return 0


if __name__ == '__main__':
  sys.exit(main())
