name: Test Targets JSON
description: Parses test target JSON file
runs:
  using: "composite"
  steps:
    - name: Download Test Targets Json
      uses: actions/download-artifact@v5
      with:
        name: ${{ matrix.platform }}_test_targets_json
        path:
    - name: Test target count
      id: parse-json
      run: |
        targets_file="test_targets.json"

        # On-Host Targets & GTest filtering
        on_host_targets=$(jq -cr 'if (.on_host | length) > 0 then .test_targets // [] else [] end' "${targets_file}")
        echo "on_host_targets=${on_host_targets}" >> $GITHUB_OUTPUT
        echo "on_host_count=$(echo "${on_host_targets}" | jq -cr 'length')" >> $GITHUB_OUTPUT

        on_host_gtest_targets=$(jq -cr 'if (.on_host | length) > 0 then .test_targets // [] | map(select(endswith("_junit_tests") | not)) else [] end' "${targets_file}")
        echo "on_host_gtest_targets=${on_host_gtest_targets}" >> $GITHUB_OUTPUT

        on_host_executables=$(jq -cr '(.on_host.unit_executables // []) + (.on_host.junit_executables // []) + (.on_host.browser_executables // [])' "${targets_file}")
        echo "on_host_executables=${on_host_executables}" >> $GITHUB_OUTPUT

        # On-Device Targets & GTest filtering
        on_device_targets=$(jq -cr 'if (.on_device | length) > 0 then .test_targets // [] else [] end' "${targets_file}")
        echo "on_device_targets=${on_device_targets}" >> $GITHUB_OUTPUT
        echo "on_device_count=$(echo "${on_device_targets}" | jq -cr 'length')" >> $GITHUB_OUTPUT

        on_device_gtest_targets=$(jq -cr 'if (.on_device | length) > 0 then .test_targets // [] | map(select(endswith("_junit_tests") | not)) else [] end' "${targets_file}")
        echo "on_device_gtest_targets=${on_device_gtest_targets}" >> $GITHUB_OUTPUT

        on_device_executables=$(jq -cr '(.on_device.unit_executables // []) + (.on_device.browser_executables // [])' "${targets_file}")
        echo "on_device_executables=${on_device_executables}" >> $GITHUB_OUTPUT
      shell: bash
outputs:
  on_host_targets:
    description: The on-host test targets in a JSON array.
    value: ${{ steps.parse-json.outputs.on_host_targets }}
  on_host_gtest_targets:
    description: The GTest-only host test targets in a JSON array.
    value: ${{ steps.parse-json.outputs.on_host_gtest_targets }}
  on_host_executables:
    description: The on-host executables in a JSON array.
    value: ${{ steps.parse-json.outputs.on_host_executables }}
  on_host_count:
    description: The number of on-host test targets.
    value: ${{ steps.parse-json.outputs.on_host_count }}
  on_device_targets:
    description: The on-device test targets in a JSON array.
    value: ${{ steps.parse-json.outputs.on_device_targets }}
  on_device_gtest_targets:
    description: The GTest-only device test targets in a JSON array.
    value: ${{ steps.parse-json.outputs.on_device_gtest_targets }}
  on_device_executables:
    description: The on-device executables in a JSON array.
    value: ${{ steps.parse-json.outputs.on_device_executables }}
  on_device_count:
    description: The number of on-device test targets.
    value: ${{ steps.parse-json.outputs.on_device_count }}
