name: Test Targets JSON
description: Parses test target JSON file
runs:
  using: "composite"
  steps:
    - name: Download Test Targets Json
      uses: actions/download-artifact@v5
      with:
        name: ${{ matrix.platform }}_test_targets_json
        path:
    - name: Test target count
      id: parse-json
      run: |
        test_targets_json="$(jq -cr '[.[] | select(.target != null and .test_type == "gunittest") | .target]' test_targets.json)"
        echo "test_targets_json=${test_targets_json}" >> $GITHUB_OUTPUT
        echo "test_targets_count=$(echo "${test_targets_json}" | jq -cr 'length')" >> $GITHUB_OUTPUT

        device_gunittest_targets="$(jq -cr '[.[] | select(.target != null and .runs_on == "device" and .test_type == "gunittest") | .target]' test_targets.json)"
        echo "device_gunittest_targets=${device_gunittest_targets}" >> $GITHUB_OUTPUT
      shell: bash
outputs:
  test_targets_count:
    description: The number of test targets.
    value: ${{ steps.parse-json.outputs.test_targets_count }}
  test_targets_json:
    description: The test targets in a JSON array.
    value: '${{ steps.parse-json.outputs.test_targets_json }}'
  device_gunittest_targets:
    description: "The on-device gunittest targets in a JSON array."
    value: '${{ steps.parse-json.outputs.device_gunittest_targets }}'
