caption: List of preconfigured network file shares.
desc: |-
  Setting the policy specifies a list of preset network file shares. Each item is an object with 2 properties: <ph name="SHARE_URL_FIELD_NAME">share_url</ph> and <ph name="MODE_FIELD_NAME">mode</ph>.

        The share URL should be <ph name="SHARE_URL_FIELD_NAME">share_url</ph>.

        For <ph name="MODE_FIELD_NAME">mode</ph>, it should be <ph name="MODE_ENUM_DROP_DOWN">drop_down</ph> or <ph name="MODE_ENUM_PRE_MOUNT">pre_mount</ph>:

        * <ph name="MODE_ENUM_DROP_DOWN">drop_down</ph> indicates that <ph name="SHARE_URL_FIELD_NAME">share_url</ph> will be added to the share discovery list.

        * <ph name="MODE_ENUM_PRE_MOUNT">pre_mount</ph> indicates that <ph name="SHARE_URL_FIELD_NAME">share_url</ph> will be mounted.
example_value:
- mode: drop_down
  share_url: smb://server/share
- mode: drop_down
  share_url: \\server\share
features:
  dynamic_refresh: true
  per_profile: true
owners:
- amistry@chromium.org
schema:
  items:
    properties:
      mode:
        enum:
        - drop_down
        - pre_mount
        type: string
      share_url:
        type: string
    required:
    - share_url
    - mode
    type: object
  type: array
supported_on:
- chrome_os:71-
tags: []
type: dict
