name: On-device Test
description: Uploads test archives to GCS and runs on-device tests.
runs:
  using: "composite"
  steps:
    - name: Set env vars
      run: |
        echo "ARCHIVE_FILE_PATH=$GITHUB_WORKSPACE/builder_tmp/${{matrix.target_platform}}_${{matrix.config}}/artifacts.tar" >> $GITHUB_ENV
      shell: bash
    - name: Create Test Files Archive
      run: python3 $GITHUB_WORKSPACE/tools/create_archive.py --test_infra -d ${{env.ARCHIVE_FILE_PATH}} -s $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}}
      shell: bash
    - name: Copy Test Files to GCS
      id: upload-test-archive
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ${{env.ARCHIVE_FILE_PATH}}
        destination: ${{env.PROJECT_NAME}}-test-artifacts/${{env.WORKFLOW}}/${{env.GITHUB_RUN_NUMBER}}/
