caption: <ph name="PRIVACY_SANDBOX_NAME">Privacy Sandbox</ph> policies
desc: A group of policies related to <ph name="PRIVACY_SANDBOX_NAME">Privacy Sandbox</ph>. See <ph name="PRIVACY_SANDBOX_URL">https://privacysandbox.com</ph> for details about <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> effort to deprecate third-party cookies.
