caption: Proxy server
desc: |-
  Allows you to specify the proxy server used by <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> and prevents users from changing proxy settings.

        If you choose to never use a proxy server and always connect directly, all other options are ignored.

        If you choose to auto detect the proxy server, all other options are ignored.

        For detailed examples, visit:
        <ph name="PROXY_HELP_URL">https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-sett<ex>https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-sett</ex></ph>.

        If you enable this setting, <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> and ARC-apps ignore all proxy-related options specified from the command line.

        Leaving these policies not set will allow the users to choose the proxy settings on their own.
