#!/usr/bin/env python3
"""Library for autoroller scripts using worktree-free git plumbing."""
from collections import defaultdict
import enum
import json
import os
import re
import subprocess
import sys


@enum.unique
class CommitStatus(enum.Enum):
  """Represents the outcome of a commit attempt."""
  SUCCESS = 'success'  # Successfully committed.
  CONFLICTED = 'conflicted'  # Committed with conflicts.
  FAILED = 'failed'  # The commit failed due to conflicts or other errors.


def log(msg):
  print(msg, file=sys.stderr)


def run(cmd, cwd=None):
  subprocess.run(cmd, check=True, stdout=sys.stderr, cwd=cwd)


def get_out(cmd):
  res = subprocess.run(cmd, capture_output=True, text=True, check=True)
  return res.stdout


def get_start_sha(branch, autoroll_file):
  """Returns an autoroll start SHA or None if CONFLICTED."""
  start = get_out(['git', 'show', f'{branch}:{autoroll_file}']).strip()

  if start.startswith('CONFLICTED:'):
    return None
  return start


def get_commits(branch, start):
  """Returns a list of commits in chronological order.

  Starting from the non-inclusive start, the commits are represented as a
  (sha, title, pr_num) tuple.
  """
  cmd = [
      'git', 'rev-list', '--oneline', '--no-abbrev-commit', '--reverse',
      f'{start}..{branch}'
  ]
  lines = get_out(cmd).splitlines()

  commits = []
  for line in lines:
    match = re.search(r'^(\w+) (.*?)(?: \(#(\d+)\))?$', line)
    if match:
      commits.append(match.groups())
  return commits


def get_rolled_source_items(target_branch):
  """Returns (rolled_shas, rolled_pr_nums) cherry-picked into HEAD."""
  output = get_out(['git', 'log', f'{target_branch}..HEAD', '--format=%B'])
  shas = set(
      re.findall(r'\(cherry picked from commit ([0-9a-fA-F]+)\)', output))
  prs = set()
  pattern = (r'(?:Refer to (?:the )?original PR: '
             r'(?:https://github\.com/[^/]+/[^/]+/pull/)?#?|'
             r'Cherry pick PR #)(\d+)')
  for m in re.finditer(pattern, output):
    prs.add(int(m.group(1)))
  return shas, prs


_PR_LABELS_CACHE = {}


def load_pr_labels_from_file(json_path):
  """Loads PR labels from a JSON file generated by gh pr list."""
  with open(json_path, 'r', encoding='utf-8') as f:
    prs_data = json.load(f)
  for pr in prs_data:
    pr_num = pr.get('number')
    if pr_num is not None:
      labels = {
          label['name']
          for label in pr.get('labels', [])
          if isinstance(label, dict) and 'name' in label
      }
      _PR_LABELS_CACHE[int(pr_num)] = labels


def get_pr_labels(pr_num):
  """Returns a set of label names for a PR number from loaded cache."""
  return _PR_LABELS_CACHE.get(int(pr_num), set())


def get_cherry_pick_metadata(sha, title, pr_num):
  log_output = get_out(
      ['git', 'log', '-1', '--format=%ad%x00%an <%ae>%x00%b', sha])
  parts = log_output.split('\x00', 2)
  date = parts[0]
  author = parts[1]
  body = ''.join(parts[2:])
  body_section = f'{body}\n\n' if body else ''

  ref_target = f'PR #{pr_num}' if pr_num else f'commit {sha}'
  msg = (f'Cherry pick {ref_target}: {title}\n\n'
         f'Refer to original {ref_target}\n\n'
         f'{body_section}'
         f'(cherry picked from commit {sha})')

  return date, author, msg


# --------------------------------------------------------------------------
# Git Plumbing helpers (operate directly on git objects without checkout).
# --------------------------------------------------------------------------
def put(tree, path, entry):
  """Returns a new tree with `path` set to entry=(mode, oid) or removed (None)."""
  head, _, rest = path.partition('/')
  raw = get_out(['git', 'ls-tree', '-z', tree]) if tree else ''
  entries = {}
  for item in filter(None, raw.split('\0')):
    meta, name = item.split('\t', 1)
    entries[name] = meta
  if rest:
    sub = entries.get(head, '').split()
    sub_tree = sub[2] if len(sub) == 3 and sub[1] == 'tree' else None
    new_sub = put(sub_tree, rest, entry)
    entry = ('040000', new_sub) if new_sub else None
  if entry is None:
    entries.pop(head, None)
  else:
    mode, oid = entry
    kind = 'tree' if mode == '040000' else ('commit' if mode == '160000' else 'blob')
    entries[head] = f'{mode} {kind} {oid}'
  if not entries:
    return None
  data = ''.join(f'{m}\t{n}\0' for n, m in entries.items())
  return subprocess.run(['git', 'mktree', '-z', '--missing'], input=data,
                        capture_output=True, text=True, check=True).stdout.strip()


def merge_trees(action, sha, onto):
  """Performs 3-way merge in object space; returns (tree, conflicts)."""
  base, theirs = (f'{sha}^', sha) if action == 'cherry-pick' else (sha, f'{sha}^')
  res = subprocess.run(
      ['git', 'merge-tree', '--write-tree', '--no-messages', '-z',
       f'--merge-base={base}', onto, theirs],
      capture_output=True, text=True)
  if res.returncode not in (0, 1):
    raise subprocess.CalledProcessError(res.returncode, res.args, res.stdout,
                                        res.stderr)

  fields = res.stdout.split('\0')
  tree, conflicts = fields[0], defaultdict(dict)
  stage_map = {'1': 'ancestor', '2': 'ours', '3': 'theirs'}
  for item in filter(None, fields[1:]):
    meta, path = item.split('\t', 1)
    mode, oid, stage = meta.split()
    conflicts[path][stage_map[stage]] = (mode, oid)
  return tree, dict(conflicts)


def resolve_conflicts(tree, conflicts):
  """Resolves standard submodule, deleted-file, and .gitmodules conflicts."""
  edits, unresolved = {}, []
  if '.gitmodules' in conflicts:
    edits['.gitmodules_conflict'] = ('100644', get_out(['git', 'rev-parse', f'{tree}:.gitmodules']).strip())
    edits['.gitmodules'] = conflicts.pop('.gitmodules')['ours']

  for path, stages in conflicts.items():
    if any(m == '160000' for m, _ in stages.values()):
      edits[path] = ('160000', stages['theirs'][1])
    elif 'theirs' not in stages or 'ours' not in stages:
      edits[path] = None
    else:
      unresolved.append(path)

  if unresolved:
    log(f'Cannot resolve conflicts: {unresolved}')
  return edits, unresolved


def commit_tree(tree, parent, date, author, msg):
  """Creates a commit object pointing to `tree` and `parent`."""
  m = re.match(r'^(.*) <(.*)>$', author)
  name, email = m.groups() if m else (author, 'cobalt-github-releaser-bot@google.com')
  env = dict(os.environ, GIT_AUTHOR_NAME=name, GIT_AUTHOR_EMAIL=email, GIT_AUTHOR_DATE=date)
  clean_msg = subprocess.run(['git', 'stripspace'], input=msg, capture_output=True, text=True, check=True).stdout
  return subprocess.run(['git', 'commit-tree', tree, '-p', parent, '-F', '-'],
                        input=clean_msg, capture_output=True, text=True, check=True, env=env).stdout.strip()


def apply_and_commit(action, sha, metadata, first_commit, autoroll_metadata,
                     head=None):
  """Attempts to apply a single commit using pure git plumbing (no checkout)."""
  if head is None:
    head = get_out(['git', 'rev-parse', 'HEAD']).strip()

  date, author, msg = metadata
  status, unmerged_files = CommitStatus.SUCCESS, None

  tree, conflicts = merge_trees(action, sha, head)
  edits, unresolved = resolve_conflicts(tree, conflicts)

  if unresolved:
    if not first_commit:
      return CommitStatus.FAILED, unresolved
    msg = f'CONFLICTED {msg}'
    status = CommitStatus.CONFLICTED
    unmerged_files = unresolved

  autoroll_file, autoroll_sha = autoroll_metadata
  prefix = 'CONFLICTED:' if status == CommitStatus.CONFLICTED else ''
  blob_content = f'{prefix}{autoroll_sha}\n'
  blob_oid = subprocess.run(['git', 'hash-object', '-w', '--stdin'],
                            input=blob_content, capture_output=True, text=True, check=True).stdout.strip()
  edits[autoroll_file] = ('100644', blob_oid)
  for path, entry in edits.items():
    tree = put(tree, path, entry)

  new_commit = commit_tree(tree, head, date, author, msg)
  run(['git', 'update-ref', 'HEAD', new_commit])

  try:
    with open(autoroll_file, 'w', encoding='utf-8') as f:
      f.write(blob_content)
  except OSError:
    pass

  return status, unmerged_files
