#!/bin/bash

MAX_ATTEMPTS=2                                                                                                │
for (( attempt=1; attempt<=MAX_ATTEMPTS; attempt++ )); do
    echo "--> Staging all changes..."
    git add .

    echo "--> Amend all changes..."
    git commit --amend
    
    # Check the exit code of the git commit command
    if [ $? -eq 0 ]; then
        echo "--> Amend successful!"
        exit 0;
    else
        echo "--> Retry Amend..."
    fi
done

echo "Amend failed"
