services:
  base:
    build:
      context: cobalt/docker
      target: base
    image: "${DOCKER_COMPOSE_IMAGE:-base}"
    platform: linux/amd64
  linux:
    build:
      context: cobalt/docker
      target: linux
    image: "${DOCKER_COMPOSE_IMAGE:-linux}"
    platform: linux/amd64
  rdk:
    build:
      context: cobalt/docker
      target: rdk
    image: "${DOCKER_COMPOSE_IMAGE:-rdk}"
    platform: linux/amd64
  unittest:
    build:
      context: cobalt/docker
      target: unittest
    image: "${DOCKER_COMPOSE_IMAGE:-unittest}"
    platform: linux/amd64
  webtest:
    build:
      context: cobalt/docker
      target: webtest
    image: "${DOCKER_COMPOSE_IMAGE:-webtest}"
    platform: linux/amd64
  pre-commit:
    build:
      context: cobalt/docker/pre-commit
    image: "${DOCKER_COMPOSE_IMAGE:-pre-commit}"
