owners:
- sidereal@google.com
- file://chrome/browser/ash/guest_os/OWNERS

caption: |-
  Configure the installer for Bruschetta VMs on <ph name="PRODUCT_OS_NAME">$2
  <ex>Google ChromeOS</ex></ph> devices

desc: |-
  Sets metadata used by the installer for Bruschetta VMs on <ph
  name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> devices, prior to it
  being installed.

future_on:
- chrome_os

features:
  dynamic_refresh: true
  per_profile: false
  cloud_only: true
  unlisted: true

type: dict

schema:
  type: object
  description: Installer metadata
  properties:
    display_name:
      type: string
      description: |-
        Name to show in the installer UI e.g. Happy VM. If unset will show a
        fallback name, either derived from the first (by display order) entry in
        the BruschettaVMConfiguration policy, or failing that, a generic name.
    learn_more_url:
      type: string
      description: |-
        A URL for users to visit to learn more. If unset there will
        be no "learn more" URL in the installer. If present, it must use
        the https scheme.

example_value:
  display_name: AwesomeNix
  learn_more_url: https://example.com/learn_more

tags:
 - system-security
