name: Print Logs and Test Summary
description: Processes logs and test results to produce a test summary.
inputs:
  log_glob:
    description: "Path (or glob) to test log files."
    required: true
  results_glob:
    description: "Path (or glob) to test result xml files."
    required: false
    default: ''
  symbolize:
    description: "If logs should be ran through crash symbolization tools."
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Prepare gclient cache directory
      if: inputs.symbolize == 'true'
      run: |
        mkdir -p /runner-cache/cobalt/src
        ln -s /runner-cache/cobalt ${GITHUB_WORKSPACE}/cobalt
      shell: bash
    - name: Prepare Workspace for Checkout
      if: inputs.symbolize == 'true'
      run: |
        CHECKOUT_PATH="${GITHUB_WORKSPACE}/cobalt/src"
        # Check src already exists by earlier runners:
        if [ -d "${CHECKOUT_PATH}/.git" ]; then
          cd "${CHECKOUT_PATH}"
          git reset --hard
          # Remove unmerged/conflict markers if any merge was aborted
          git merge --abort || true
        fi
      shell: bash
    - name: Add safe directory for git
      if: inputs.symbolize == 'true'
      run: git config --global --add safe.directory /runner-cache/cobalt/src
      shell: bash
    - name: Checkout
      if: inputs.symbolize == 'true'
      uses: actions/checkout@v4
      with:
        path: cobalt/src
        fetch-depth: ${{ ( github.event_name == 'pull_request' || github.repository == 'youtube/cobalt_sandbox' ) && 2 || 0 }}
        clean: false
    - name: Set Up Depot Tools
      if: inputs.symbolize == 'true'
      uses: ./cobalt/src/.github/actions/depot_tools
    - name: Print Logs and Test Summary
      run: |
        # Print logs and failing tests.
        # Enable globstar shell option for globstar paths e.g. /**/*.xml and
        # nullopt to returns empty string if the glob matches no files.
        shopt -s globstar nullglob

        log_files=(${{ inputs.log_glob }})
        if [ ${#log_files[@]} -eq 0 ]; then
          echo "::error::No log files were collected. The tests probably failed to run."
          exit 1
        else
          for log_file in ${log_files[@]}; do
            if [ "${{ inputs.symbolize }}" == "true" ]; then
              cat ../${log_file} | python3 cobalt/src/third_party/android_platform/development/scripts/stack.py --pass-through --output-directory out/${{ matrix.platform }}_${{ matrix.config }}/
            else
              echo "=== ${log_file} ==="
              cat ${log_file}
            fi
          done
        fi
      shell: bash
