caption: <ph name="MS_AD_NAME">Microsoft速 Active Directory速</ph> management settings
desc: Controls settings specific to <ph name="MS_AD_NAME">Microsoft速 Active Directory速</ph>
  managed <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> devices.
