name: Run API Leak Detector
description: Runs the API leak detector

runs:
  using: "composite"
  steps:
    - name: Run Detector
      shell: bash
      env:
        SB_API_VERSION: ${{ matrix.sb_api_version }}
        PLATFORM: ${{ matrix.platform }}
        CONFIG: ${{ matrix.config }}
      run: |
        set -x
        FLAGS=()
        if [ -n "${SB_API_VERSION}" ]; then
          FLAGS+=("--sb_api_version=${SB_API_VERSION}")
        fi
        python3 cobalt/src/starboard/tools/api_leak_detector/api_leak_detector.py -p "${PLATFORM}" -c "${CONFIG}" --submit-check "${FLAGS[@]}"
        if [ "${CONFIG}" == "devel" ]; then
          python3 cobalt/src/starboard/tools/api_leak_detector/api_leak_detector.py -p "${PLATFORM}" -c "${CONFIG}" --submit-check "${FLAGS[@]}" -t nplb
        fi
