name: Run API Leak Detector
description: Runs the API leak detector

runs:
  using: "composite"
  steps:
    - name: Run Detector
      shell: bash
      env:
        SB_API_VERSION: ${{ matrix.sb_api_version }}
        PLATFORM: ${{ matrix.platform }}
        CONFIG: ${{ matrix.config }}
      run: |
        set -x
        python3 cobalt/src/starboard/tools/api_leak_detector/api_leak_detector.py -p "${PLATFORM}" -c "${CONFIG}" --submit-check ${SB_API_VERSION:+--sb_api_version=${SB_API_VERSION}}
        if [ "${CONFIG}" == "devel" ]; then
          python3 cobalt/src/starboard/tools/api_leak_detector/api_leak_detector.py -p "${PLATFORM}" -c "${CONFIG}" --submit-check ${SB_API_VERSION:+--sb_api_version=${SB_API_VERSION}} -t nplb
        fi
