name: E2E Tests
description: Runs e2e tests.
inputs:
  test_dimensions:
    description: "Test dimensions JSON string."
    required: true
  e2e_test_targets:
    description: "E2E test targets."
    required: true
  artifact_basename:
    description: "The basename of the artifact to be used for E2E tests."
    required: true
  test_device_family:
    description: "Test device family."
    required: true
  test_attempts:
    description: "Number of attempts for the tests."
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: |
        pip3 install --require-hashes --no-deps -r ${GITHUB_WORKSPACE}/cobalt/tools/requirements.txt
      shell: bash
    - name: Generate gRPC files
      run: |
        python -m grpc_tools.protoc -I${GITHUB_WORKSPACE}/cobalt/tools/ \
            --python_out=${GITHUB_WORKSPACE}/cobalt/tools/ \
            --grpc_python_out=${GITHUB_WORKSPACE}/cobalt/tools/ \
            ${GITHUB_WORKSPACE}/cobalt/tools/on_device_tests_gateway.proto
      shell: bash
    - name: Set Up Cloud SDK
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Set GCS Project Name
      run: |
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
      shell: bash
    - name: Run Tests on ${{ matrix.platform }} Platform
      env:
        GCS_ARTIFACTS_PATH: /bigstore/${{ env.PROJECT_NAME }}-test-artifacts/${{ github.workflow }}/${{ github.run_number }}/${{ matrix.platform }}/${{ inputs.artifact_basename }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
        GITHUB_ACTOR_ID: ${{ github.actor_id }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_PR_HEAD_USER_LOGIN: ${{ github.event.pull_request.head.user.login }}
        GITHUB_PR_HEAD_USER_ID: ${{ github.event.pull_request.head.user.id }}
        GITHUB_COMMIT_AUTHOR_USERNAME: ${{ github.event.commits[0].author.username }}
        GITHUB_COMMIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        TEST_ATTEMPTS: ${{ inputs.test_attempts }}
        TEST_TYPE: e2e_test
        TEST_RETRY_LEVEL: FAIL
      run: |
        set -x

        python3 -u cobalt/tools/on_device_tests_gateway_client.py \
          --token ${GITHUB_TOKEN} \
          trigger \
          --device_family '${{ inputs.test_device_family }}' \
          --test_type ${TEST_TYPE} \
          --targets '${{ inputs.e2e_test_targets }}' \
          --retry_level ${TEST_RETRY_LEVEL} \
          --label ${TEST_TYPE} \
          --label github_${GITHUB_PR_NUMBER:-postsubmit} \
          --label builder-${{ matrix.platform }} \
          --label builder_url-${GITHUB_RUN_URL} \
          --label github \
          --label ${GITHUB_EVENT_NAME} \
          --label ${GITHUB_WORKFLOW} \
          --label actor-${GITHUB_ACTOR} \
          --label actor_id-${GITHUB_ACTOR_ID} \
          --label triggering_actor-${GITHUB_TRIGGERING_ACTOR} \
          --label sha-${GITHUB_SHA} \
          --label repository-${GITHUB_REPO} \
          --label author-${GITHUB_PR_HEAD_USER_LOGIN:-$GITHUB_COMMIT_AUTHOR_USERNAME} \
          --label author_id-${GITHUB_PR_HEAD_USER_ID:-$GITHUB_COMMIT_AUTHOR_EMAIL} \
          --dimensions '${{ inputs.test_dimensions }}' \
          ${{ contains(matrix.platform, 'android') && format('--cobalt_path "{0}"', env.GCS_ARTIFACTS_PATH) || '' }} \
          ${{ contains(matrix.platform, 'evergreen-arm-hardfp') && format('--cobalt_build "{0}"', env.GCS_ARTIFACTS_PATH) || '' }} \
          || {
            echo "Finished running tests..."
            echo "The test session failed. See logs for details."
            # Fail the job so it's easy to retrigger.
            exit 1
          }
        echo "Finished running tests..."
      shell: bash
