application: gonativeclient
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /demo
  static_files: static/index.html
  upload: static/index\.html
  secure: always

- url: /demo/.*
  static_files: static/index.html
  upload: static/index\.html
  secure: always

- url: /static/home/(.*)
  static_files: static/home/\1
  upload: static/home/.*
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: gonacl.application

skip_files:
- src/.*
