# Copyright (c) 2023, Alliance for Open Media. All rights reserved
#
# This source code is subject to the terms of the BSD 3-Clause Clear License
# and the Alliance for Open Media Patent License 1.0. If the BSD 3-Clause Clear
# License was not distributed with this source code in the LICENSE file, you
# can obtain it at www.aomedia.org/license/software-license/bsd-3-c-c. If the
# Alliance for Open Media Patent License 1.0 was not distributed with this
# source code in the PATENTS file, you can obtain it at
# www.aomedia.org/license/patent.

# proto-file: third_party/libiamf/cli/proto/user_metadata.proto
# proto-message: UserMetadata

test_vector_metadata {
  human_readable_description:
    "A third-order ambisonics + stereo base profile IAMF stream encoded using "
    "Opus."
  file_name_prefix: "test_000305"
  is_valid: true
  mp4_fixed_timestamp: "2023-04-19 00:00:00"
  primary_tested_spec_sections: [
    "3.6.2/loudspeaker_layout == Stereo",
    "3.6.3/ambisonics_mono_config",
    "3.7.4/default_mix_gain",
    "3.11.1/OPUS Specific",
    "4.2/Base Profile",
    "8.5.1/Loudness Information"
  ]
  base_test: "test_000111"
}

ia_sequence_header_metadata {
  ia_code: 0x69616d66  # "iamf"
  primary_profile: PROFILE_VERSION_BASE
  additional_profile: PROFILE_VERSION_BASE
}

codec_config_metadata {
  codec_config_id: 200
  codec_config {
    codec_id: 0x4f707573  # "Opus"
    num_samples_per_frame: 960
    audio_roll_distance: -4
    decoder_config_opus {
      version: 1
      output_channel_count: 2
      pre_skip: 312
      input_sample_rate: 48000
      output_gain: 0
      mapping_family: 0
      opus_encoder_metadata {
        target_bitrate_per_channel: 48000
        application: APPLICATION_AUDIO
      }
    }
  }
}

audio_element_metadata: [
  {
    audio_element_id: 300
    audio_element_type: AUDIO_ELEMENT_SCENE_BASED
    reserved: 0
    codec_config_id: 200
    num_substreams: 16
    audio_substream_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    num_parameters: 0
    ambisonics_config {
      ambisonics_mode: AMBISONICS_MODE_MONO
      ambisonics_mono_config {
        output_channel_count: 16
        substream_count: 16
        channel_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
      }
    }
  },
  {
    audio_element_id: 301
    audio_element_type: AUDIO_ELEMENT_CHANNEL_BASED
    reserved: 0
    codec_config_id: 200
    num_substreams: 1
    audio_substream_ids: [16]
    num_parameters: 0
    scalable_channel_layout_config {
      num_layers: 1
      reserved: 0
      channel_audio_layer_configs: [
        {
          loudspeaker_layout: 1  # Stereo
          output_gain_is_present_flag: 0
          recon_gain_is_present_flag: 0
          reserved_a: 0
          substream_count: 1
          coupled_substream_count: 1
        }
      ]
    }
  }
]

mix_presentation_metadata {
  mix_presentation_id: 42
  count_label: 1
  language_labels: ["en-us"]
  mix_presentation_annotations_array: [
    {
      mix_presentation_friendly_label: "test_mix_pres"
    }
  ]
  num_sub_mixes: 1
  sub_mixes {
    num_audio_elements: 2
    audio_elements: [
      {
        audio_element_id: 300
        mix_presentation_element_annotations_array: [
          {
            audio_element_friendly_label: "test_sub_mix_0_audio_element_0"
          }
        ]
        rendering_config {
          headphones_rendering_mode: HEADPHONES_RENDERING_MODE_STEREO
        }
        element_mix_config {
          mix_gain {
            param_definition {
              parameter_id: 999  # Non-existent; default will be used
              parameter_rate: 48000
              param_definition_mode: 1
              reserved: 0
            }
            default_mix_gain: -768
          }
        }
      },
      {
        audio_element_id: 301
        mix_presentation_element_annotations_array: [
          {
            audio_element_friendly_label: "test_sub_mix_0_audio_element_1"
          }
        ]
        rendering_config {
          headphones_rendering_mode: HEADPHONES_RENDERING_MODE_STEREO
        }
        element_mix_config {
          mix_gain {
            param_definition {
              parameter_id: 998  # Non-existent; default will be used
              parameter_rate: 48000
              param_definition_mode: 1
              reserved: 0
            }
            default_mix_gain: -768
          }
        }
      }
    ]
    output_mix_config {
      output_mix_gain {
        param_definition {
          parameter_id: 997  # Non-existent; default will be used
          parameter_rate: 48000
          param_definition_mode: 1
          reserved: 0
        }
        default_mix_gain: 0
      }
    }
    num_layouts: 1
    layouts {
      loudness_layout {
        layout_type: LAYOUT_TYPE_LOUDSPEAKERS_SS_CONVENTION
        ss_layout {
          sound_system: SOUND_SYSTEM_A_0_2_0
          reserved: 0
        }
      }
      loudness {
        info_type: 0
        integrated_loudness: -3672
        digital_peak: -764
      }
    }
  }
}

audio_frame_metadata: [
  {
    wav_filename: "Transport_TOA_5s.wav"
    samples_to_trim_at_end: 648
    samples_to_trim_at_start: 312
    audio_element_id: 300
    channel_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    channel_labels: ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15"]
  },
  {
    wav_filename: "dialog_clip_stereo.wav"
    samples_to_trim_at_end: 648
    samples_to_trim_at_start: 312
    audio_element_id: 301
    channel_ids: [0, 1]
    channel_labels: ["L2", "R2"]
  }
]

temporal_delimiter_metadata {
  enable_temporal_delimiters: false
}
