name: Set Up Depot Tools
description: Sets up Depot Tools and initializes gclient. Requires source code to be cloned to src/ directory.
inputs:
  run_sync:
    description: Whether or not to run gclient sync.
    default: 'true'
  clear_cache:
    description: Whether or not to clear runner cache.
    default: 'false'
  rbe_instance:
    description: The RBE instance to use.
    default: projects/cobalt-actions-prod/instances/default_instance
  # TODO: b/477593749 - runner-cache is not available on default Github Mac
  # runners and so we special case to use runner.temp for now. Clean this up
  # when self-hosted Mac runners are available.
  use_cache:
    description: Whether or not to use runner cache.
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set Depot Tools Base Path
      id: paths
      env:
        USE_CACHE: ${{ inputs.use_cache }}
      run: |
        if [[ "${USE_CACHE}" == "false" ]]; then
          echo "base_path=${{ runner.temp }}" >> ${GITHUB_OUTPUT}
        else
          echo "base_path=/runner-cache" >> ${GITHUB_OUTPUT}
        fi
      shell: bash

    - name: Clear Cache
      if: inputs.clear_cache == 'true'
      env:
        USE_CACHE: ${{ inputs.use_cache }}
        BASE_PATH: ${{ steps.paths.outputs.base_path }}
        DEPOT_TOOLS_BASE_PATH: ${{ steps.paths.outputs.base_path }}/depot_tools
        CIPD_CACHE_DIR: "${{ steps.paths.outputs.base_path }}/cobalt/.cipd_cache"
      run: |
        set -x
        # Remove gclient/depot tools.
        rm -rf "${DEPOT_TOOLS_BASE_PATH}" "${CIPD_CACHE_DIR}"

        # Reset cobalt checkout by deleting all submodules and cleaning all non-tracked files.
        if [[ "${USE_CACHE}" == "true" ]]; then
          git -C "${BASE_PATH}/cobalt/src" submodule deinit -f --all
          git -C "${BASE_PATH}/cobalt/src" clean -ffdx
        fi
      shell: bash

    - name: Clone Depot Tools
      if: inputs.use_cache == 'false'
      env:
        DEPOT_TOOLS_BASE_PATH: ${{ steps.paths.outputs.base_path }}/depot_tools
      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git "${DEPOT_TOOLS_BASE_PATH}"
      shell: bash

    - name: Reset Cached Depot Tools
      if: inputs.clear_cache == 'false' && inputs.use_cache == 'true'
      env:
        DEPOT_TOOLS_BASE_PATH: ${{ steps.paths.outputs.base_path }}/depot_tools
      run: git -C "${DEPOT_TOOLS_BASE_PATH}" reset --hard origin/main
      shell: bash

    - name: Add Depot Tools to PATH
      env:
        DEPOT_TOOLS_BASE_PATH: ${{ steps.paths.outputs.base_path }}/depot_tools
      run: echo "${DEPOT_TOOLS_BASE_PATH}" >> ${GITHUB_PATH}
      shell: bash

    - name: Bootstrap Bundled python3
      env:
        DEPOT_TOOLS_BASE_PATH: ${{ steps.paths.outputs.base_path }}/depot_tools
      run: |
        # Must be run manually as $DEPOT_TOOLS_UPDATE is 0 in CI, skipping the bootstrap.
        source ${DEPOT_TOOLS_BASE_PATH}/bootstrap_python3 && bootstrap_python3
      shell: bash

    - name: Disable Chromium client side build telemetry
      run: build_telemetry opt-out
      shell: bash

    - name: Run gclient config
      env:
        RBE_INSTANCE: ${{ inputs.rbe_instance }}
      run: |
        cd cobalt
        gclient config \
          --name=src \
          --custom-var=download_remoteexec_cfg=True \
          --custom-var="rbe_instance=\"${RBE_INSTANCE}\"" \
          https://github.com/${{ github.repository }}
      shell: bash

    - name: Set target OS for Android
      if: contains(matrix.platform, 'android')
      run: |
        cd cobalt
        echo "target_os=['android']" >> .gclient
        gclient validate
      shell: bash

    - name: Set target OS for tvOS
      if: contains(matrix.platform, 'tvos')
      run: |
        cd cobalt
        echo "target_os=['ios']" >> .gclient
        gclient validate
      shell: bash

    - name: Run gclient sync
      if: inputs.run_sync == 'true'
      run: |
        cd cobalt
        gclient sync \
          --verbose \
          --shallow \
          --no-history \
          --nohooks \
          --force \
          --delete_unversioned_trees \
          --revision ${{ github.sha }}
      shell: bash

    - name: Run gclient runhooks
      if: inputs.run_sync == 'true'
      run: |
        cd cobalt
        gclient runhooks --verbose
      shell: bash
