name: Set Up Depot Tools
description: Sets up Depot Tools and initializes gclient. Optionally performs checkout and uses git cache.

inputs:
  run_sync:
    description: Whether or not to run gclient sync.
    default: 'true'
  rbe_instance:
    description: The RBE instance to use.
    default: projects/cobalt-actions-prod/instances/default_instance
  use_cache:
    description: Whether or not to use runner cache.
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set Cache Path
      id: cache-path
      shell: bash
      env:
        USE_CACHE: ${{ inputs.use_cache }}
      run: |
        if [[ "${USE_CACHE}" == "true" ]] && [[ -w "/runner-cache" ]]; then
          echo "path=/runner-cache" >> ${GITHUB_OUTPUT}
        else
          echo "path=" >> ${GITHUB_OUTPUT}
        fi

    - name: Clone Depot Tools
      uses: ./.github/actions/checkout
      with:
        repository: https://chromium.googlesource.com/chromium/tools/depot_tools.git
        ref: main
        fetch_depth: 0
        path: depot_tools
        use_cache: ${{ inputs.use_cache }}

    - name: Add Depot Tools to PATH
      run: echo "${GITHUB_WORKSPACE}/depot_tools" >> ${GITHUB_PATH}
      shell: bash

    - name: Set CIPD Cache Directory
      if: steps.cache-path.outputs.path != ''
      run: echo "CIPD_CACHE_DIR=${{ steps.cache-path.outputs.path }}/cipd-cache" >> ${GITHUB_ENV}
      shell: bash

    - name: Bootstrap Bundled python3
      run: |
        # Must be run manually as $DEPOT_TOOLS_UPDATE is 0 in CI, skipping the bootstrap.
        source ${GITHUB_WORKSPACE}/depot_tools/bootstrap_python3 && bootstrap_python3
      shell: bash

    - name: Disable Chromium client side build telemetry
      run: build_telemetry opt-out
      shell: bash

    - name: Run gclient config
      env:
        RBE_INSTANCE: ${{ inputs.rbe_instance }}
        REPOSITORY: ${{ github.server_url }}/${{ github.repository }}
        CACHE_PATH: ${{ steps.cache-path.outputs.path }}
      run: |
        set -x
        cd cobalt

        CACHE_ARG=()
        if [[ -n "${CACHE_PATH}" ]]; then
          CACHE_ARG=(--cache-dir="${CACHE_PATH}"/git-cache)
        fi

        gclient config \
          --name=src \
          "${CACHE_ARG[@]}" \
          --custom-var=download_remoteexec_cfg=True \
          --custom-var="rbe_instance=\"${RBE_INSTANCE}\"" \
          "${REPOSITORY}"
      shell: bash

    - name: Set target OS for Android
      if: contains(matrix.platform, 'android')
      run: |
        cd cobalt
        echo "target_os=['android']" >> .gclient
        gclient validate
      shell: bash

    - name: Set target OS for tvOS
      if: contains(matrix.platform, 'tvos')
      run: |
        cd cobalt
        echo "target_os=['ios']" >> .gclient
        gclient validate
      shell: bash

    - name: Run gclient sync
      if: inputs.run_sync == 'true'
      env:
        REF: ${{ github.sha }}
      run: |
        cd cobalt
        gclient sync \
          --verbose \
          --shallow \
          --no-history \
          --nohooks \
          --force \
          --delete_unversioned_trees \
          --revision "${REF}"
      shell: bash

    - name: Run gclient runhooks
      if: inputs.run_sync == 'true'
      run: |
        cd cobalt
        gclient runhooks --verbose
      shell: bash
