caption: App Launch Automation
desc: Setting this policy allows administrators to configure automation for
  launching apps on <ph name="PRODUCT_NAME">$1<ex>Google ChromeOS</ex></ph>
  devices. These apps can be launched on user login, or users can launch them
  together from the launcher.
example_value:
- auto_launch_on_startup: false
  created_time_usec: '13320917261678808'
  desk:
    apps:
    - app_type: browser
      browser_tabs:
      - url: https://www.chromium.org
      window_id: 30002
    - app_type: browser
      browser_tabs:
      - url: chrome://version/
      - url: https://dev.chromium.org
      window_id: 30001
  name: App Automation 1
  updated_time_usec: '13320917261678808'
  uuid: 27ea906b-a7d3-40b1-8c36-76d332d7f184
- created_time_usec: '13320917271679905'
  desk:
    apps:
    - app_type: browser
      browser_tabs:
      - url: https://www.google.com/
      - url: https://www.youtube.com/
      window_id: 30001
  name: App Automation 2
  updated_time_usec: '13320917271679905'
  uuid: 3aa30d88-576e-48ea-ab26-cbdd2cbe43a1
features:
  dynamic_refresh: true
  per_profile: false
future_on:
- chrome_os
owners:
- yzd@google.com
- cros-commercial-productivity-policy-eng@google.com
schema:
  type: array
  items:
    type: object
    properties:
      auto_launch_on_startup:
        type: boolean
      created_time_usec:
        type: string
      desk:
        type: object
        properties:
          apps:
            type: array
            items:
              type: object
              properties:
                app_type:
                  enum:
                  - android
                  - browser
                  - chrome_app
                  - isolated_web_app
                  - progressive_web_app
                  type: string
                browser_tabs:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                window_id:
                  type: integer
      name:
        type: string
      updated_time_usec:
        type: string
      uuid:
        type: string
tags: []
type: dict
