caption: Application locale
desc: |-
  Setting the policy specifies the locale <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> uses.

        Turning it off or leaving it unset means the locale will be the first valid locale from:
        1) The user specified locale (if configured).
        2) The system locale.
        3) The fallback locale (en-US).
example_value: en
features:
  can_be_recommended: true
  dynamic_refresh: false
  per_profile: false
label: Application locale
owners:
- file://components/policy/OWNERS
- hendrich@chromium.org
schema:
  type: string
supported_on:
- chrome.win:8-
tags: []
type: string
