caption: Allow saving images directly to <ph name="GOOGLE_PHOTOS_PRODUCT_NAME">Google Photos</ph>
default: 0
desc: This policy controls whether the user is allowed to save images to <ph name="GOOGLE_PHOTOS_PRODUCT_NAME">Google Photos</ph> 
  directly from the context menu.

  Setting the policy to Enabled or leaving it unset allows the user to save images to <ph name="GOOGLE_PHOTOS_PRODUCT_NAME">Google Photos</ph> from the context menu.
  Setting the policy to Disabled prevent users seeing the option in the context menu.

  This policy does not prevent users from saving images to <ph name="GOOGLE_PHOTOS_PRODUCT_NAME">Google Photos</ph> using other ways beside the context menu.
example_value: 0
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: The context menu will have a menu item to share images to <ph name="GOOGLE_PHOTOS_PRODUCT_NAME">Google Photos</ph>.
  name: Enabled
  value: 0
- caption: The context menu will not have a menu item to share images to <ph name="GOOGLE_PHOTOS_PRODUCT_NAME">Google Photos</ph>.
  name: Disabled
  value: 1
owners:
- qpubert@google.com
- olivierrobin@google.com
schema:
  enum:
  - 0
  - 1
  type: integer
supported_on:
- ios:120-
tags: []
type: int-enum