caption: Contextual integrations of Google services on <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph>
desc: |-
  Improve productivity by allowing information from Google apps and services to appear on <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> system surfaces.

  An integration will be displayed if the associated Google service is turned on.

  When <ph name="CONTEXTUAL_GOOGLE_INTEGRATIONS_ENABLED">ContextualGoogleIntegrationsEnabled</ph> is Disabled, all services will be disabled, regardless the settings of this policy.

  When <ph name="CONTEXTUAL_GOOGLE_INTEGRATIONS_ENABLED">ContextualGoogleIntegrationsEnabled</ph> is Enabled or not set, services can be selected by this policy.

  If this policy is left unset, all services will be enabled.

  Otherwise, only selected services will be enabled.
example_value:
- GoogleCalendar
- GoogleClassroom
- GoogleTasks
features:
  dynamic_refresh: true
  per_profile: true
items:
# `GoogleCalendar` will eventually replace `CalendarIntegrationEnabled` policy.
- caption: <ph name="GOOGLE_CALENDAR_NAME">Google Calendar</ph>
  name: GoogleCalendar
  value: GoogleCalendar
# `GoogleClassroom` will not be immediately supported.
- caption: <ph name="GOOGLE_CLASSROOM_NAME">Google Classroom</ph>
  name: GoogleClassroom
  value: GoogleClassroom
- caption: <ph name="GOOGLE_TASKS_NAME">Google Tasks</ph>
  name: GoogleTasks
  value: GoogleTasks
- caption: <ph name="CHROME_SYNC_NAME">Chrome Sync</ph>
  name: ChromeSync
  value: ChromeSync
- caption: <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>
  name: GoogleDrive
  value: GoogleDrive
- caption: Weather
  name: Weather
  value: Weather
owners:
- amitrokhin@google.com
- file://ash/glanceables/OWNERS
schema:
  items:
    enum:
    - GoogleCalendar
    - GoogleClassroom
    - GoogleTasks
    - ChromeSync
    - GoogleDrive
    - Weather
    type: string
  type: array
supported_on:
- chrome_os:125-
tags: []
type: string-enum-list
