caption: Allow saving files directly to <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>
default: 0
desc: This policy controls whether the user is allowed to save files to <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>
  directly from the download manager.

  Setting the policy to Enabled or leaving it unset allows the user to save files to <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> from the download manager.
  Setting the policy to Disabled prevent users seeing the option in the download manager.

  This policy does not prevent users from saving files to <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> using other ways beside the download manager.
example_value: 0
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: The download manager will have an option to save files to <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>.
  name: Enabled
  value: 0
- caption: The download manager will not have an option to save files to <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>.
  name: Disabled
  value: 1
owners:
- qpubert@google.com
- olivierrobin@google.com
schema:
  enum:
  - 0
  - 1
  type: integer
supported_on:
- ios:123-
tags: []
type: int-enum