caption: Dynamic Code Settings
default: 0
desc: |-
  This policy controls the dynamic code settings for <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph>.

  Disabling dynamic code improves the security of <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> by preventing potentially hostile dynamic code and third-party code from making changes to <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph>'s behavior, but might cause compatibility issues with third-party software that must run inside the browser process.

  If the policy is set to 0 - Default or left unset then <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> will use the default settings.

  If the policy is set to 1 - DisabledForBrowser then the <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph> browser process will be prevented from creating dynamic code.

  Note: Read more about process mitigation policies ( https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/sandbox.md#Process-mitigation-policies ).
example_value: 1
features:
  dynamic_refresh: false
  per_profile: false
items:
- caption: Default dynamic code settings
  name: Default
  value: 0
- caption: Prevent the browser process from creating dynamic code
  name: DisabledForBrowser
  value: 1
owners:
- wfh@chromium.org
- file://sandbox/win/OWNERS
schema:
  type: integer
  enum:
  - 0
  - 1
supported_on:
- chrome.win:127-
tags:
- system-security
type: int-enum
