caption: Controls visibility of enterprise profile badge in the toolbar
default: 0
desc: |-
  For work and school profiles, the toolbar will show a "Work" or "School" label by default next to the toolbar avatar. The label will only be shown if the signed in account is managed.

  Setting this policy to <ph name="HIDE_EXPANDED_ENTERPRISE_TOOLBAR_BADGE">hide_expanded_enterprise_toolbar_badge</ph> (value 1) will hide the enterprise badge for a managed profile in the toolbar.

  Leaving this policy unset or setting it to <ph name="SHOW_EXPANDED_ENTERPRISE_TOOLBAR_BADGE">show_expanded_enterprise_toolbar_badge</ph> (value 0) will show the enterprise badge.

  The label is customizable via the <ph name="ENTERPRISE_CUSTOM_LABEL_POLICY_NAME">EnterpriseCustomLabel</ph> policy.
example_value: 1
features:
  dynamic_refresh: true
  per_profile: true
supported_on:
- chrome.*:131-
items:
- caption: Show expanded enterprise toolbar badge
  name: show_enterprise_toolbar_badge
  value: 0
- caption: Hide expanded enterprise toolbar badge
  name: hide_enterprise_toolbar_badge
  value: 1
owners:
- ydago@chromium.org
- file://components/enterprise/OWNERS
schema:
  enum:
  - 0
  - 1
  type: integer
tags: []
type: int-enum
