caption: Allow choosing files directly from <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>
default: 0
desc: This policy controls whether the user is allowed to choose files from <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph>
  directly when a website contains a form where files can be submitted.

  Setting the policy to "Show <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> option." (0) or not setting the policy allows the user to choose files from <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> in the file selection menu.

  Setting the policy to "Hide <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> option." (1) hides the <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> option in the file selection menu.

  This policy does not prevent users from choosing files from <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> using other ways beside the 'Google Drive' action in the file selection menu.
example_value: 0
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: Show <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> option.
  name: Enabled
  value: 0
- caption: Hide <ph name="GOOGLE_DRIVE_NAME">Google Drive</ph> option.
  name: Disabled
  value: 1
owners:
- qpubert@google.com
- olivierrobin@google.com
schema:
  enum:
  - 0
  - 1
  type: integer
supported_on:
- ios:133-
tags: []
type: int-enum