caption: Select task scheduler configuration
desc: |-
  Setting the policy instructs <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> to use the task scheduler configuration identified by the specified name. This policy can be set to <ph name="CONSERVATIVE_VALUE">Conservative</ph> or <ph name="PERFORMANCE_VALUE">Performance</ph>, which tune the task scheduler for stability or maximum performance, respectively.

        If unset, users make their own choice.
example_value: performance
features:
  can_be_recommended: true
  dynamic_refresh: true
  per_profile: false
items:
- caption: Optimize for stability.
  name: Conservative
  value: conservative
- caption: Optimize for performance.
  name: Performance
  value: performance
owners:
- file://components/policy/OWNERS
- emaxx@chromium.org
schema:
  enum:
  - conservative
  - performance
  type: string
supported_on:
- chrome_os:74-
tags: []
type: string-enum
