name: Prepare Runner Cache
description: Check the runner cache directory for build
runs:
  using: "composite"
  steps:
    - name: Check Runner Cache Status
      run: |
        # If .git/index.lock exists, it indicates a previous abnormal exit.
        if [ -f "${CHECKOUT_PATH}/.git/index.lock" ]; then
          echo "index.lock found, removing the cache."
          rm -f "${CHECKOUT_PATH}"
        fi
        # Check src already exists by earlier runners:
        if [ -d "${CHECKOUT_PATH}/.git" ]; then
          echo "Existing Git repository found. Performing hard reset and clean."
          cd "${CHECKOUT_PATH}"
          git reset --hard
          # Remove unmerged/conflict markers if any merge was aborted
          git merge --abort || true
        fi
        # Ensure the base directory exists before the symlink step
        mkdir -p /runner-cache/cobalt
      env:
        CHECKOUT_PATH: /runner-cache/cobalt/src
      shell: bash
    - name: Link Runner Cache
      run: |
        ln -sf /runner-cache/cobalt ${GITHUB_WORKSPACE}/cobalt
      shell: bash
    - name: Set Safe Directory
      run: git config --global --add safe.directory "${GITHUB_WORKSPACE}/cobalt/src"
      shell: bash
