name: Install Sccache
description: Installs sccache
inputs:
  sccache_gcs_key:
    description: "The keyfile needed to access our sccache."
    required: true
runs:
  using: "composite"
  steps:
  - name: Install sccache
    shell: bash
    run: brew install sccache
  - name: Configure sccache
    shell: bash
    env:
      SCCACHE_GCS_KEY: ${{ inputs.sccache_gcs_key }}
    run: |
      printf "%s" "$SCCACHE_GCS_KEY" > "${HOME}/gcloud.json"
      echo "SCCACHE_GCS_RW_MODE=READ_WRITE" >> $GITHUB_ENV
      echo "SCCACHE_GCS_KEY_PATH=${HOME}/gcloud.json" >> $GITHUB_ENV
      echo "SCCACHE_GCS_BUCKET=cobalt-sccache-tvos-bucket" >> $GITHUB_ENV
      echo "SCCACHE=1" >> $GITHUB_ENV
      echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
  - name: Start sccache server
    shell: bash
    run: |
      sccache --stop-server || true
      sccache --start-server
