name: Install Sccache
description: Installs sccache
inputs:
  sccache_gcs_key:
    description: "The keyfile needed to access our sccache."
    required: true
runs:
  using: "composite"
  steps:
  - name: Install sccache
    shell: bash
    run: brew install sccache
  - name: Configure sccache
    shell: bash
    env:
      SCCACHE_GCS_KEY: ${{ inputs.sccache_gcs_key }}
    run: |
      set -x
      base64 -D -i "${GITHUB_WORKSPACE}/.github/resources/test_reference.jpeg" > "${HOME}/gcloud.json"
      echo "SCCACHE_GCS_KEY_PATH=${HOME}/gcloud.json" >> $GITHUB_ENV
      echo "SCCACHE=1" >> $GITHUB_ENV
      echo "SCCACHE_GCS_BUCKET=cobalt-sccache-tvos-bucket" >> $GITHUB_ENV
      echo "SCCACHE_GCS_RW_MODE=READ_WRITE" >> $GITHUB_ENV
      echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV

      export SCCACHE_GCS_KEY_PATH="${HOME}/gcloud.json"
      export SCCACHE_GCS_BUCKET="cobalt-sccache-tvos-bucket"
      export SCCACHE_GCS_RW_MODE="READ_WRITE"
      export SCCACHE_IDLE_TIMEOUT="0"
      export ENABLE_SCCACHE="true"

      sccache --stop-server || true
      sccache --start-server
