name: Install Sccache
description: Installs sccache
inputs:
  sccache_gcs_key:
    description: "The keyfile needed to access our sccache."
    required: true
runs:
  using: "composite"
  steps:
  - name: Install sccache
    shell: bash
    run: brew install sccache
  - name: Configure sccache
    shell: bash
    env:
      SCCACHE_GCS_KEY: ${{ inputs.sccache_gcs_key }}
    run: |
      set -x
      echo "$SCCACHE_GCS_KEY" > "${HOME}/gcloud.json"
      echo "SCCACHE_GCS_KEY_PATH=${HOME}/gcloud.json" >> $GITHUB_ENV
      echo "SCCACHE=1" >> $GITHUB_ENV
      echo "SCCACHE_GCS_BUCKET=cobalt-kokoro-sccache-mac" >> $GITHUB_ENV
      echo "SCCACHE_GCS_RW_MODE=READ_WRITE" >> $GITHUB_ENV
      echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
  - name: Set Up Cloud SDK
    uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    with:
      project_id: yt-cobalt
