#!/usr/bin/env python3
"""Automated Comparative Review & Skill Learning Pipeline.

Compares Human Ground-Truth PR fixes against AI Rebase attempts.
Uses the Tier-2 Expert Model (Claude Sonnet 5, GLM 5.2) to:
1. Identify key differences between Human and AI approaches.
2. Analyze why AI diverged (missed upstream shifts, unnecessary edits, etc.).
3. Generate or update Skill documentation in reasoning_engine/skills/*.md.
4. Persist structured lessons to the GCS Knowledge Bank.

Convention:
  In Cobalt autoroll PRs, the first 5 commits are the roller baseline.
  All subsequent commits (from commit 6 onwards) are the fix commits.

Usage:
  python3 .github/rebase/review_pipeline.py \
    --human-pr 12161 \
    --ai-pr 12176 \
    --update-skills
"""

import argparse
import json
import os
import re
import subprocess
import sys
from typing import Any, Dict, List, Optional, Set, Tuple

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(SCRIPT_DIR)
if SCRIPT_DIR not in sys.path:
  sys.path.insert(0, SCRIPT_DIR)
if PARENT_DIR not in sys.path:
  sys.path.insert(0, PARENT_DIR)

# pylint: disable=wrong-import-position
from base_resolver import execute_local_tool
from engine_client import ReasoningEngineClient
from reasoning_engine.engine import CobaltReasoningEngine

SKILLS_DIR = os.path.join(SCRIPT_DIR, "reasoning_engine", "skills")


def run_cmd(cmd: List[str], cwd: Optional[str] = None) -> Tuple[bool, str, str]:
  """Runs a shell command and returns (success, stdout, stderr)."""
  try:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=90,
        check=False,
    )
    return proc.returncode == 0, proc.stdout.strip(), proc.stderr.strip()
  except Exception as e:  # pylint: disable=broad-exception-caught
    return False, "", str(e)


def extract_pr_number(pr_input: str) -> str:
  """Extracts numeric PR ID from number or GitHub PR URL."""
  m = re.search(r"/pull/(\d+)", pr_input)
  if m:
    return m.group(1)
  clean = pr_input.strip().lstrip("#")
  if clean.isdigit():
    return clean
  return pr_input


def fetch_pr_info(pr_num: str) -> Optional[Dict[str, Any]]:
  """Fetches PR metadata, commits, and files via gh CLI."""
  ok, out, err = run_cmd([
      "gh", "pr", "view", pr_num, "--json",
      "number,title,body,commits,files,baseRefName,headRefName"
  ])
  if not ok:
    print(f"[ERROR] Failed to fetch PR #{pr_num}: {err}", file=sys.stderr)
    return None
  try:
    return json.loads(out)
  except json.JSONDecodeError:
    return None


def partition_roll_commits(
    commits: List[Dict[str, Any]]
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
  """Partitions roll PR commits.

  The first 5 commits are generated by the roller to bring Chromium code;
  all subsequent commits are the fix commits.
  """
  if len(commits) > 5:
    return commits[:5], commits[5:]
  return [], commits


def get_diff_for_commits(commits: List[Dict[str, Any]],
                         repo_root: str,
                         base_sha: Optional[str] = None) -> str:
  """Calculates git diff across a list of commits."""
  if not commits:
    return ""

  first_sha = base_sha or commits[0].get("oid", "")
  last_sha = commits[-1].get("oid", "")

  if first_sha and last_sha:
    diff_range = (f"{first_sha}..{last_sha}"
                  if base_sha else f"{first_sha}^..{last_sha}")
    ok, out, _ = run_cmd(["git", "diff", diff_range], cwd=repo_root)
    if ok and out:
      return out

  # Fallback: git show individual commits
  diff_chunks = []
  for c in commits:
    sha = c.get("oid", "")
    headline = c.get("messageHeadline", "")
    ok, out, _ = run_cmd(["git", "show", "--stat", "-p", sha], cwd=repo_root)
    if ok and out:
      diff_chunks.append(f"Commit: {sha} ({headline})\n{out}")

  return "\n\n".join(diff_chunks)


def extract_modified_files_from_diff(diff_text: str) -> Set[str]:
  """Extracts list of modified file paths from unified diff."""
  files = set()
  for line in diff_text.splitlines():
    if line.startswith("+++ b/"):
      files.add(line[6:].strip())
  return files


def is_comment_or_whitespace_line(line: str) -> bool:
  """Checks if a diff line is whitespace-only or a comment line."""
  stripped = line.strip()
  if not stripped:
    return True
  if stripped.startswith(("+", "-")) and not stripped.startswith(
      ("+++", "---")):
    stripped = stripped[1:].strip()
  if not stripped:
    return True
  # C++ / JS / Java / GN comments
  if stripped.startswith(("//", "/*", "*", "*/", '"""', "'''")):
    return True
  # Python/Shell comments (protect C/C++ preprocessor directives)
  if stripped.startswith("#"):
    cpp_directives = (
        "#include",
        "#if",
        "#ifdef",
        "#ifndef",
        "#else",
        "#elif",
        "#endif",
        "#define",
        "#undef",
        "#pragma",
        "#error",
        "#warning",
    )
    if any(stripped.startswith(d) for d in cpp_directives):
      return False
    return True
  return False


def extract_functional_diff_lines(diff_text: str) -> Set[str]:
  """Extracts normalized functional code lines from a diff."""
  functional_lines = set()
  for line in diff_text.splitlines():
    if line.startswith(("+", "-")) and not line.startswith(("+++", "---")):
      prefix = line[0]  # '+' or '-'
      content = line[1:].strip()
      if not content or is_comment_or_whitespace_line(line):
        continue
      # Normalize whitespace runs inside functional code
      normalized_content = " ".join(content.split())
      functional_lines.add(f"{prefix} {normalized_content}")
  return functional_lines


def calculate_ai_pr_metrics(
    human_files: Set[str],
    ai_files: Set[str],
    human_diff: str,
    ai_diff: str,
) -> Dict[str, Any]:
  """Calculates Jaccard Similarity on modified files and code lines."""
  # 1. File-level Jaccard Overlap
  both_files = human_files & ai_files
  human_only_files = human_files - ai_files
  ai_only_files = ai_files - human_files
  union_files = human_files | ai_files

  file_jaccard = ((len(both_files) / len(union_files)) *
                  100.0 if union_files else 100.0)

  # 2. Functional Code Line Jaccard Overlap (excluding comments/whitespace)
  human_code_lines = extract_functional_diff_lines(human_diff)
  ai_code_lines = extract_functional_diff_lines(ai_diff)
  shared_code_lines = human_code_lines & ai_code_lines
  human_only_code_lines = human_code_lines - ai_code_lines
  ai_only_code_lines = ai_code_lines - human_code_lines
  union_code_lines = human_code_lines | ai_code_lines

  code_jaccard = ((len(shared_code_lines) / len(union_code_lines)) *
                  100.0 if union_code_lines else 100.0)

  # 3. Overall Combined Jaccard Similarity (50% File, 50% Functional Code)
  overall_similarity = round((file_jaccard + code_jaccard) / 2.0, 1)

  return {
      "overall_similarity": overall_similarity,
      "file_jaccard": round(file_jaccard, 1),
      "code_jaccard": round(code_jaccard, 1),
      "total_human_files": len(human_files),
      "total_ai_files": len(ai_files),
      "shared_files_count": len(both_files),
      "human_only_files_count": len(human_only_files),
      "ai_only_files_count": len(ai_only_files),
      "total_human_code_lines": len(human_code_lines),
      "total_ai_code_lines": len(ai_code_lines),
      "shared_code_lines_count": len(shared_code_lines),
      "human_only_code_lines_count": len(human_only_code_lines),
      "ai_only_code_lines_count": len(ai_only_code_lines),
  }


def format_metrics_markdown(metrics: Dict[str, Any]) -> str:
  """Renders clean Jaccard similarity scorecard table in Markdown."""
  ovr = metrics["overall_similarity"]
  fj = metrics["file_jaccard"]
  cj = metrics["code_jaccard"]
  thf = metrics["total_human_files"]
  taf = metrics["total_ai_files"]
  sfc = metrics["shared_files_count"]
  hofc = metrics["human_only_files_count"]
  aofc = metrics["ai_only_files_count"]
  thcl = metrics["total_human_code_lines"]
  tacl = metrics["total_ai_code_lines"]
  sclc = metrics["shared_code_lines_count"]
  hoclc = metrics["human_only_code_lines_count"]
  aoclc = metrics["ai_only_code_lines_count"]

  return ("## Jaccard Similarity & Divergence Scorecard\n\n"
          "| Evaluation Scope | Jaccard Overlap | Human Ground-Truth | "
          "AI Rebase Attempt | Shared (Exact Matches) | "
          "Divergence (Differences) |\n"
          "| :--- | :--- | :--- | :--- | :--- | :--- |\n"
          f"| **Overall Rebase Alignment** | **{ovr}%** | — | — | — | "
          "Composite (50% Files + 50% Functional Code) |\n"
          f"| **Modified Files** | **{fj}%** | {thf} files | {taf} files | "
          f"{sfc} shared files | {hofc} missed, {aofc} extra |\n"
          f"| **Functional Code Lines** | **{cj}%** | {thcl} lines | "
          f"{tacl} lines | {sclc} matching lines | "
          f"{hoclc} missed, {aoclc} divergent |\n\n"
          "> *Note: Functional code lines compare added/deleted logic "
          "excluding comments, blank lines, and whitespace.*")


def extract_single_file_diff(diff_text: str, target_file: str) -> str:
  """Extracts diff block for a specific file from a multi-file diff."""
  clean_target = target_file.strip().lstrip("./")
  chunks = []
  capturing = False

  for line in diff_text.splitlines():
    if line.startswith("diff --git ") or line.startswith("+++ b/"):
      if clean_target in line:
        capturing = True
        chunks.append(line)
        continue
      if capturing and line.startswith("diff --git "):
        break
    if capturing:
      chunks.append(line)

  return "\n".join(chunks).strip()


def execute_review_tool(
    cmd: str,
    repo_root: str,
    human_diff: str,
    ai_diff: str,
) -> str:
  """Executes safe read-only inspection tools for review pipeline."""
  clean_cmd = cmd.strip()
  if clean_cmd.startswith("TOOL_DIFF_FILE:"):
    file_path = clean_cmd.split(":", 1)[1].strip()
    if not file_path:
      return "[ERROR] No file path provided to TOOL_DIFF_FILE."
    h_file_diff = extract_single_file_diff(human_diff, file_path)
    a_file_diff = extract_single_file_diff(ai_diff, file_path)
    h_msg = h_file_diff or "(No changes in Human PR)"
    a_msg = a_file_diff or "(No changes in AI PR)"
    return (f"=== Target File: {file_path} ===\n\n"
            f"--- Human Ground-Truth Fix Diff ---\n"
            f"{h_msg}\n\n"
            f"--- AI Rebase Attempt Diff ---\n"
            f"{a_msg}\n")

  return execute_local_tool(clean_cmd, repo_root)


def load_cobalt_skills_context(skills_dir: str = SKILLS_DIR) -> str:
  """Loads Cobalt architectural rules and rebase principles from skills."""
  if not os.path.isdir(skills_dir):
    return ""

  docs = []
  skill_files = [
      "cobalt_rebase.md",
      "compiler_healing.md",
      "gn_healing.md",
      "roll_history.md",
  ]
  for filename in skill_files:
    fpath = os.path.join(skills_dir, filename)
    if os.path.isfile(fpath):
      try:
        with open(fpath, "r", encoding="utf-8", errors="replace") as f:
          content = f.read().strip()
          docs.append(f"### Domain Skill Guide: {filename}\n{content}")
      except Exception:  # pylint: disable=broad-exception-caught
        pass

  return "\n\n".join(docs)


# pylint: disable=too-many-positional-arguments,too-many-arguments,protected-access
def generate_comparative_review(
    engine_or_client: Any,
    human_pr_data: Dict[str, Any],
    ai_pr_data: Dict[str, Any],
    human_diff: str,
    ai_diff: str,
    both_files: List[str],
    human_only_files: List[str],
    ai_only_files: List[str],
    repo_root: str = "",
    expert_model: Optional[str] = None,
) -> str:
  """Uses Tier-2 Expert Agent to interactively inspect file diffs."""
  h_num = human_pr_data.get("number", "")
  h_title = human_pr_data.get("title", "")
  a_num = ai_pr_data.get("number", "")
  a_title = ai_pr_data.get("title", "")

  both_summary = "\n".join(f"- {f}" for f in both_files) or "None"
  human_only_summary = "\n".join(f"- {f}" for f in human_only_files) or "None"
  ai_only_summary = "\n".join(f"- {f}" for f in ai_only_files) or "None"

  skills_context = load_cobalt_skills_context()

  sys_inst = (
      "You are the Senior Principal Chromium and Cobalt Systems Architect.\n"
      "Your mission is to perform a rigorous post-mortem review comparing a "
      "Human Expert (Igalia/Google) rebase fix vs. an AI Rebase attempt.\n\n"
      f"=== Cobalt Architectural & Rebase Knowledge Base ===\n"
      f"{skills_context}\n\n"
      "Context & Objectives:\n"
      "- In Human PR, the first 5 commits are the roll baseline, "
      "and subsequent commits are the human fixes.\n"
      "- Inspect diffs on demand with:\n"
      "    TOOL_DIFF_FILE: <filepath>\n"
      "    TOOL_UPSTREAM_DIFF: <filepath>\n"
      "    TOOL_READ_FILE: <path> <start>-<end>\n"
      "    TOOL_GIT_LOG: <count> <filepath>\n"
      "    TOOL_GREP: <symbol>\n\n"
      "Guidelines:\n"
      "1. In your first turns, request `TOOL_DIFF_FILE:` for critical files.\n"
      "2. Once you have sufficient evidence, emit your final review report.\n\n"
      "Required Final Output Structure:\n"
      f"# Post-Mortem Comparative Review: Human (PR #{h_num}) vs. "
      f"AI (PR #{a_num})\n\n"
      "## 1. Executive Summary & Upstream Evolution\n"
      "## 2. Key Differences in Resolution Approach\n"
      "### A. Divergences in Shared Files (Human vs. AI)\n"
      "### B. Files Modified Only by Human (Missed by AI)\n"
      "### C. Files Modified Only by AI (Unnecessary/Suboptimal Edits)\n"
      "## 3. Extracted Rebase Rules & Knowledge Items\n"
      "Format each atomic lesson as:\n"
      "```lesson\n"
      "TARGET: <filepath>\n"
      "ISSUE: <brief description of break>\n"
      "RULE: <actionable rule/technique for AI>\n"
      "```\n\n"
      "## 4. Skill Document Updates\n"
      "Format proposed skill additions as:\n"
      "```skill_update: <skill_file.md>\n"
      "### <Section Title>\n"
      "<detailed markdown guidance to append to the skill file>\n"
      "```")

  prompt = (
      f"Human Ground-Truth PR: #{h_num} - {h_title}\n"
      f"AI Rebase Attempt PR: #{a_num} - {a_title}\n\n"
      f"=== Modified Files Inventory ===\n"
      f"Shared Files Modified by Both ({len(both_files)}):\n"
      f"{both_summary}\n\n"
      f"Files Modified by Human Only (Missed by AI - "
      f"{len(human_only_files)}):\n{human_only_summary}\n\n"
      f"Files Modified by AI Only (Unnecessary/Extra - "
      f"{len(ai_only_files)}):\n{ai_only_summary}\n\n"
      "Please request the specific file diffs using "
      "`TOOL_DIFF_FILE: <filepath>` for the files you wish to inspect first, "
      "or provide your review if ready.")

  exp_label = expert_model or "Default"
  print(
      f"  [REVIEW] Starting Interactive Review Session with ({exp_label})...",
      file=sys.stderr)
  current_prompt = prompt
  accumulated_tool_context = []

  for round_idx in range(1, 8):
    if hasattr(engine_or_client, "_generate_expert_content"):
      response = engine_or_client._generate_expert_content(
          current_prompt, sys_inst, expert_model=expert_model)
    elif hasattr(engine_or_client, "query"):
      res = engine_or_client.query(
          action="chat",
          message=f"{sys_inst}\n\n{current_prompt}",
          expert_model=expert_model,
          use_pro=True,
      )
      response = res.get("response", "") if isinstance(res, dict) else str(res)
    else:
      break

    if not response:
      break

    tool_matches = re.findall(r"(TOOL_[A-Z_]+:[^\n]+)", response.strip())
    if not tool_matches:
      return response

    print(
        f"  [REVIEW] [Turn {round_idx}] Expert requested "
        f"{len(tool_matches)} tool(s):",
        file=sys.stderr)
    round_tool_results = []
    for tool_cmd in tool_matches[:10]:
      clean_tool = tool_cmd.strip()
      print(f"    -> {clean_tool}", file=sys.stderr)
      tool_output = execute_review_tool(clean_tool, repo_root, human_diff,
                                        ai_diff)
      round_tool_results.append(
          f"Tool `{clean_tool}` Output:\n```\n{tool_output[:5000]}\n```")

    accumulated_tool_context.extend(round_tool_results)
    if round_idx >= 3 or len(accumulated_tool_context) >= 15:
      next_instruction = (
          "You have now inspected key diffs and files across the PR. "
          "Please now generate your complete, exhaustive final post-mortem "
          "comparative review report following the required structure:\n"
          f"# Post-Mortem Comparative Review: Human (PR #{h_num}) vs. "
          f"AI (PR #{a_num})\n"
          "## 1. Executive Summary & Upstream Evolution\n"
          "## 2. Key Differences in Resolution Approach\n"
          "## 3. Extracted Rebase Rules & Knowledge Items (with ```lesson)\n"
          "## 4. Skill Document Updates (with ```skill_update)")
    else:
      next_instruction = (
          "If you need further file diffs, output `TOOL_DIFF_FILE: <path>`. "
          "Otherwise, proceed with your comprehensive final review report.")

    accum_len = len(accumulated_tool_context)
    current_prompt = (f"{prompt}\n\n"
                      f"--- Investigation Tool Results ({accum_len}) ---\n"
                      f"{chr(10).join(accumulated_tool_context[-20:])}\n\n"
                      f"{next_instruction}")

  return response or ""


def apply_skill_updates(review_text: str) -> List[str]:
  """Appends skill update blocks to files in reasoning_engine/skills/."""
  updates = re.findall(r"```skill_update:\s*([a-zA-Z0-9_\-\.]+)\n(.*?)```",
                       review_text, re.DOTALL)
  updated_files = []

  for filename, content in updates:
    target_path = os.path.join(SKILLS_DIR, filename.strip())
    clean_content = content.strip()
    if not clean_content:
      continue

    # Create or append to skill file
    if os.path.isfile(target_path):
      try:
        with open(target_path, "r", encoding="utf-8") as f:
          existing = f.read()
        # Avoid duplicate appending
        if clean_content[:60] in existing:
          continue
        with open(target_path, "a", encoding="utf-8") as f:
          f.write(f"\n\n---\n\n## Expert Review Insights\n\n{clean_content}\n")
        updated_files.append(filename)
        print(f"  [SKILL_DOC] Updated skill file: {filename}", file=sys.stderr)
      except OSError as e:
        print(
            f"  [SKILL_DOC] Warning: Could not update {filename}: {e}",
            file=sys.stderr)
    else:
      try:
        title_str = (filename.replace(".md", "").replace("_", " ").title())
        with open(target_path, "w", encoding="utf-8") as f:
          f.write(f"# {title_str}\n\n{clean_content}\n")
        updated_files.append(filename)
        print(
            f"  [SKILL_DOC] Created new skill file: {filename}",
            file=sys.stderr)
      except OSError as e:
        print(
            f"  [SKILL_DOC] Warning: Could not create {filename}: {e}",
            file=sys.stderr)

  return updated_files


# pylint: disable=protected-access
def generate_skill_updates_from_review(
    engine_or_client: Any,
    review_text: str,
    expert_model: Optional[str] = None,
) -> str:
  """Prompts the expert model to synthesize explicit skill updates."""
  sys_inst = (
      "You are the Senior Principal Cobalt Systems Architect.\n"
      "Your task is to take the post-mortem comparative review and produce "
      "actionable atomic knowledge items and skill documentation updates.")
  prompt = (
      f"Here is the post-mortem review findings:\n\n{review_text[:15000]}\n\n"
      "Based on these findings, please produce:\n"
      "1. Extracted atomic lessons for our memory bank:\n"
      "```lesson\n"
      "TARGET: <filepath>\n"
      "ISSUE: <brief description of break>\n"
      "RULE: <actionable rule/technique for AI>\n"
      "```\n\n"
      "2. Explicit skill documentation additions to append to our skills "
      "(`cobalt_rebase.md`, `compiler_healing.md`, `gn_healing.md`):\n"
      "```skill_update: <skill_file.md>\n"
      "### <Section Title>\n"
      "<detailed markdown guidance to append to the skill file>\n"
      "```\n")
  if hasattr(engine_or_client, "_generate_expert_content"):
    return engine_or_client._generate_expert_content(
        prompt, sys_inst, expert_model=expert_model) or ""
  if hasattr(engine_or_client, "query"):
    res = engine_or_client.query(
        action="chat",
        message=f"{sys_inst}\n\n{prompt}",
        expert_model=expert_model,
        use_pro=True,
    )
    return res.get("response", "") if isinstance(res, dict) else str(res)
  return ""


def persist_lessons_to_memory(review_text: str, engine_or_client: Any) -> int:
  """Extracts ```lesson blocks and records them to GCS Knowledge Bank."""
  lesson_blocks = re.findall(r"```lesson\s*(.*?)\s*```", review_text, re.DOTALL)
  saved = 0

  for block in lesson_blocks:
    lines = block.strip().splitlines()
    target = ""
    issue = ""
    rule = ""
    for l in lines:
      if l.startswith("TARGET:"):
        target = l.replace("TARGET:", "").strip()
      elif l.startswith("ISSUE:"):
        issue = l.replace("ISSUE:", "").strip()
      elif l.startswith("RULE:"):
        rule = l.replace("RULE:", "").strip()

    if target and (issue or rule):
      desc = f"[{target}] {issue} -> {rule}"
      print(
          f"  [KNOWLEDGE_BANK] Persisting lesson for: {target}...",
          file=sys.stderr)
      if hasattr(engine_or_client, "record_successful_fix"):
        engine_or_client.record_successful_fix(
            issue_description=desc,
            solution_diff=rule,
            target_file=target,
        )
      else:
        engine_or_client.query(
            action="record_successful_fix",
            issue_description=desc,
            solution_diff=rule,
            target_file=target,
        )
      saved += 1

  return saved


def main():
  """Main entry point for review pipeline."""
  parser = argparse.ArgumentParser(
      description="Compare Human vs AI Rebase PR and Update Skills")
  parser.add_argument(
      "--human-pr",
      required=True,
      help="Human/Bot Roll PR (e.g. 12161 or PR URL)",
  )
  parser.add_argument(
      "--ai-pr",
      required=True,
      help="AI Rebase PR (e.g. 12176 or PR URL)",
  )
  parser.add_argument(
      "--local",
      action="store_true",
      help="Run Reasoning Engine locally in-process",
  )
  parser.add_argument(
      "--remote",
      "--resource-id",
      dest="resource_id",
      default=os.environ.get("REASONING_ENGINE_ID", ""),
      help="Hosted Vertex AI Reasoning Engine Resource ID",
  )
  parser.add_argument(
      "--project-id",
      default=os.environ.get("GCP_PROJECT") or "lxn-test",
      help="GCP Project ID",
  )
  parser.add_argument(
      "--location",
      default=os.environ.get("GCP_LOCATION", "us-central1"),
      help="Vertex AI Location",
  )
  parser.add_argument(
      "--expert-model",
      default=os.environ.get("EXPERT_MODEL", "claude-sonnet-5"),
      help=("Expert LLM model (default: claude-sonnet-5; supports "
            "gemini-3.7-flash, gemini-2.5-pro, glm-5.2, claude-opus-5)"),
  )
  parser.add_argument(
      "--expert-location",
      default=os.environ.get("EXPERT_LOCATION", "global"),
      help="Vertex AI region for Expert model (default: global)",
  )
  parser.add_argument(
      "--update-skills",
      action="store_true",
      help="Automatically update skill docs with extracted lessons",
  )
  parser.add_argument(
      "--gcs-memory-uri",
      default=os.environ.get("GCS_MEMORY_URI",
                             "gs://lxn-test/rebase_memory/knowledge_bank.json"),
      help="GCS URI for knowledge memory bank",
  )
  parser.add_argument(
      "--out",
      default="",
      help="Optional path to save markdown review report",
  )
  args = parser.parse_args()

  repo_root = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

  h_num = extract_pr_number(args.human_pr)
  a_num = extract_pr_number(args.ai_pr)

  print(f"[PIPELINE] Fetching Human PR #{h_num} data...", file=sys.stderr)
  h_data = fetch_pr_info(h_num)
  if not h_data:
    sys.exit(1)

  print(f"[PIPELINE] Fetching AI PR #{a_num} data...", file=sys.stderr)
  a_data = fetch_pr_info(a_num)
  if not a_data:
    sys.exit(1)

  # Partition commits in Human PR:
  # First 5 commits = roller baseline; remaining commits = human fix
  h_commits = h_data.get("commits", [])
  h_infra, h_fixes = partition_roll_commits(h_commits)
  print(
      f"[PIPELINE] Human PR #{h_num}: {len(h_infra)} roller baseline commits, "
      f"{len(h_fixes)} human fix commits.",
      file=sys.stderr,
  )

  # Diff of the human fix is from 5th commit (conflicted roll) to last commit
  base_sha = h_infra[-1].get("oid", "") if h_infra else None
  human_diff = get_diff_for_commits(h_fixes, repo_root, base_sha=base_sha)
  if not human_diff:
    _, human_diff, _ = run_cmd(["gh", "pr", "diff", h_num])

  # AI PR diff: partition roller commits if present
  a_commits = a_data.get("commits", [])
  a_infra, a_fixes = partition_roll_commits(a_commits)
  if a_infra and a_fixes:
    print(
        f"[PIPELINE] AI PR #{a_num}: {len(a_infra)} roller baseline commits, "
        f"{len(a_fixes)} AI fix commits.",
        file=sys.stderr,
    )
    a_base_sha = a_infra[-1].get("oid", "")
    ai_diff = get_diff_for_commits(a_fixes, repo_root, base_sha=a_base_sha)
  else:
    ai_diff = get_diff_for_commits(a_commits, repo_root)
  if not ai_diff:
    _, ai_diff, _ = run_cmd(["gh", "pr", "diff", a_num])

  # Analyze modified file sets
  human_files = extract_modified_files_from_diff(human_diff)
  ai_files = extract_modified_files_from_diff(ai_diff)

  both_files = sorted(list(human_files & ai_files))
  human_only_files = sorted(list(human_files - ai_files))
  ai_only_files = sorted(list(ai_files - human_files))

  # Calculate quantitative scoring metrics
  metrics = calculate_ai_pr_metrics(human_files, ai_files, human_diff, ai_diff)
  metrics_markdown = format_metrics_markdown(metrics)

  ovr = metrics["overall_similarity"]
  fj = metrics["file_jaccard"]
  sfc = metrics["shared_files_count"]
  hofc = metrics["human_only_files_count"]
  aofc = metrics["ai_only_files_count"]
  cj = metrics["code_jaccard"]
  sclc = metrics["shared_code_lines_count"]
  hoclc = metrics["human_only_code_lines_count"]
  aoclc = metrics["ai_only_code_lines_count"]

  print(
      f"[PIPELINE] Jaccard Similarity & Divergence Scorecard:\n"
      f"  - Overall Rebase Alignment : {ovr}%\n"
      f"  - Modified Files Overlap    : {fj}% "
      f"({sfc} shared, {hofc} missed by AI, {aofc} extra by AI)\n"
      f"  - Functional Code Lines     : {cj}% "
      f"({sclc} matching lines, {hoclc} missed, {aoclc} divergent)",
      file=sys.stderr,
  )

  if args.local or not args.resource_id:
    print(
        "[PIPELINE] Running CobaltReasoningEngine in Local Mode...",
        file=sys.stderr,
    )
    engine = CobaltReasoningEngine(
        project_id=args.project_id,
        location=args.location,
        expert_model=args.expert_model,
        expert_location=args.expert_location,
        gcs_memory_uri=args.gcs_memory_uri,
    )
  else:
    print(
        f"[PIPELINE] Connecting to Remote Reasoning Engine: "
        f"{args.resource_id}...",
        file=sys.stderr,
    )
    engine = ReasoningEngineClient(
        resource_id=args.resource_id,
        project_id=args.project_id,
        location=args.location,
    )

  review_report = generate_comparative_review(
      engine_or_client=engine,
      human_pr_data=h_data,
      ai_pr_data=a_data,
      human_diff=human_diff,
      ai_diff=ai_diff,
      both_files=both_files,
      human_only_files=human_only_files,
      ai_only_files=ai_only_files,
      repo_root=repo_root,
      expert_model=args.expert_model,
  )

  # Prepend the scorecard to the review report
  full_report = f"{metrics_markdown}\n---\n\n{review_report}"

  print("\n" + "=" * 80)
  print(full_report)
  print("=" * 80 + "\n")

  # Persist lessons to memory
  saved = persist_lessons_to_memory(review_report, engine)

  # Apply skill updates if requested
  if args.update_skills:
    updated_docs = apply_skill_updates(review_report)
    if not updated_docs:
      print(
          "[PIPELINE] Synthesizing explicit skill updates and lessons...",
          file=sys.stderr,
      )
      skill_content = generate_skill_updates_from_review(
          engine, review_report, expert_model=args.expert_model)
      if skill_content:
        saved += persist_lessons_to_memory(skill_content, engine)
        updated_docs = apply_skill_updates(skill_content)
        review_report += (
            f"\n\n---\n\n## 4. Synthesized Skill Updates & Knowledge Items\n\n"
            f"{skill_content}")
        full_report = f"{metrics_markdown}\n---\n\n{review_report}"

    doc_str = ", ".join(updated_docs) if updated_docs else "None"
    print(
        f"[PIPELINE] Saved {saved} new knowledge items to GCS Knowledge Bank.",
        file=sys.stderr,
    )
    print(
        f"[PIPELINE] Updated {len(updated_docs)} skill documents: {doc_str}",
        file=sys.stderr,
    )

  if args.out:
    try:
      with open(args.out, "w", encoding="utf-8") as f:
        f.write(full_report)
      print(f"[PIPELINE] Saved review report to: {args.out}", file=sys.stderr)
    except OSError as e:
      print(
          f"[ERROR] Could not write report to {args.out}: {e}", file=sys.stderr)


if __name__ == "__main__":
  main()
