#!/usr/bin/env python3
"""Automated Comparative Review & Skill Learning Pipeline.

Compares Human Ground-Truth PR fixes against AI Rebase attempts.
Uses the Tier-2 Expert Model (Claude Sonnet 4.6) to:
1. Identify key differences between Human and AI approaches.
2. Analyze why AI diverged (missed upstream shifts, unnecessary edits, etc.).
3. Generate or update Skill documentation (.github/rebase/reasoning_engine/skills/*.md).
4. Persist structured lessons to the GCS Knowledge Bank.

Convention:
  In Cobalt autoroll PRs, the first 5 commits are generated by the roller to
  bring the upstream Chromium code. All subsequent commits (from commit 6 onwards)
  are the fix commits.

Usage:
  python3 .github/rebase/review_pipeline.py \
    --human-pr 12161 \
    --ai-pr 12176 \
    --update-skills
"""

import argparse
import json
import os
import re
import subprocess
import sys
from typing import Any, Dict, List, Optional, Set, Tuple

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(SCRIPT_DIR)
if SCRIPT_DIR not in sys.path:
  sys.path.insert(0, SCRIPT_DIR)
if PARENT_DIR not in sys.path:
  sys.path.insert(0, PARENT_DIR)

# pylint: disable=wrong-import-position
from base_resolver import execute_local_tool
from engine_client import ReasoningEngineClient
from reasoning_engine.engine import CobaltReasoningEngine

SKILLS_DIR = os.path.join(SCRIPT_DIR, "reasoning_engine", "skills")


def run_cmd(cmd: List[str], cwd: Optional[str] = None) -> Tuple[bool, str, str]:
  """Runs a shell command and returns (success, stdout, stderr)."""
  try:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=90,
        check=False,
    )
    return proc.returncode == 0, proc.stdout.strip(), proc.stderr.strip()
  except Exception as e:  # pylint: disable=broad-exception-caught
    return False, "", str(e)


def extract_pr_number(pr_input: str) -> str:
  """Extracts numeric PR ID from number or GitHub PR URL."""
  m = re.search(r"/pull/(\d+)", pr_input)
  if m:
    return m.group(1)
  clean = pr_input.strip().lstrip("#")
  if clean.isdigit():
    return clean
  return pr_input


def fetch_pr_info(pr_num: str) -> Optional[Dict[str, Any]]:
  """Fetches PR metadata, commits, and files via gh CLI."""
  ok, out, err = run_cmd([
      "gh", "pr", "view", pr_num, "--json",
      "number,title,body,commits,files,baseRefName,headRefName"
  ])
  if not ok:
    print(f"[ERROR] Failed to fetch PR #{pr_num}: {err}", file=sys.stderr)
    return None
  try:
    return json.loads(out)
  except json.JSONDecodeError:
    return None


def partition_roll_commits(
    commits: List[Dict[str, Any]]
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
  """Partitions roll PR commits.

  The first 5 commits are generated by the roller to bring Chromium code;
  all subsequent commits are the fix commits.
  """
  if len(commits) > 5:
    return commits[:5], commits[5:]
  return [], commits


def get_diff_for_commits(commits: List[Dict[str, Any]],
                         repo_root: str,
                         base_sha: Optional[str] = None) -> str:
  """Calculates git diff across a list of commits or from base_sha to last commit."""
  if not commits:
    return ""

  first_sha = base_sha or commits[0].get("oid", "")
  last_sha = commits[-1].get("oid", "")

  if first_sha and last_sha:
    diff_range = f"{first_sha}..{last_sha}" if base_sha else f"{first_sha}^..{last_sha}"
    ok, out, _ = run_cmd(["git", "diff", diff_range], cwd=repo_root)
    if ok and out:
      return out

  # Fallback: git show individual commits
  diff_chunks = []
  for c in commits:
    sha = c.get("oid", "")
    headline = c.get("messageHeadline", "")
    ok, out, _ = run_cmd(["git", "show", "--stat", "-p", sha], cwd=repo_root)
    if ok and out:
      diff_chunks.append(f"Commit: {sha} ({headline})\n{out}")

  return "\n\n".join(diff_chunks)


def extract_modified_files_from_diff(diff_text: str) -> Set[str]:
  """Extracts list of modified file paths from unified diff."""
  files = set()
  for line in diff_text.splitlines():
    if line.startswith("+++ b/"):
      files.add(line[6:].strip())
  return files


def generate_comparative_review(
    engine_or_client: Any,
    human_pr_data: Dict[str, Any],
    ai_pr_data: Dict[str, Any],
    human_diff: str,
    ai_diff: str,
    both_files: List[str],
    human_only_files: List[str],
    ai_only_files: List[str],
    repo_root: str = "",
    expert_model: Optional[str] = None,
) -> str:
  """Uses Tier-2 Expert Agent to perform deep comparative review and update skills."""
  h_num = human_pr_data.get("number", "")
  h_title = human_pr_data.get("title", "")
  a_num = ai_pr_data.get("number", "")
  a_title = ai_pr_data.get("title", "")

  both_summary = "\n".join(f"- {f}" for f in both_files[:30]) or "None"
  human_only_summary = "\n".join(
      f"- {f}" for f in human_only_files[:30]) or "None"
  ai_only_summary = "\n".join(f"- {f}" for f in ai_only_files[:30]) or "None"

  sys_inst = (
      "You are the Senior Principal Chromium and Cobalt Systems Architect.\n"
      "Your mission is to perform a rigorous post-mortem review comparing a Human "
      "Expert (Igalia/Google) rebase fix vs. an AI Rebase attempt.\n\n"
      "Context:\n"
      "- In the Human PR, the first 5 commits were the automated Chromium roll baseline, "
      "and the subsequent commits were the human fixes.\n\n"
      "Objectives:\n"
      "1. Identify the core upstream Chromium architectural changes in this roll.\n"
      "2. Perform a file-by-file comparative divergence analysis:\n"
      "   - Why did the human edit files that AI missed?\n"
      "   - Why did AI edit files that human did not touch (e.g. unnecessary workarounds vs. deleting dead code)?\n"
      "   - Where both edited the same file, evaluate differences in approach (macro preservation, cleaner API translations, style).\n"
      "3. Synthesize actionable Knowledge Items (lessons) for our memory bank.\n"
      "4. Generate explicit skill doc update sections for our skill guides (`compiler_healing.md`, `gn_healing.md`, `cobalt_rebase.md`).\n\n"
      "Required Output Structure:\n"
      "# Post-Mortem Comparative Review: Human (PR #{h_num}) vs. AI (PR #{a_num})\n\n"
      "## 1. Executive Summary & Upstream Evolution\n"
      "## 2. Key Differences in Resolution Approach\n"
      "### A. Divergences in Shared Files (Human vs. AI)\n"
      "### B. Files Modified Only by Human (Missed by AI)\n"
      "### C. Files Modified Only by AI (Unnecessary/Suboptimal Edits)\n"
      "## 3. Extracted Rebase Rules & Knowledge Items\n"
      "Format each atomic lesson as:\n"
      "```lesson\n"
      "TARGET: <filepath>\n"
      "ISSUE: <brief description of break>\n"
      "RULE: <actionable rule/technique for AI>\n"
      "```\n\n"
      "## 4. Skill Document Updates\n"
      "Format proposed skill additions as:\n"
      "```skill_update: <skill_file.md>\n"
      "### <Section Title>\n"
      "<detailed markdown guidance to append to the skill file>\n"
      "```")

  prompt = (
      f"Human Ground-Truth PR: #{h_num} - {h_title}\n"
      f"AI Rebase Attempt PR: #{a_num} - {a_title}\n\n"
      f"=== File Overlap Breakdown ===\n"
      f"Files Modified by Both ({len(both_files)}):\n{both_summary}\n\n"
      f"Files Modified by Human Only ({len(human_only_files)}):\n{human_only_summary}\n\n"
      f"Files Modified by AI Only ({len(ai_only_files)}):\n{ai_only_summary}\n\n"
      f"=== AI Rebase Diff (Excerpt) ===\n{ai_diff[:24576]}\n\n"
      f"=== Human Ground-Truth Fix Diff (Excerpt) ===\n{human_diff[:32768]}\n\n"
      "Please perform your comprehensive comparative architectural review, extract knowledge items, and generate skill doc updates."
  )

  print(
      f"  [REVIEW] Consulting Tier-2 Expert Agent ({expert_model or 'Default'})...",
      file=sys.stderr)
  current_prompt = prompt
  accumulated_tool_context = []

  for round_idx in range(1, 5):
    if hasattr(engine_or_client, "_generate_expert_content"):
      response = engine_or_client._generate_expert_content(
          current_prompt, sys_inst, expert_model=expert_model)
    elif hasattr(engine_or_client, "generate_expert_guidance"):
      res = engine_or_client.generate_expert_guidance(
          target=f"PR_{h_num}_vs_PR_{a_num}",
          diagnostics=f"Review Human PR #{h_num} vs AI PR #{a_num}",
          source_contexts=human_diff[:16384],
          trajectory_history=f"Shared Files:\n{both_summary}",
          working_diff=ai_diff[:8192],
          expert_model=expert_model,
      )
      response = res.get("guidance", "")
    else:
      res = engine_or_client.query(
          action="chat",
          message=f"{sys_inst}\n\n{current_prompt}",
          use_pro=True,
      )
      response = res.get("response", "") if isinstance(res, dict) else str(res)

    if not response:
      break

    tool_match = re.search(r"^(TOOL_[A-Z_]+:.*)$", response.strip(),
                           re.MULTILINE)
    if not tool_match:
      return response

    tool_cmd = tool_match.group(1).strip()
    print(
        f"  [REVIEW] [Tool Round {round_idx}] Expert requested: {tool_cmd}",
        file=sys.stderr)
    tool_output = execute_local_tool(tool_cmd, repo_root)
    accumulated_tool_context.append(
        f"Tool `{tool_cmd}` output:\n```\n{tool_output}\n```")

    current_prompt = (
        f"{prompt}\n\n"
        f"--- Multi-Turn Investigation Tool Results ---\n"
        f"{chr(10).join(accumulated_tool_context)}\n\n"
        "Now proceed with your full post-mortem review, knowledge extraction, and skill updates."
    )

  return response or ""


def apply_skill_updates(review_text: str) -> List[str]:
  """Appends skill update blocks to files in reasoning_engine/skills/."""
  updates = re.findall(r"```skill_update:\s*([a-zA-Z0-9_\-\.]+)\n(.*?)```",
                       review_text, re.DOTALL)
  updated_files = []

  for filename, content in updates:
    target_path = os.path.join(SKILLS_DIR, filename.strip())
    clean_content = content.strip()
    if not clean_content:
      continue

    # Create or append to skill file
    if os.path.isfile(target_path):
      try:
        with open(target_path, "r", encoding="utf-8") as f:
          existing = f.read()
        # Avoid duplicate appending
        if clean_content[:60] in existing:
          continue
        with open(target_path, "a", encoding="utf-8") as f:
          f.write(f"\n\n---\n\n## Expert Review Insights\n\n{clean_content}\n")
        updated_files.append(filename)
        print(f"  [SKILL_DOC] Updated skill file: {filename}", file=sys.stderr)
      except OSError as e:
        print(
            f"  [SKILL_DOC] Warning: Could not update {filename}: {e}",
            file=sys.stderr)
    else:
      try:
        with open(target_path, "w", encoding="utf-8") as f:
          f.write(
              f"# {filename.replace('.md', '').replace('_', ' ').title()}\n\n{clean_content}\n"
          )
        updated_files.append(filename)
        print(
            f"  [SKILL_DOC] Created new skill file: {filename}",
            file=sys.stderr)
      except OSError as e:
        print(
            f"  [SKILL_DOC] Warning: Could not create {filename}: {e}",
            file=sys.stderr)

  return updated_files


def persist_lessons_to_memory(review_text: str, engine_or_client: Any) -> int:
  """Extracts ```lesson blocks and records them to GCS Knowledge Bank."""
  lesson_blocks = re.findall(r"```lesson\s*(.*?)\s*```", review_text, re.DOTALL)
  saved = 0

  for block in lesson_blocks:
    lines = block.strip().splitlines()
    target = ""
    issue = ""
    rule = ""
    for l in lines:
      if l.startswith("TARGET:"):
        target = l.replace("TARGET:", "").strip()
      elif l.startswith("ISSUE:"):
        issue = l.replace("ISSUE:", "").strip()
      elif l.startswith("RULE:"):
        rule = l.replace("RULE:", "").strip()

    if target and (issue or rule):
      desc = f"[{target}] {issue} -> {rule}"
      print(
          f"  [KNOWLEDGE_BANK] Persisting lesson for: {target}...",
          file=sys.stderr)
      if hasattr(engine_or_client, "record_successful_fix"):
        engine_or_client.record_successful_fix(
            issue_description=desc,
            solution_diff=rule,
            target_file=target,
        )
      else:
        engine_or_client.query(
            action="record_successful_fix",
            issue_description=desc,
            solution_diff=rule,
            target_file=target,
        )
      saved += 1

  return saved


def main():
  """Main entry point for review pipeline."""
  parser = argparse.ArgumentParser(
      description="Compare Human vs AI Rebase PR and Update Skills")
  parser.add_argument(
      "--human-pr",
      required=True,
      help="Human/Bot Roll PR (e.g. 12161 or https://github.com/youtube/cobalt/pull/12161)",
  )
  parser.add_argument(
      "--ai-pr",
      required=True,
      help="AI Rebase PR (e.g. 12176 or https://github.com/youtube/cobalt/pull/12176)",
  )
  parser.add_argument(
      "--remote",
      "--resource-id",
      dest="resource_id",
      default=os.environ.get("REASONING_ENGINE_ID", "6638241529313886208"),
      help="Hosted Vertex AI Reasoning Engine Resource ID (default: 6638241529313886208)",
  )
  parser.add_argument(
      "--project-id",
      default=os.environ.get("GCP_PROJECT") or "lxn-test",
      help="GCP Project ID",
  )
  parser.add_argument(
      "--location",
      default=os.environ.get("GCP_LOCATION", "us-central1"),
      help="Vertex AI Location",
  )
  parser.add_argument(
      "--expert-model",
      default=os.environ.get("EXPERT_MODEL", "claude-sonnet-5"),
      help=(
          "Expert LLM model (default: claude-sonnet-5; supports "
          "gemini-3.7-flash, gemini-2.5-pro, glm-5.2, claude-opus-5)"),
  )
  parser.add_argument(
      "--expert-location",
      default=os.environ.get("EXPERT_LOCATION", "global"),
      help="Vertex AI region for Expert model (default: global)",
  )
  parser.add_argument(
      "--update-skills",
      action="store_true",
      help="Automatically update skill docs in reasoning_engine/skills/ with lessons",
  )
  parser.add_argument(
      "--out",
      default="",
      help="Optional path to save markdown review report",
  )
  args = parser.parse_args()

  repo_root = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

  h_num = extract_pr_number(args.human_pr)
  a_num = extract_pr_number(args.ai_pr)

  print(f"[PIPELINE] Fetching Human PR #{h_num} data...", file=sys.stderr)
  h_data = fetch_pr_info(h_num)
  if not h_data:
    sys.exit(1)

  print(f"[PIPELINE] Fetching AI PR #{a_num} data...", file=sys.stderr)
  a_data = fetch_pr_info(a_num)
  if not a_data:
    sys.exit(1)

  # Partition commits in Human PR:
  # First 5 commits = roller baseline; remaining commits = human fix
  h_commits = h_data.get("commits", [])
  h_infra, h_fixes = partition_roll_commits(h_commits)
  print(
      f"[PIPELINE] Human PR #{h_num}: {len(h_infra)} roller baseline commits, "
      f"{len(h_fixes)} human fix commits.",
      file=sys.stderr,
  )

  # Diff of the human fix is from the 5th commit (conflicted roll) to the last commit
  base_sha = h_infra[-1].get("oid", "") if h_infra else None
  human_diff = get_diff_for_commits(h_fixes, repo_root, base_sha=base_sha)
  if not human_diff:
    ok, human_diff, _ = run_cmd(["gh", "pr", "diff", h_num])

  # AI PR diff: partition roller commits if present
  a_commits = a_data.get("commits", [])
  a_infra, a_fixes = partition_roll_commits(a_commits)
  if a_infra and a_fixes:
    print(
        f"[PIPELINE] AI PR #{a_num}: {len(a_infra)} roller baseline commits, "
        f"{len(a_fixes)} AI fix commits.",
        file=sys.stderr,
    )
    a_base_sha = a_infra[-1].get("oid", "")
    ai_diff = get_diff_for_commits(a_fixes, repo_root, base_sha=a_base_sha)
  else:
    ai_diff = get_diff_for_commits(a_commits, repo_root)
  if not ai_diff:
    ok, ai_diff, _ = run_cmd(["gh", "pr", "diff", a_num])

  # Analyze modified file sets
  human_files = extract_modified_files_from_diff(human_diff)
  ai_files = extract_modified_files_from_diff(ai_diff)

  both_files = sorted(list(human_files & ai_files))
  human_only_files = sorted(list(human_files - ai_files))
  ai_only_files = sorted(list(ai_files - human_files))

  print(
      f"[PIPELINE] Comparison Breakdown:\n"
      f"  - Files in Both: {len(both_files)}\n"
      f"  - Files Human Only: {len(human_only_files)}\n"
      f"  - Files AI Only: {len(ai_only_files)}",
      file=sys.stderr,
  )

  if args.resource_id:
    print(
        f"[PIPELINE] Connecting to Remote Reasoning Engine: {args.resource_id}...",
        file=sys.stderr)
    engine = ReasoningEngineClient(
        resource_id=args.resource_id,
        project_id=args.project_id,
        location=args.location,
    )
  else:
    engine = CobaltReasoningEngine(
        project_id=args.project_id,
        location=args.location,
        expert_model=args.expert_model,
        expert_location=args.expert_location,
    )

  review_report = generate_comparative_review(
      engine_or_client=engine,
      human_pr_data=h_data,
      ai_pr_data=a_data,
      human_diff=human_diff,
      ai_diff=ai_diff,
      both_files=both_files,
      human_only_files=human_only_files,
      ai_only_files=ai_only_files,
      repo_root=repo_root,
      expert_model=args.expert_model,
  )

  print("\n" + "=" * 80)
  print(review_report)
  print("=" * 80 + "\n")

  # Persist lessons to memory
  saved = persist_lessons_to_memory(review_report, engine)
  print(
      f"[PIPELINE] Saved {saved} new knowledge items to GCS Knowledge Bank.",
      file=sys.stderr)

  # Apply skill updates if requested
  if args.update_skills:
    updated_docs = apply_skill_updates(review_report)
    print(
        f"[PIPELINE] Updated {len(updated_docs)} skill documents: {', '.join(updated_docs)}",
        file=sys.stderr)

  if args.out:
    try:
      with open(args.out, "w", encoding="utf-8") as f:
        f.write(review_report)
      print(f"[PIPELINE] Saved review report to: {args.out}", file=sys.stderr)
    except OSError as e:
      print(
          f"[ERROR] Could not write report to {args.out}: {e}", file=sys.stderr)


if __name__ == "__main__":
  main()
