// Modified based on the file generated by build/write_buildflag_header.py from
// "//media/gpu:buildflags"

#ifndef MEDIA_GPU_BUILDFLAGS_H_
#define MEDIA_GPU_BUILDFLAGS_H_

#if !defined(STARBOARD)
#error "This file only works with Cobalt/Starboard."
#endif  // !defined(STARBOARD)

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_VAAPI() (0)
#define BUILDFLAG_INTERNAL_USE_VAAPI_IMAGE_CODECS() (0)
#define BUILDFLAG_INTERNAL_USE_V4L2_CODEC() (0)
#define BUILDFLAG_INTERNAL_USE_LIBV4L2() (0)
#define BUILDFLAG_INTERNAL_USE_VAAPI_X11() (0)

#endif  // MEDIA_GPU_BUILDFLAGS_H_
