// Copyright 2022 The Cobalt Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// https://w3c.github.io/ServiceWorker/#client-interface

[Exposed = ServiceWorker] interface Client {
  readonly attribute USVString url;
  readonly attribute FrameType frameType;
  readonly attribute DOMString id;
  readonly attribute ClientType type;
  void postMessage(any message);
  // TODO: Support sequence<object>: b/218501774
  // void postMessage(any message, sequence<object> transfer);
  // TODO: Support overloads with dictionary parameter: b/218506730
  // void postMessage(any message,
  //                 optional StructuredSerializeOptions options = {});

};
