name: Process Test Results
description: Uploads test results to DataDog.
inputs:
  datadog_api_key:
    description: "Path to directory where test results are saved."
    required: true
  test_results_key:
    description: "Artifact key used to store test results."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Test Results
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test_results_key }}
        path: results/

    - name: Publish Test Report
      continue-on-error: true
      uses: mikepenz/action-junit-report@992d97d6eb2e5f3de985fbf9df6a04386874114d
      with:
        report_paths: results/*.xml
        skip_annotations: true

    - name: Get Datadog CLI
      id: download-dd-cli
      # The API key is not available on PRs created from a fork.
      if: inputs.datadog_api_key != ''
      env:
        DD_VERSION: 'v2.18.0'
        DD_SHA256SUM: 'adbe9b3a41faaf0b1d9702ba256cf8fa9e474c0cc8216f25e5b489c53d6f0a70  datadog-ci'
      run: |
        set -x
        download_url="https://github.com/DataDog/datadog-ci/releases/download/${DD_VERSION}/datadog-ci_linux-x64"
        curl -L --fail ${download_url} --output datadog-ci
        echo ${DD_SHA256SUM} | sha256sum --check
        chmod +x datadog-ci
      shell: bash

    - name: Upload to Datadog
      if: steps.download-dd-cli.outcome == 'success'
      env:
        DATADOG_SITE: us5.datadoghq.com
        DATADOG_API_KEY: ${{ inputs.datadog_api_key }}
        DD_SERVICE: ${{ github.event.repository.name }}
        DD_TAGS: os.platform:${{ matrix.platform }}
        DD_ENV: ci
      run: |
        set -x
        ./datadog-ci junit upload --service ${DD_SERVICE} results/*.xml
      shell: bash
