// Generated by build/write_buildflag_header.py
// From "//base:debugging_buildflags"
//
// However for Cobalt we just hardcode the values of these #defines.

#ifndef BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_
#define BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_

#include "base/buildflag.h"
#include "starboard/configuration.h"

#define BUILDFLAG_INTERNAL_ENABLE_LOCATION_SOURCE() (1)
#define BUILDFLAG_INTERNAL_ENABLE_PROFILING() (0)
#if !defined(SB_IS_COMPILER_MSVC)
#define BUILDFLAG_INTERNAL_CAN_UNWIND_WITH_FRAME_POINTERS() (1)
#else
#define BUILDFLAG_INTERNAL_CAN_UNWIND_WITH_FRAME_POINTERS() (0)
#endif
#define BUILDFLAG_INTERNAL_UNSAFE_DEVELOPER_BUILD() (1)
#define BUILDFLAG_INTERNAL_CAN_UNWIND_WITH_CFI_TABLE() (0)

#endif  // BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_