caption: Sign-in settings
desc: Controls the behavior of the sign-in screen, where users log into their accounts.
  Settings include who can log in, what type of accounts are allowed, what authentication
  methods should be used, as well as general accessibility, input method and locale
  settings.
