/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef DOM_PARSER_HTML_DECODER_H_
#define DOM_PARSER_HTML_DECODER_H_

#include <string>

#include "base/callback.h"
#include "base/memory/ref_counted.h"
#include "base/memory/scoped_ptr.h"
#include "base/threading/thread_checker.h"
#include "cobalt/base/source_location.h"
#include "cobalt/dom/document.h"
#include "cobalt/dom/node.h"
#include "cobalt/loader/decoder.h"

namespace cobalt {
namespace dom_parser {

enum HTMLParserSeverity {
  kHTMLParserWarning,
  kHTMLParserError,
  kHTMLParserFatal,
  kHTMLParserSeverityCount,
};

// This decoder class is responsible for decoding a piece of HTML source code
// using libxml2 SAX parser, creating corresponding DOM nodes and inserting them
// at the given position.
class HTMLDecoder : public loader::Decoder {
 public:
  // This subclass is responsible for providing the handlers for the interface
  // of libxml's SAX parser. To convert void* context to this type in the
  // handler functions it is kept in the public section.
  class LibxmlWrapper;

  enum DOMType {
    kDocumentFull,
    kDocumentFragment,
  };

  // New nodes will be inserted under parent_node, before reference_node.
  // If dom_type is kDocumentFragment, it means the DOM presentation to be
  // decoded is a document fragment, which means implied <html>, <body> tags
  // generated by the libxml parser won't be appended to the parent.
  HTMLDecoder(const scoped_refptr<dom::Document>& document,
              const scoped_refptr<dom::Node>& parent_node,
              const scoped_refptr<dom::Node>& reference_node, DOMType dom_type,
              const base::SourceLocation& input_location,
              const base::Closure& done_callback,
              const base::Callback<void(const std::string&)>& error_callback);

  ~HTMLDecoder();

  // From Decoder.
  void DecodeChunk(const char* data, size_t size) OVERRIDE;
  void Finish() OVERRIDE;

 private:
  base::ThreadChecker thread_checker_;
  scoped_ptr<LibxmlWrapper> libxml_wrapper_;
  const base::Closure done_callback_;

  DISALLOW_COPY_AND_ASSIGN(HTMLDecoder);
};

}  // namespace dom_parser
}  // namespace cobalt

#endif  // DOM_PARSER_HTML_DECODER_H_
