// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BASE_I18N_TAGS_H_
#define BASE_I18N_TAGS_H_

#include "base/i18n/language_tag.h"
#include "base/i18n/tag_converters.h"

// This file provides access to compile-time validated, canonical `LanguageTag`
// constants for all supported locales in Chromium.
//
// These constants should be used whenever you need to refer to a specific
// supported language tag in a type-safe way, avoiding string literals.
//
// Usage:
//   const base::i18n::LanguageTag& en = base::i18n::language_tags::ENGLISH();
//   const base::i18n::LanguageTag& zh_cn =
//       base::i18n::language_tags::CHINESE_CHINA();
//
// The functions return a reference to a static `LanguageTag` instance.
//
// A base::i18n::GetKnownLanguageTag<>() function is also offered templated on a
// literal string for the language tag. Overloads are provided only for known
// tags (the same set of tags that the literal functions are built on).
//
// Usage:
//   const base::i18n::LanguageTag& en =
//       base::i18n::GetKnownLanguageTag<"en">();
//   const base::i18n::LanguageTag& zh_cn =
//       base::i18n::GetKnownLanguageTag<"zh-CN">();
//
// If the function is called with a unknown tag, the code does not compile.
// Notice that not being able to use GetKnownLanguageTag<> does not mean the tag
// is not valid.
//
// Compilation error example:
//   // The tag "en-BR" is valid, but it is not pre-defined in our list of known
//   // chromium tags.
//   const base::i18n::LanguageTag& en =
//       base::i18n::GetKnownLanguageTag<"en-BR">();
//
//
// The list of supported languages is generated by the action
// `canonical_language_tags_gen` and stored in
// `base/i18n/internal/canonical_language_tags.inc`.
namespace base::i18n {

namespace internal {
// A structural type that holds a string literal at compile time.
template <size_t N>
struct StringLiteral {
  constexpr StringLiteral(const char (&str)[N]) { std::copy_n(str, N, value); }
  char value[N];
};
}  // namespace internal

// Returns a LanguageTag checked at compile time. It only works for known tags
// (defined below).
// This is the default implementation that has a false static_assert to force
// compilation error if `GetKnownLanguageTag` is called with an unknown tag.
template <internal::StringLiteral s>
const LanguageTag& GetKnownLanguageTag() {
  // Default implementation forces compilation error so callers cannot call with
  // an unknown tag.
  static_assert(
      false, "Language tag is not pre-defined therefore cannot be used here.");
}

namespace language_tags {

// Returns a undefined language tag.
BASE_I18N_EXPORT const LanguageTag& UNDEFINED();

#define IMPL_LANGUAGECODE_TAG_NAME(tag, name) \
  BASE_I18N_EXPORT const LanguageTag& name();

#include "base/i18n/internal/canonical_language_tags.inc"
#undef IMPL_LANGUAGECODE_TAG_NAME

}  // namespace language_tags

template <>
inline const LanguageTag& GetKnownLanguageTag<"und">() {
  return language_tags::UNDEFINED();
}

#define IMPL_LANGUAGECODE_TAG_NAME(tag, name)            \
  template <>                                            \
  inline const LanguageTag& GetKnownLanguageTag<tag>() { \
    return language_tags::name();                        \
  }

#include "base/i18n/internal/canonical_language_tags.inc"
#undef IMPL_LANGUAGECODE_TAG_NAME

}  // namespace base::i18n

#endif  // BASE_I18N_TAGS_H_
