# Copyright 2016 Samsung Electronics. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{
  'targets': [
    {
      'target_name': 'starboard_platform',
      'type': 'static_library',
      'sources': [
        '<(DEPTH)/starboard/shared/dlmalloc/memory_allocate_aligned_unchecked.cc',
        '<(DEPTH)/starboard/shared/dlmalloc/memory_allocate_unchecked.cc',
        '<(DEPTH)/starboard/shared/dlmalloc/memory_free.cc',
        '<(DEPTH)/starboard/shared/dlmalloc/memory_free_aligned.cc',
        '<(DEPTH)/starboard/shared/dlmalloc/memory_map.cc',
        '<(DEPTH)/starboard/shared/dlmalloc/memory_reallocate_unchecked.cc',
        '<(DEPTH)/starboard/shared/dlmalloc/memory_unmap.cc',
        '<(DEPTH)/starboard/shared/starboard/media/codec_util.cc',
        '<(DEPTH)/starboard/shared/starboard/media/codec_util.h',
        '<(DEPTH)/starboard/shared/starboard/media/media_can_play_mime_and_key_system.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_get_audio_configuration_stereo_only.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_get_audio_output_count_stereo_only.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_is_audio_supported_aac_only.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_is_output_protected.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_is_video_supported_h264_1080p_sfr_only.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_set_output_protection.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_util.cc',
        '<(DEPTH)/starboard/shared/starboard/media/media_util.h',
        '<(DEPTH)/starboard/shared/starboard/media/mime_type.cc',
        '<(DEPTH)/starboard/shared/starboard/media/mime_type.h',
        '<(DEPTH)/starboard/shared/starboard/new.cc',
        '<(DEPTH)/starboard/shared/starboard/player/decoded_audio_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/decoded_audio_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_decoder_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_frame_tracker.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_frame_tracker.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_renderer_impl_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_renderer_impl_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_renderer_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_renderer_sink.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_renderer_sink_impl.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_renderer_sink_impl.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_resampler_impl.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_time_stretcher.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/audio_time_stretcher.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/decoded_audio_queue.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/decoded_audio_queue.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/filter_based_player_worker_handler.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/filter_based_player_worker_handler.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/player_components.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/video_decoder_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/video_renderer_impl_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/video_renderer_impl_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/video_renderer_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/filter/wsola_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/filter/wsola_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/input_buffer_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/input_buffer_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/job_queue.cc',
        '<(DEPTH)/starboard/shared/starboard/player/job_queue.h',
        '<(DEPTH)/starboard/shared/starboard/player/player_create.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_destroy.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_get_current_frame.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_get_info.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_output_mode_supported.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_internal.h',
        '<(DEPTH)/starboard/shared/starboard/player/player_seek.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_set_bounds.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_set_playback_rate.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_set_volume.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_worker.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_worker.h',
        '<(DEPTH)/starboard/shared/starboard/player/player_write_end_of_stream.cc',
        '<(DEPTH)/starboard/shared/starboard/player/player_write_sample.cc',
        '<(DEPTH)/starboard/shared/starboard/player/video_frame_internal.cc',
        '<(DEPTH)/starboard/shared/starboard/player/video_frame_internal.h',
        '<(DEPTH)/starboard/shared/stub/accessibility_get_display_settings.cc',
        '<(DEPTH)/starboard/shared/stub/accessibility_get_text_to_speech_settings.cc',
        '<(DEPTH)/starboard/shared/stub/cryptography_create_transformer.cc',
        '<(DEPTH)/starboard/shared/stub/cryptography_destroy_transformer.cc',
        '<(DEPTH)/starboard/shared/stub/cryptography_get_tag.cc',
        '<(DEPTH)/starboard/shared/stub/cryptography_set_authenticated_data.cc',
        '<(DEPTH)/starboard/shared/stub/cryptography_set_initialization_vector.cc',
        '<(DEPTH)/starboard/shared/stub/cryptography_transform.cc',
        '<(DEPTH)/starboard/shared/stub/decode_target_create_egl.cc',
        '<(DEPTH)/starboard/shared/stub/decode_target_get_info.cc',
        '<(DEPTH)/starboard/shared/stub/decode_target_release.cc',
        '<(DEPTH)/starboard/shared/stub/drm_close_session.cc',
        '<(DEPTH)/starboard/shared/stub/drm_create_system.cc',
        '<(DEPTH)/starboard/shared/stub/drm_destroy_system.cc',
        '<(DEPTH)/starboard/shared/stub/drm_generate_session_update_request.cc',
        '<(DEPTH)/starboard/shared/stub/drm_system_internal.h',
        '<(DEPTH)/starboard/shared/stub/drm_update_session.cc',
        '<(DEPTH)/starboard/shared/stub/image_decode.cc',
        '<(DEPTH)/starboard/shared/stub/image_is_decode_supported.cc',
        '<(DEPTH)/starboard/shared/stub/media_is_supported.cc',
        '<(DEPTH)/starboard/shared/stub/media_is_transfer_characteristics_supported.cc',
        '<(DEPTH)/starboard/shared/wayland/application_wayland.cc',
        '<(DEPTH)/starboard/contrib/tizen/shared/ffmpeg/ffmpeg_audio_decoder.cc',
        '<(DEPTH)/starboard/contrib/tizen/shared/ffmpeg/ffmpeg_audio_decoder.h',
        '<(DEPTH)/starboard/contrib/tizen/shared/ffmpeg/ffmpeg_common.cc',
        '<(DEPTH)/starboard/contrib/tizen/shared/ffmpeg/ffmpeg_common.h',
        '<(DEPTH)/starboard/contrib/tizen/shared/ffmpeg/ffmpeg_video_decoder.cc',
        '<(DEPTH)/starboard/contrib/tizen/shared/ffmpeg/ffmpeg_video_decoder.h',
        '<(DEPTH)/starboard/contrib/tizen/shared/main.cc',
        '<(DEPTH)/starboard/contrib/tizen/shared/player/filter/ffmpeg_player_components_impl.cc',
        '<(DEPTH)/starboard/contrib/tizen/shared/system_get_path.cc',
        'atomic_public.h',
        'configuration_public.h',
        'system_get_property.cc',
      ],
      'defines': [
        # This must be defined when building Starboard, and must not when
        # building Starboard client code.
        'STARBOARD_IMPLEMENTATION',
      ],
      'dependencies': [
        '<(DEPTH)/starboard/common/common.gyp:common',
        '<(DEPTH)/starboard/contrib/tizen/shared/system.gyp:aul',
        '<(DEPTH)/starboard/contrib/tizen/shared/system.gyp:elementary',
        '<(DEPTH)/third_party/dlmalloc/dlmalloc.gyp:dlmalloc',
        'starboard_common.gyp:starboard_common',
      ],
    },
  ],
}
