# Use the official Ubuntu image as the base
FROM debian:12

# Install any necessary dependencies
RUN apt-get update && apt-get install -y \
    # curl \
   #  python3-dev \
    # xz-utils \
  #  pkgconf \
   # libglib2.0-0 \
   # gperf \
   # gcc-multilib \
    bzip2 \
   # python3-certifi \
   libasound2 \
   libdbus-1-3 \
   libgbm-dev \
   libnss3 \
   libxcomposite-dev \
   #
    xauth \
    xvfb \
    jq \
    && rm -rf /var/lib/apt/lists/*
