// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef STARBOARD_CONFIGURATION_H_
#define STARBOARD_CONFIGURATION_H_

#if !defined(STARBOARD)
#  error "You must define STARBOARD in Starboard builds."
#endif

// The maximum API version allowed by this version of the Starboard headers,
// inclusive.
#define SB_MAXIMUM_API_VERSION 1

// The minimum API version allowed by this version of the Starboard headers,
// inclusive.
#define SB_MINIMUM_API_VERSION 1

// Determines a compile-time capability of the system.
#define SB_CAN(SB_FEATURE) (defined(SB_CAN_##SB_FEATURE) && SB_CAN_##SB_FEATURE)

// Determines at compile-time whether this platform has a standard feature or
// header available.
#define SB_HAS(SB_FEATURE) (defined(SB_HAS_##SB_FEATURE) && SB_HAS_##SB_FEATURE)

// Determines at compile-time an aspect of this platform.
#define SB_IS(SB_FEATURE) (defined(SB_IS_##SB_FEATURE) && SB_IS_##SB_FEATURE)

// Determines at compile-time if this platform implements a given version number
// or above.
#define SB_VER(SB_VERSION) (STARBOARD_API_VERSION >= SB_VERSION)

// Include the platform specific configuration. This definition is generated by
// GYP in starboard_base_target.gypi and passed in on the command line for all
// targets and all configurations.
#include STARBOARD_CONFIGURATION_INCLUDE

// Audit the platform-specific configuration.

#if !defined(STARBOARD_API_VERSION)
#  error "STARBOARD_API_VERSION was not defined by your platform."
#endif

#if STARBOARD_API_VERSION > SB_MAXIMUM_API_VERSION
#  error "Your platform's STARBOARD_API_VERSION > SB_MAXIMUM_API_VERSION."
#endif

#if STARBOARD_API_VERSION < SB_MINIMUM_API_VERSION
#  error "Your platform's STARBOARD_API_VERSION < SB_MINIMUM_API_VERSION."
#endif

// Whether the current platform is little endian.
#define SB_IS_LITTLE_ENDIAN (!SB_IS(BIG_ENDIAN))

#endif  // STARBOARD_CONFIGURATION_H_
