name: GN
description: Generates and checks GN.
inputs:
  name:
    required: false
runs:
  using: "composite"
  steps:
    - name: Configure Environment
      shell: bash
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Set up Cloud SDK
      if: startsWith(${{matrix.target_platform}}, 'android')
      uses: google-github-actions/setup-gcloud@v1
    - name: Configure Android Environment
      shell: bash
      if: startsWith(${{matrix.target_platform}}, 'android')
      run: |
        echo "ANDROID_HOME=/root/starboard-toolchains/AndroidSdk/" >> $GITHUB_ENV
        echo "COBALT_GRADLE_BUILD_COUNT=24" >> $GITHUB_ENV
        PROJECT_NAME=$(gcloud config get-value project)
        echo "GCS_NIGHTLY_PATH=gs://${PROJECT_NAME}-build-artifacts" >> $GITHUB_ENV
    - name: GN
      run: |
        set -x
        if [ -z ${COBALT_EVERGREEN_LOADER+x} ]; then
          BUILD_PLATFORM=${{ matrix.target_platform }}
          EXTRA_GN_ARGUMENTS=${{ matrix.extra_gn_arguments }}
        else
          BUILD_PLATFORM=${COBALT_EVERGREEN_LOADER}
          EXTRA_GN_ARGUMENTS=${{ matrix.extra_evergreen_loader_gn_arguments }}
        fi
        gn gen $GITHUB_WORKSPACE/out/${BUILD_PLATFORM}_${{matrix.config}} --args="target_platform=\"${BUILD_PLATFORM}\" ${{matrix.sb_api_version}} ${{matrix.target_os}} ${{matrix.target_cpu}} ${EXTRA_GN_ARGUMENTS} is_internal_build=false build_type=\"${{matrix.config}}\""
        gn check $GITHUB_WORKSPACE/out/${BUILD_PLATFORM}_${{ matrix.config }}
      shell: bash
