// This file was GENERATED by command:
//     pump.py jsc_callback_function.h.pump
// DO NOT EDIT BY HAND!!!


/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SCRIPT_JAVASCRIPTCORE_JSC_CALLBACK_FUNCTION_H_
#define SCRIPT_JAVASCRIPTCORE_JSC_CALLBACK_FUNCTION_H_

#include "cobalt/script/callback_function.h"
#include "cobalt/script/javascriptcore/jsc_object_owner.h"

// The JSCCallbackFunction type is used to represent IDL callback functions.
// Create a new JSCCallbackFunction by specifying the base CallbackFunction
// as a template parameter to the constructor.
//
// Constructor parameters:
//     callable: A handle that keeps keeps alive the JSC::JSFunction that
//         will be called when the callback is fired.
//     callback: A base::Callback that will be executed when the Run(...)
//         function is executed. It will take as parameters the object_owner
//         followed by any arguments that are defined on the callback type.

namespace cobalt {
namespace script {
namespace javascriptcore {

// First, we forward declare the Callback class template. This informs the
// compiler that the template only has 1 type parameter which is the base
// CallbackFunction template class with parameters.
//
// See base/callback.h.pump for further discussion on this pattern.
template <typename Sig>
class JSCCallbackFunction;

template <typename R>
class JSCCallbackFunction<R(void)>
    : public CallbackFunction<R(void)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run()
      const OVERRIDE {
    callback_.Run(callable_);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1>
class JSCCallbackFunction<R(A1)>
    : public CallbackFunction<R(A1)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1)
      const OVERRIDE {
    callback_.Run(callable_, a1);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1, typename A2>
class JSCCallbackFunction<R(A1, A2)>
    : public CallbackFunction<R(A1, A2)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType,
      typename base::internal::CallbackParamTraits<A2>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1,
      typename base::internal::CallbackParamTraits<A2>::ForwardType a2)
      const OVERRIDE {
    callback_.Run(callable_, a1, a2);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1, typename A2, typename A3>
class JSCCallbackFunction<R(A1, A2, A3)>
    : public CallbackFunction<R(A1, A2, A3)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType,
      typename base::internal::CallbackParamTraits<A2>::ForwardType,
      typename base::internal::CallbackParamTraits<A3>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1,
      typename base::internal::CallbackParamTraits<A2>::ForwardType a2,
      typename base::internal::CallbackParamTraits<A3>::ForwardType a3)
      const OVERRIDE {
    callback_.Run(callable_, a1, a2, a3);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1, typename A2, typename A3, typename A4>
class JSCCallbackFunction<R(A1, A2, A3, A4)>
    : public CallbackFunction<R(A1, A2, A3, A4)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType,
      typename base::internal::CallbackParamTraits<A2>::ForwardType,
      typename base::internal::CallbackParamTraits<A3>::ForwardType,
      typename base::internal::CallbackParamTraits<A4>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1,
      typename base::internal::CallbackParamTraits<A2>::ForwardType a2,
      typename base::internal::CallbackParamTraits<A3>::ForwardType a3,
      typename base::internal::CallbackParamTraits<A4>::ForwardType a4)
      const OVERRIDE {
    callback_.Run(callable_, a1, a2, a3, a4);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1, typename A2, typename A3, typename A4,
    typename A5>
class JSCCallbackFunction<R(A1, A2, A3, A4, A5)>
    : public CallbackFunction<R(A1, A2, A3, A4, A5)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType,
      typename base::internal::CallbackParamTraits<A2>::ForwardType,
      typename base::internal::CallbackParamTraits<A3>::ForwardType,
      typename base::internal::CallbackParamTraits<A4>::ForwardType,
      typename base::internal::CallbackParamTraits<A5>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1,
      typename base::internal::CallbackParamTraits<A2>::ForwardType a2,
      typename base::internal::CallbackParamTraits<A3>::ForwardType a3,
      typename base::internal::CallbackParamTraits<A4>::ForwardType a4,
      typename base::internal::CallbackParamTraits<A5>::ForwardType a5)
      const OVERRIDE {
    callback_.Run(callable_, a1, a2, a3, a4, a5);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6>
class JSCCallbackFunction<R(A1, A2, A3, A4, A5, A6)>
    : public CallbackFunction<R(A1, A2, A3, A4, A5, A6)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType,
      typename base::internal::CallbackParamTraits<A2>::ForwardType,
      typename base::internal::CallbackParamTraits<A3>::ForwardType,
      typename base::internal::CallbackParamTraits<A4>::ForwardType,
      typename base::internal::CallbackParamTraits<A5>::ForwardType,
      typename base::internal::CallbackParamTraits<A6>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1,
      typename base::internal::CallbackParamTraits<A2>::ForwardType a2,
      typename base::internal::CallbackParamTraits<A3>::ForwardType a3,
      typename base::internal::CallbackParamTraits<A4>::ForwardType a4,
      typename base::internal::CallbackParamTraits<A5>::ForwardType a5,
      typename base::internal::CallbackParamTraits<A6>::ForwardType a6)
      const OVERRIDE {
    callback_.Run(callable_, a1, a2, a3, a4, a5, a6);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

template <typename R, typename A1, typename A2, typename A3, typename A4,
    typename A5, typename A6, typename A7>
class JSCCallbackFunction<R(A1, A2, A3, A4, A5, A6, A7)>
    : public CallbackFunction<R(A1, A2, A3, A4, A5, A6, A7)> {
 public:
  typedef base::Callback<R(const scoped_refptr<JSCObjectOwner>&,
      typename base::internal::CallbackParamTraits<A1>::ForwardType,
      typename base::internal::CallbackParamTraits<A2>::ForwardType,
      typename base::internal::CallbackParamTraits<A3>::ForwardType,
      typename base::internal::CallbackParamTraits<A4>::ForwardType,
      typename base::internal::CallbackParamTraits<A5>::ForwardType,
      typename base::internal::CallbackParamTraits<A6>::ForwardType,
      typename base::internal::CallbackParamTraits<A7>::ForwardType)>
      CallbackType;
  JSCCallbackFunction(const scoped_refptr<JSCObjectOwner>& callable,
                      const CallbackType& callback)
      : callable_(callable), callback_(callback) {}

  R Run(
      typename base::internal::CallbackParamTraits<A1>::ForwardType a1,
      typename base::internal::CallbackParamTraits<A2>::ForwardType a2,
      typename base::internal::CallbackParamTraits<A3>::ForwardType a3,
      typename base::internal::CallbackParamTraits<A4>::ForwardType a4,
      typename base::internal::CallbackParamTraits<A5>::ForwardType a5,
      typename base::internal::CallbackParamTraits<A6>::ForwardType a6,
      typename base::internal::CallbackParamTraits<A7>::ForwardType a7)
      const OVERRIDE {
    callback_.Run(callable_, a1, a2, a3, a4, a5, a6, a7);
  }

  JSCObjectOwner* callable() { return callable_.get(); }

 private:
  ~JSCCallbackFunction() {}

  CallbackType callback_;
  scoped_refptr<JSCObjectOwner> callable_;
};

}  // namespace javascriptcore
}  // namespace script
}  // namespace cobalt

#endif  // SCRIPT_JAVASCRIPTCORE_JSC_CALLBACK_FUNCTION_H_
