caption: Control the availability of developer mode on extensions page
desc: |-
  Control if users can turn on Developer Mode on chrome://extensions.

  If the policy is not set, users can turn on developer mode on extension page unless <ph name="DEVELOPER_TOOLS_AVAILABILITY_POLICY_NAME">DeveloperToolsAvailability</ph> policy is set to <ph name="DEVELOPER_TOOLS_DISALLOWED">DeveloperToolsDisallowed</ph> (2).
  If the policy is set to <ph name="ALLOW">Allow</ph> (0), users can turn on developer mode on extensions page.
  If the policy is set to <ph name="DISALLOW">Disallow</ph> (1), users can not turn on developer mode on extensions page.

  If this policy is set, <ph name="DEVELOPER_TOOLS_AVAILABILITY_POLICY_NAME">DeveloperToolsAvailability</ph> can no longer control extensions developer mode.

supported_on:
- chrome.*:128-
- chrome_os:128-
features:
  dynamic_refresh: true
  per_profile: true
owners:
- zmin@chromium.org
- file://extensions/OWNERS
tags: []

type: int-enum
schema:
  enum:
  - 0
  - 1
  type: integer
items:
- caption: Allow the usage of developer mode on extensions page
  name: Allow
  value: 0
- caption: Do not allow the usage of developer mode on extensions page
  name: Disallow
  value: 1
default: null
example_value: 1
