caption: Enterprise printer configuration file
desc: |-
  Setting this policy configure enterprise printers. Its format matches the <ph name="PRINTERS_POLICY_NAME">Printers</ph> dictionary, with an additional required <ph name="ID_FIELD">"id"</ph> or <ph name="GUID_FIELD">"guid"</ph> field for each printer for allow listing or deny listing. The file size can't exceed 5MB and is in JSON format. A file with about 21,000 printers encodes as a 5MB file. The cryptographic hash helps verify download integrity. The file is downloaded, cached, and redownloaded when the URL or the hash changes. <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> downloads the file for printer configurations and makes printers available along with <ph name="PRINTERS_BULK_ACCESS_MODE_POLICY_NAME">PrintersBulkAccessMode</ph>, <ph name="PRINTERS_BULK_ALLOWLIST_POLICY_NAME">PrintersBulkAllowlist</ph>, and <ph name="PRINTERS_BULK_BLOCKLIST_POLICY_NAME">PrintersBulkBlocklist</ph>.

        This policy has no effect on whether users can configure printers on individual devices. It is intended to be supplementary to the configuration of printers by individual users.

        If you set the policy, users can't change it.
example_value:
  hash: deadbeefdeadbeefdeadbeefdeadbeefdeafdeadbeefdeadbeef
  url: https://example.com/printerpolicy
features:
  dynamic_refresh: true
  per_profile: true
max_size: 5242880
owners:
- file://chromeos/printing/OWNERS
- luum@chromium.org
schema:
  properties:
    hash:
      type: string
    url:
      type: string
  type: object
supported_on:
- chrome_os:86-
tags: []
type: external
