name: On Host Tests
description: Runs on-host tests.
inputs:
  test_artifacts_key:
    description: "Artifact key used to store test artifacts."
    required: true
  test_results_key:
    description: "Artifact key used to store test results."
    required: true
  num_gtest_shards:
    description: "Total number of shards used to run the steps in this file."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
    - name: Extract Artifacts
      shell: bash
      run: |
        set -x
<<<<<<< HEAD

        test_dir="${GITHUB_WORKSPACE}/unit_test"
        echo "test_dir=${test_dir}" >> $GITHUB_ENV

        mkdir -p ${test_dir}
        cd ${test_dir}
        tar xvf ../test_artifacts.tar.gz
=======
        mkdir -p unit_test/
        cd unit_test/
        tar -I 'zstd -T0' -xf ../test_artifacts.tar.zstd
>>>>>>> d2f225c4cb4 (ci: Use zstd compression for test artifacts (#7841))
    - name: Run Tests
      id: run-tests
      shell: bash
      env:
        XVFB_SERVER_ARGS: "-screen 0 1920x1080x24i +render +extension GLX -noreset"
      run: |
        set -x
        env

        # Explicitly point to libraries in extracted dir.
        LD_LIBRARY_PATH="${test_dir}/out/${{ matrix.platform}}_${{ matrix.config }}/starboard"
        LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${test_dir}/out/${{ matrix.platform}}_${{ matrix.config }}"
        export LD_LIBRARY_PATH

        # Make results dir available to the archiving step below.
        results_dir="${GITHUB_WORKSPACE}/results"
        echo "results_dir=${results_dir}" >> $GITHUB_ENV

        # Test results (xml and logs) must be in a subfolder in results_dir
        # to be picked up by the test result processor.
        # This also prevents accidental overwriting when collecting results.
        test_output="${results_dir}/shard_${{ matrix.shard }}"
        mkdir -p ${test_output}

        failed_suites=""
        cd "${test_dir}"

        for test_binary_path in $(cat out/${{ matrix.platform}}_${{ matrix.config }}/test_targets.json | jq -cr '.executables | join(" ")'); do
          test_binary=$(basename "${test_binary_path}")
          if [[ "${{ matrix.platform}}" == *"evergreen"* ]]; then
            test_binary_path=${test_binary_path}_loader
          fi
          echo "Running tests for suite: ${test_binary}"

          test_filter="*"
          test_filter_json_dir="${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}/${test_binary}_filter.json"
          if [ -f ${test_filter_json_dir} ]; then
            test_filter=`jq -r '"-" + (.failing_tests | join(":"))' ${test_filter_json_dir}`
          fi

          echo "Test filter evaluated to: ${test_filter}"
          xml_path="${test_output}/${test_binary}_result.xml"
          log_path="${test_output}/${test_binary}_log.txt"
          # TODO: Investigate test_runner.py

          if [ "${test_filter}" == "-*" ]; then
            echo "Skipped due to test filter." >  ${log_path}
          else
            export GTEST_TOTAL_SHARDS=${{ inputs.num_gtest_shards }}
            export GTEST_SHARD_INDEX=${{ matrix.shard }}
            /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" \
                stdbuf -i0 -o0 -e0 ./"${test_binary_path}" \
                --gtest_output="xml:${xml_path}" \
                --gtest_filter="${test_filter}" 2>&1 | tee ${log_path} || {
              failed_suites="${failed_suites} ${test_binary}"
            }
          fi
        done
        echo "Finished running tests..."
        if [ -n "${failed_suites}" ]; then
          echo "Test suites failed:${failed_suites}"
          # Fail the job so it's easy to retrigger.
          exit 1
        fi
    - name: Archive Test Results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_results_key }}
        path: ${{ env.results_dir }}/*
