// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Custom interface to communicate with layout tests.

[
  Conditional=ENABLE_TEST_RUNNER
] interface TestRunner {
  void notifyDone();
  void waitUntilDone();
  void DoNonMeasuredLayout();

  // Increment's the web page's clock by the specified number of milliseconds.
  // This will result in the advance of animations.
  void AdvanceClockByMs(long long amount);

  // Expose running native garbage collection without a JavaScript stack, and
  // then executing a callback. This is required to properly test certain
  // garbage collection scenarios, as that act of calling |window.gc| from
  // JavaScript can change the state of what is and isn't reachable with
  // respect to engine internals.
  [CallWith=EnvironmentSettings]
  void collectGarbageAndThenDo(TestRunnerCallback callback);
};

callback TestRunnerCallback = void();
