/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

[PrimaryGlobal]
/*sealed*/ interface Window : EventTarget {
  // [Unforgeable] readonly attribute WindowProxy window;
  [Unforgeable] readonly attribute Document document;
  [PutForwards=href, Unforgeable] readonly attribute Location location;
  readonly attribute Navigator navigator;

  long requestAnimationFrame(FrameRequestCallback callback);

  // TODO(***REMOVED***, b/21560766, b/21560873, b/21561006): Change the following
  // method back to its original form in the spec, when "Function" and "any" are
  // supported.  Move the method back to WindowTimers.idl.
  //   http://www.w3.org/TR/html5/webappapis.html#timers
  long setTimeout(TimerCallback handler, optional long timeout);

  readonly attribute Console console;
};
Window implements GlobalEventHandlers;

callback FrameRequestCallback = void(double time);
callback TimerCallback = void();
