caption: Power management settings when the user becomes idle
desc: |-
  Setting the policy controls the power management strategy when the user idles.

        There are 4 actions:

        * The screen dims if the user is idle for the time specified by <ph name="SCREEN_DIM_FIELD_NAME">ScreenDim</ph>.

        * The screen turns off if the user is idle for the time specified by <ph name="SCREEN_OFF_FIELD_NAME">ScreenOff</ph>.

        * A warning dialog appears if the user remains idle for the time specified by <ph name="IDLE_WARNING_FIELD_NAME">IdleWarning</ph>. It warns the user that the idle action will be taken and only appears if the idle action is to sign out or shut down.

        * The action specified by <ph name="IDLE_ACTION_FIELD_NAME">IdleAction</ph> is taken if the user is idle for the time specified by <ph name="IDLE_FIELD_NAME">Idle</ph>.

        For each of the above actions, the delay should be specified in milliseconds and must be set to a value greater than zero to trigger the corresponding action. If the delay is set to zero, <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> won't take the corresponding action.

        For each of the above delays, when the time is unset, a default value is used.

        <ph name="SCREEN_DIM_FIELD_NAME">ScreenDim</ph> values will be clamped to be less than or equal to <ph name="SCREEN_OFF_FIELD_NAME">ScreenOff</ph>. <ph name="SCREEN_OFF_FIELD_NAME">ScreenOff</ph> and <ph name="IDLE_WARNING_FIELD_NAME">IdleWarning</ph> will be clamped to be less than or equal to <ph name="IDLE_FIELD_NAME">Idle</ph>.

        <ph name="IDLE_ACTION_FIELD_NAME">IdleAction</ph> can be one of 4 actions:

        * <ph name="IDLE_ACTION_ENUM_SUSPEND">Suspend</ph>

        * <ph name="IDLE_ACTION_ENUM_LOGOUT">Logout</ph>

        * <ph name="IDLE_ACTION_ENUM_SHUTDOWN">Shutdown</ph>

        * <ph name="IDLE_ACTION_ENUM_DO_NOTHING">DoNothing</ph>

        If the <ph name="IDLE_ACTION_FIELD_NAME">IdleAction</ph> is not set, <ph name="IDLE_ACTION_ENUM_SUSPEND">Suspend</ph> is taken.

        Note: There are separate settings for AC power and battery.
example_value:
  AC:
    Delays:
      Idle: 30000
      IdleWarning: 5000
      ScreenDim: 10000
      ScreenOff: 20000
    IdleAction: DoNothing
  Battery:
    Delays:
      Idle: 30000
      IdleWarning: 5000
      ScreenDim: 10000
      ScreenOff: 20000
    IdleAction: DoNothing
features:
  dynamic_refresh: true
  per_profile: false
owners:
- reinauer@google.com
- chromeos-power@google.com
schema:
  properties:
    AC:
      $ref: PowerManagementDelays
      description: Delays and actions to take when the device is idle and running
        on AC power
    Battery:
      $ref: PowerManagementDelays
      description: Delays and actions to take when the device is idle and running
        on battery
  type: object
supported_on:
- chrome_os:35-
tags: []
type: dict
