name: On Device Test
description: Runs on-device tests.

runs:
  using: "composite"
  steps:
    - name: Install requirements
      run: |
        pip3 install grpcio==1.37.0 grpcio-tools==1.38.0
      shell: bash
    - name: Generate gRPC files
      run: |
        python -m grpc_tools.protoc -Itools/ --python_out=tools/ --grpc_python_out=tools/ tools/on_device_tests_gateway.proto
      shell: bash
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Set env vars
      run: |
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
        echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        echo "WORKFLOW=${{ github.workflow }}" >> $GITHUB_ENV
        if [ "${COBALT_BOOTLOADER}" != "null" ]; then
          echo "LOADER_CONFIG=${{ matrix.config }}" >> $GITHUB_ENV
          echo "LOADER_PLATFORM=${ COBALT_BOOTLOADER }" >> $GITHUB_ENV
        fi
        if [ "${{ matrix.dimension }}" != "null" ]; then
          echo "DIMENSION=${{ matrix.dimension }}" >> $GITHUB_ENV
        fi
      shell: bash
    - name: trigger ${{ matrix.type }} tests on ${{ matrix.platform }} platform
      run: |
        echo "session_id=$(
        python3 tools/on_device_tests_gateway_client.py \
          --token ${{ github.token }} \
          trigger \
          --test_type ${{ matrix.type }} \
          --platform ${{ matrix.target_platform }} \
          --config ${{ matrix.config }} \
          --label cobalt_github_${{ github.event_name }} \
          --tag cobalt_github_${{ github.event_name }} \
          --change_id "${{ github.sha }}" \
          --builder_name github_${{ matrix.platform }}_tests \
          --build_number ${GITHUB_RUN_NUMBER} \
          ${LOADER_PLATFORM:+"--loader_config" "$LOADER_CONFIG"} \
          ${LOADER_PLATFORM:+"--loader_platform" "$LOADER_PLATFORM"} \
          ${DIMENSION:+"--dimension" "$DIMENSION"} \
          --archive_path gs://${PROJECT_NAME}-test-artifacts-tmp/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{ matrix.platform }}_${{ matrix.config }}/artifacts.tar
        )" >> $GITHUB_ENV
      shell: bash
    - name: watch ${{ matrix.type }} tests on ${{ matrix.platform }} platform
      run: |
        python3 tools/on_device_tests_gateway_client.py \
          --token ${{ github.token }} \
          watch ${{ env.session_id }}
      shell: bash

