#ifndef STARBOARD_TVOS_SHARED_INTENT_YTINTENT_STARBOARDAPIS_H_
#define STARBOARD_TVOS_SHARED_INTENT_YTINTENT_STARBOARDAPIS_H_

void SBProcessAppIntent(const char* query, int isSearch);

#endif  // STARBOARD_TVOS_SHARED_INTENT_YTINTENT_STARBOARDAPIS_H_
