// Usually this would be:
//
// Generated by build/write_buildflag_header.py
// From "//base/allocator:features"
//
// However for Cobalt we just hardcode the values of these #defines.

#ifndef BASE_ALLOCATOR_FEATURES_H_
#define BASE_ALLOCATOR_FEATURES_H_

#include "base/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_ALLOCATOR_SHIM() (0)

#endif  // BASE_ALLOCATOR_FEATURES_H_
