caption: Settings for AI Mode Search recommendations in the address bar and new tab page search box

desc: |-
  This policy controls the AI Mode recommendations section in the address bar and the new tab page search box.

  This feature is available to all users with Google as their default search engine, unless it is disabled by this policy.

  If the policy is unset, its behavior is determined by the <ph name="GEN_AI_DEFAULT_SETTINGS_POLICY_NAME">GenAiDefaultSettings</ph> policy.

  When policy is set to 0 - Enabled or not set, the feature will be available to users. When policy is set to 1 - Disabled, the feature will not be available.

  0 = Allow the feature to be used
  1 = Do not allow the feature.

default: 0
example_value: 1
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: Allow AI Mode recommendations.
  name: Allowed
  value: 0
- caption: Do not allow AI Mode recommendations.
  name: Disabled
  value: 1
owners:
- file://components/omnibox/OWNERS
schema:
  enum:
  - 0
  - 1
  type: integer
future_on:
- android
- ios
- chrome.*
- chrome_os
tags: []
type: int-enum
