caption: Settings for AI-powered History Search

desc: |-
  AI History Search is a feature that allows users to search their browsing history and receive generated answers based on page contents and not just the page title and URL.

  0 = Enable the feature for users, and send relevant data to Google to help train or improve AI models. Relevant data may include prompts, inputs, outputs, and source materials, depending on the feature. It may be reviewed by humans for the sole purpose of improving AI models. 0 is the default value, except when noted below.

  1 = Enable the feature for users, but do not send data to Google to train or improve AI models. 1 is the default value for Enterprise users managed by <ph name="GOOGLE_ADMIN_CONSOLE_PRODUCT_NAME">Google Admin console</ph> and for Education accounts managed by <ph name="GOOGLE_WORKSPACE_PRODUCT_NAME">Google Workspace</ph>.

  2 = Disable the feature.

  If the policy is unset, the default behavior is 0 for regular consumer users and 2 for managed users on <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph>.

  For more information on data handling for generative AI features, please see https://support.google.com/chrome/a?p=generative_ai_settings.
default: 0
example_value: 2
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: Allow AI History Search and improve AI models.
  name: Allowed
  value: 0
- caption: Allow AI History Search without improving AI models.
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow AI History Search.
  name: Disabled
  value: 2
owners:
- file://components/history_embeddings/OWNERS
- file://components/optimization_guide/OWNERS
schema:
  enum:
  - 0
  - 1
  - 2
  type: integer
tags:
- google-sharing
supported_on:
- chrome.*:128-
- chrome_os:128-
tags: []
type: int-enum
