caption: Tab Compare settings
default: 0
desc: |-
  Tab Compare is an AI-powered tool for comparing information across a user's tabs. As an example, the feature can be offered to the user when multiple tabs with products in a similar category are open.

  0 = Enable the feature for users, and send relevant data to Google to help train or improve AI models. Relevant data may include prompts, inputs, outputs, and source materials, depending on the feature. It may be reviewed by humans for the sole purpose of improving AI models. 0 is the default value, except when noted below.

  1 = Enable the feature for users, but do not send data to Google to train or improve AI models. 1 is the default value for Enterprise users managed by <ph name="GOOGLE_ADMIN_CONSOLE_PRODUCT_NAME">Google Admin console</ph> and for Education accounts managed by <ph name="GOOGLE_WORKSPACE_PRODUCT_NAME">Google Workspace</ph>.

  2 = Disable the feature.

example_value: 2
features:
  dynamic_refresh: true
  per_profile: true
future_on:
- ios
- android
items:
- caption: Allow Tab Compare and improve AI models.
  name: Allowed
  value: 0
- caption: Allow Tab Compare without improving AI models.
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow Tab Compare.
  name: Disabled
  value: 2
owners:
- chrome-shopping@google.com
- file://components/commerce/OWNERS
schema:
  enum:
  - 0
  - 1
  - 2
  type: integer
supported_on:
- chrome.*:129-
- chrome_os:129-
tags: []
type: int-enum
