# Copyright 2019 The Cobalt Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was initially generated by starboard/tools/create_derived_build.py,
# though it may have been modified since its creation.
"""Starboard Linux X64X11 BlitterGLES platform configuration."""

from starboard.linux.x64x11 import gyp_configuration as parent_configuration
from starboard.tools.testing import test_filter


class LinuxX64X11BlitterglesConfiguration(
    parent_configuration.LinuxX64X11Configuration):

  def GetTestFilters(self):
    filters = super(LinuxX64X11BlitterglesConfiguration, self).GetTestFilters()
    for target, tests in self.__FILTERED_TESTS.iteritems():
      filters.extend(test_filter.TestFilter(target, test) for test in tests)
    return filters

  __FILTERED_TESTS = {
      'nplb_blitter_pixel_tests': [
          # Filtered because the bilinear interpolation with GLES is slightly
          # different than the interpolation on the expected image.
          'SbBlitterPixelTest.MagnifyBlitRectToRectInterpolated',
      ],
  }


def CreatePlatformConfig():
  return LinuxX64X11BlitterglesConfiguration('linux-x64x11-blittergles')
