name: Internal Tests
description: Runs internal tests.
inputs:
  test_dimensions:
    description: "Test dimensions JSON string."
    default: "{}"
  test_targets:
    description: "Test targets."
    required: true
  test_type:
    description: "Test type (e.g. e2e_test or yts_test)"
    required: true
  artifact_name:
    description: "The name of the artifact to be used for tests (e.g., Cobalt.apk)."
    default: "Cobalt.apk"
  test_device_family:
    description: "The test device family (e.g., raspi, rdk)."
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Requirements
      run: |
        pip3 install --require-hashes --no-deps -r ${GITHUB_WORKSPACE}/cobalt/tools/requirements.txt
      shell: bash
    - name: Generate gRPC files
      run: |
        python -m grpc_tools.protoc -I${GITHUB_WORKSPACE}/cobalt/tools/ \
            --python_out=${GITHUB_WORKSPACE}/cobalt/tools/ \
            --grpc_python_out=${GITHUB_WORKSPACE}/cobalt/tools/ \
            ${GITHUB_WORKSPACE}/cobalt/tools/on_device_tests_gateway.proto
      shell: bash
    - name: Set Up Cloud SDK
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Set GCS Project Name
      run: |
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
      shell: bash
    - name: Run Tests on ${{ matrix.platform }} Platform
      env:
        GCS_ARTIFACTS_PATH: ${{ env.PROJECT_NAME }}-test-artifacts/${{ github.workflow }}/${{ github.run_number }}/${{ matrix.platform }}/${{ matrix.platform }}_qa
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        TEST_RETRY_LEVEL: FAIL
      run: |
        set -x

        python3 -u cobalt/tools/on_device_tests_gateway_client.py \
          --token ${{ github.token }} \
          trigger \
          --test_type ${{ inputs.test_type }} \
          --targets '${{ inputs.test_targets }}' \
          --retry_level ${TEST_RETRY_LEVEL} \
          --label ${{ inputs.test_type }} \
          --label github_${{ github.event.pull_request.number || 'postsubmit' }} \
          --label builder-${{ matrix.platform }} \
          --label builder_url-${GITHUB_RUN_URL} \
          --label github \
          --label ${{ github.event_name }} \
          --label ${GITHUB_WORKFLOW} \
          --label actor-${{ github.actor }} \
          --label actor_id-${{ github.actor_id }} \
          --label triggering_actor-${{ github.triggering_actor }} \
          --label sha-${GITHUB_SHA} \
          --label repository-${{ github.repository }} \
          --label author-${{ github.event.pull_request.head.user.login || github.event.commits[0].author.username }} \
          --label author_id-${{ github.event.pull_request.head.user.id || github.event.commits[0].author.email }} \
          --label branch:${{ github.ref_name }} \
          --dimensions '${{ inputs.test_dimensions }}' \
          --artifact_name '${{ inputs.artifact_name }}' \
          --device_family '${{ inputs.test_device_family }}' \
          --cobalt_path "${GCS_ARTIFACTS_PATH}" || {
            echo "Finished running tests..."
            echo "The test session failed. See logs for details."
            # Fail the job so it's easy to retrigger.
            exit 1
          }
        echo "Finished running tests..."
      shell: bash
