name: On Host Test
description: Runs on-host tests.
inputs:
  os:
    description: "Host OS (either linux or windows)."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Env Variables
      shell: bash
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "TEST_RESULTS_DIR=${GITHUB_WORKSPACE}/unit-test-results" >> $GITHUB_ENV
        echo "COVERAGE_DIR=${GITHUB_WORKSPACE}/coverage" >> $GITHUB_ENV
    - name: Archive unit test report
      uses: actions/upload-artifact@v3
      # TODO: Should only run for unit-tests
      if: always()
      with:
        name: unit-test-reports
        path: ${{env.TEST_RESULTS_DIR}}/
    - name: Archive coverage html report
      if: success() && matrix.shard == 'coverage'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ${{env.COVERAGE_DIR}}/html
    - name: Upload to Codecov
      if: success() && matrix.shard == 'coverage'
      uses: codecov/codecov-action@v3
      with:
        files: ${{env.COVERAGE_DIR}}/report.txt
