name: Test Artifact Upload
description: Uploads test archives for on-device and on-host tests.
inputs:
  upload_on_host_test_artifacts:
    description: "Indicates if on-host test artifacts should be uploaded."
    required: true
  upload_on_device_test_artifacts:
    description: "Indicates if on-device test artifacts should be uploaded."
    required: true
  test_artifacts_key:
    description: "Artifact key used to store on-host test artifacts."
    required: true
  test_targets_json_file:
    description: "File containing the test target json."
    required: true
runs:
  using: "composite"
  steps:
    - name: Archive Test Artifacts
      run: |
        set -x
        mkdir ${GITHUB_WORKSPACE}/artifacts
        cd src/

<<<<<<< HEAD
=======
        # Configure archiver to gz compression for android, raspi, and rdk as the devices don't have zstd installed.
        FLAGS=""
        if [[ "${{ matrix.platform }}" == *android* ]]; then
          FLAGS="--compression gz --archive-per-target --use-android-deps-path --flatten-deps"
        elif [[ "${{ matrix.platform }}" == *raspi* || "${{ matrix.platform }}" == *rdk* ]]; then
          FLAGS="--compression gz --archive-per-target --flatten-deps"
        else
          FLAGS="--compression zstd --compression-level=9"
        fi

>>>>>>> d2f225c4cb4 (ci: Use zstd compression for test artifacts (#7841))
        time vpython3 -u ./cobalt/build/archive_test_artifacts.py \
          --source-dir ${GITHUB_WORKSPACE}/src \
          --out-dir out/${{ matrix.platform }}_${{ matrix.config }}/ \
          --destination-dir ${GITHUB_WORKSPACE}/artifacts \
          --platform ${{ matrix.platform }} \
          --targets $(cat "${{ inputs.test_targets_json_file }}" | jq -cr '.test_targets | join(",")')
      shell: bash
    - name: Upload On-Host Test Artifacts Archive
      if: inputs.upload_on_host_test_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
        path: artifacts/*
        retention-days: 3
    - name: Set up Cloud SDK
      if: inputs.upload_on_device_test_artifacts == 'true'
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Upload Android Test Artifacts to GCS
      if: inputs.upload_on_device_test_artifacts == 'true'
      env:
        WORKFLOW: ${{ github.workflow }}
      run: |
        set -eux
        project_name=$(gcloud config get-value project)

        # Upload gtest target artifacts.
        gsutil -m cp "${GITHUB_WORKSPACE}/artifacts/*" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}/"
<<<<<<< HEAD

        # Upload cobalt.apk for smoke tests.
        gsutil -m cp "${GITHUB_WORKSPACE}/src/out/${{ matrix.platform }}_${{ matrix.config }}/apks/Cobalt.apk" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}/"
=======
>>>>>>> d2f225c4cb4 (ci: Use zstd compression for test artifacts (#7841))
      shell: bash
