name: Test Artifact Upload
description: Packages and uploads test archives for either on-host or on-device tests.
inputs:
  upload_e2e_test_artifacts:
    description: "Indicates if E2E test artifacts should be uploaded."
    required: false
    default: "false"
  upload_on_device_test_artifacts:
    description: "Indicates if on-device test artifacts should be uploaded."
    required: false
    default: "false"
  platform:
    description: "The platform for which artifacts are being uploaded."
    required: true
  config:
    description: "The build configuration (e.g., devel, qa, gold)."
    required: true
  type:
    description: "The type of packaging ('on_host' or 'on_device')"
    required: true
  test_targets_json:
    description: "JSON array of GN targets to package"
    required: true
  test_artifacts_key:
    description: "Artifact key used to store on-host test artifacts."
    required: false
    default: ""
  on_device_executables:
    description: "JSON array of device executables to copy (only for on_device type)"
    required: false
    default: "[]"
runs:
  using: "composite"
  steps:
    - name: Create Artifacts Directory
      run: mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
      shell: bash

    - name: Copy Runnables to Artifacts
      if: inputs.type == 'on_device' && inputs.upload_on_device_test_artifacts == 'true'
      run: |
        set -eux
        cd cobalt/src/
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        readarray -t targets < <(echo '${{ inputs.on_device_executables }}' | jq -r '.[]')
        for target in "${targets[@]}"; do
          cp "${target}" "${GITHUB_WORKSPACE}/artifacts/"
        done
      shell: bash

    - name: Archive Test Dependencies
      env:
        PLATFORM: ${{ inputs.platform }}
        CONFIG: ${{ inputs.config }}
        TYPE: ${{ inputs.type }}
      run: |
        set -x
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        cd cobalt/src/

        TARGETS=$(echo '${{ inputs.test_targets_json }}' | jq -cr 'join(",")')

        if [[ -n "${TARGETS}" ]]; then
          FLAGS=""
          # For Device tests:
          if [[ "${TYPE}" == "on_device" ]]; then
            if [[ "${PLATFORM}" == *android* ]]; then
              FLAGS="--compression gz --archive-per-target --use-android-deps-path --flatten-deps"
            elif [[ "${PLATFORM}" == *raspi* || "${PLATFORM}" == *rdk* ]]; then
              FLAGS="--compression gz --archive-per-target --flatten-deps"
            else
              FLAGS="--compression zstd --compression-level=9"
            fi
          # For Host tests (GTests and JUnit tests):
          else
            FLAGS="--compression zstd --compression-level=9"
            if [[ "${PLATFORM}" == *android* ]]; then
              FLAGS="${FLAGS} --use-android-deps-path"
            fi
          fi

          time vpython3 -u ./cobalt/build/archive_test_artifacts.py \
            --source-dir ${GITHUB_WORKSPACE}/cobalt/src \
            --out-dir out/${PLATFORM}_${CONFIG}/ \
            --destination-dir ${GITHUB_WORKSPACE}/artifacts \
            --targets "${TARGETS}" \
            ${FLAGS}
        fi
      shell: bash

    - name: Archive Test Results Directory
      if: inputs.type == 'on_device' && (inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_e2e_test_artifacts == 'true')
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        cd cobalt/src/
        tar -I 'zstd -T0' -cf "${GITHUB_WORKSPACE}/artifacts/cobalt_test_results.tar.zstd" -C "out/${{ inputs.platform }}_${{ inputs.config }}/" test_results
      shell: bash

    - name: Upload On-Host Test Artifacts Archive
      if: inputs.type == 'on_host'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
        path: artifacts/*
        retention-days: 3

    - name: Set up Cloud SDK
      if: inputs.type == 'on_device' && (inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_e2e_test_artifacts == 'true')
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1

    - name: Upload On-Device Test Artifacts to GCS
      if: inputs.type == 'on_device' && (inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_e2e_test_artifacts == 'true')
      env:
        WORKFLOW: ${{ github.workflow }}
        PLATFORM: ${{ inputs.platform }}
        CONFIG: ${{ inputs.config }}
        UPLOAD_E2E_TEST_ARTIFACTS: ${{ inputs.upload_e2e_test_artifacts }}
      run: |
        set -eux
        project_name=$(gcloud config get-value project)

        # Add Cobalt release artifacts for smoke tests.
        if [[ "${UPLOAD_E2E_TEST_ARTIFACTS}" == "true" ]]; then
          mv ${GITHUB_WORKSPACE}/cobalt/src/out/test-package/* \
             ${GITHUB_WORKSPACE}/artifacts/
        fi

        # Upload cobalt.apk for smoke tests.
        if [[ "${PLATFORM}" == *android* ]]; then
          cp "${GITHUB_WORKSPACE}/cobalt/src/out/${PLATFORM}_${CONFIG}/apks/Cobalt.apk" \
             "${GITHUB_WORKSPACE}/artifacts/"
        fi

        gsutil -m cp -r "${GITHUB_WORKSPACE}/artifacts/*" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${PLATFORM}/"
      shell: bash
