name: Test Artifact Upload
description: Uploads test archives for on-device and on-host tests.
inputs:
  upload_on_host_test_artifacts:
    description: "Indicates if on-host test artifacts should be uploaded."
    required: true
  upload_on_device_test_artifacts:
    description: "Indicates if on-device test artifacts should be uploaded."
    required: true
  test_artifacts_key:
    description: "Artifact key used to store on-host test artifacts."
    required: true
  test_targets_json_file:
    description: "The path to test targets json file."
    required: true
runs:
  using: "composite"
  steps:
    - name: Copy Runnables to Artifacts
      if: inputs.upload_on_device_test_artifacts == 'true'
      env:
        TEST_TARGETS_JSON_FILE: ${{ inputs.test_targets_json_file }}
      run: |
        set -eux
        cd src/
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        for target in $(cat "${TEST_TARGETS_JSON_FILE}" | jq -r '.executables | .[]'); do
          cp "${target}" "${GITHUB_WORKSPACE}/artifacts/"
        done
      shell: bash
    - name: Archive Test Dependencies
      env:
        TEST_TARGETS_JSON_FILE: ${{ inputs.test_targets_json_file }}
      run: |
        set -x
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        cd src/

        FLAGS=""
        if [[ "${{ matrix.platform }}" == "android" ]]; then
          FLAGS="--archive-per-target --use-android-deps-path --root-dir ."
        elif [[ "${{ matrix.platform }}" == *raspi* ]]; then
          FLAGS="--archive-per-target"
        fi

        time vpython3 -u ./cobalt/build/archive_test_artifacts.py \
          --source-dir ${GITHUB_WORKSPACE}/src \
          --out-dir out/${{ matrix.platform }}_${{ matrix.config }}/ \
          --destination-dir ${GITHUB_WORKSPACE}/artifacts \
          --targets $(cat "${TEST_TARGETS_JSON_FILE}" | jq -cr '.test_targets | join(",")') \
          ${FLAGS}
      shell: bash
    - name: Upload On-Host Test Artifacts Archive
      if: inputs.upload_on_host_test_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
        path: artifacts/*
        retention-days: 3
    - name: Set up Cloud SDK
      if: inputs.upload_on_device_test_artifacts == 'true'
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Upload Android Test Artifacts to GCS
      if: inputs.upload_on_device_test_artifacts == 'true'
      env:
        WORKFLOW: ${{ github.workflow }}
      run: |
        set -eux
        project_name=$(gcloud config get-value project)

        # Upload gtest target artifacts.
        gsutil -m cp "${GITHUB_WORKSPACE}/artifacts/*" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}/"

        if [[ "${{ matrix.platform }}" == "android" ]]; then
          # Upload cobalt.apk for smoke tests.
          gsutil -m cp "${GITHUB_WORKSPACE}/src/out/${{ matrix.platform }}_${{ matrix.config }}/apks/Cobalt.apk" \
            "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}/"
        fi
      shell: bash
