name: Test Artifact Upload
description: Uploads test archives for on-device and on-host tests.
inputs:
  upload_e2e_test_artifacts:
    description: "Indicates if E2E test artifacts should be uploaded."
    required: true
  upload_on_host_test_artifacts:
    description: "Indicates if on-host test artifacts should be uploaded."
    required: true
  upload_on_device_test_artifacts:
    description: "Indicates if on-device test artifacts should be uploaded."
    required: true
  test_artifacts_key:
    description: "Artifact key used to store on-host test artifacts."
    required: true
  test_targets_json_file:
    description: "The path to test targets json file."
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Artifacts Directory
      run: mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
      shell: bash
    - name: Copy Runnables to Artifacts
      if: inputs.upload_on_device_test_artifacts == 'true'
      env:
        TEST_TARGETS_JSON_FILE: ${{ inputs.test_targets_json_file }}
      run: |
        set -eux
        cd cobalt/src/
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        for target in $(cat "${TEST_TARGETS_JSON_FILE}" | jq -r '.executables | .[]'); do
          cp "${target}" "${GITHUB_WORKSPACE}/artifacts/"
        done
      shell: bash
    - name: Archive Test Dependencies
      if: inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_on_host_test_artifacts == 'true'
      env:
        TEST_TARGETS_JSON_FILE: ${{ inputs.test_targets_json_file }}
      run: |
        set -x
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        cd cobalt/src/

        # Configure archiver to gz compression for android, raspi, and rdk as the devices don't have zstd installed.
        FLAGS=""
        if [[ "${{ matrix.platform }}" == *android* ]]; then
          FLAGS="--compression gz --archive-per-target --use-android-deps-path --flatten-deps"
        elif [[ "${{ matrix.platform }}" == *raspi* || "${{ matrix.platform }}" == *rdk* ]]; then
          FLAGS="--compression gz --archive-per-target --flatten-deps"
        else
          FLAGS="--compression zstd --compression-level=9"
        fi

        time vpython3 -u ./cobalt/build/archive_test_artifacts.py \
          --source-dir ${GITHUB_WORKSPACE}/cobalt/src \
          --out-dir out/${{ matrix.platform }}_${{ matrix.config }}/ \
          --destination-dir ${GITHUB_WORKSPACE}/artifacts \
          --targets $(cat "${TEST_TARGETS_JSON_FILE}" | jq -cr '.test_targets | join(",")') \
          ${FLAGS}
      shell: bash
    - name: Upload On-Host Test Artifacts Archive
      if: inputs.upload_on_host_test_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
        path: artifacts/*
        retention-days: 3
    - name: Set up Cloud SDK
      if: inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_e2e_test_artifacts == 'true'
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Upload On-Device Test Artifacts to GCS
      if: inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_e2e_test_artifacts == 'true'
      env:
        WORKFLOW: ${{ github.workflow }}
      run: |
        set -eux
        project_name=$(gcloud config get-value project)

        # Add Cobalt release artifacts for smoke tests.
        if [[ "${{ inputs.upload_e2e_test_artifacts }}" == "true" ]]; then
          mv ${GITHUB_WORKSPACE}/cobalt/src/out/test-package/* \
             ${GITHUB_WORKSPACE}/artifacts/
        fi

        # Upload cobalt.apk for smoke tests.
        if [[ "${{ matrix.platform }}" == *android* ]]; then
          cp "${GITHUB_WORKSPACE}/cobalt/src/out/${{ matrix.platform }}_${{ matrix.config }}/apks/Cobalt.apk" \
             "${GITHUB_WORKSPACE}/artifacts/"
        fi

        gsutil -m cp -r "${GITHUB_WORKSPACE}/artifacts/*" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}/"
      shell: bash
    - name: Login to us-west1 GAR
      if: inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_on_host_test_artifacts == 'true'
      run: |
        set -eux
        # Login to GAR using the service account token from metadata server.
        TOKEN_ENDPOINT="http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token"
        ACCESS_TOKEN=$(curl -H 'Metadata-Flavor: Google' ${TOKEN_ENDPOINT} | jq -r .access_token)
        printf ${ACCESS_TOKEN} | docker login -u oauth2accesstoken --password-stdin https://us-west1-docker.pkg.dev
      shell: bash
    - name: Build and Push Browser Test Docker Image
      if: inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_on_host_test_artifacts == 'true'
      env:
        TEST_TARGETS_JSON_FILE: ${{ inputs.test_targets_json_file }}
      run: |
        set -eux
        # Check if cobalt_browsertests is in the targets.
        if grep -q "cobalt_browsertests" "${TEST_TARGETS_JSON_FILE}"; then
          echo "Found cobalt_browsertests in targets. Building Docker image..."

          # Dockerfile expects cobalt_browsertests_artifacts.tar.gz in the context.
          # archive_test_artifacts.py creates it in the artifacts directory.
          cp "${GITHUB_WORKSPACE}/cobalt/src/cobalt/testing/browser_tests/tools/Dockerfile" "${GITHUB_WORKSPACE}/artifacts/"
          cd "${GITHUB_WORKSPACE}/artifacts/"

          TAG="${{ github.run_id }}-${{ matrix.platform }}-${{ matrix.config }}"
          IMAGE="us-west1-docker.pkg.dev/ytlr-image-hosting/integration-test-images/avvall-service-test:${TAG}"

          docker build -f Dockerfile -t "${IMAGE}" .
          docker push "${IMAGE}"
        else
          echo "cobalt_browsertests not found in targets. Skipping Docker build."
        fi
      shell: bash
