name: Test Artifact Upload
description: Uploads test archives for on-device and on-host tests.
inputs:
  on_host:
    description: "Indicates if on-host test artifacts should be uploaded."
    required: true
  on_device:
    description: "Indicates if on-device test artifacts should be uploaded."
    required: true
  test_artifacts_key:
    description: "Artifact key used to store on-host test artifacts."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      if: inputs.on_device == 'true'
      uses: isarkis/setup-gcloud@40dce7857b354839efac498d3632050f568090b6 # v1.1.1
    - name: Upload Android Test Artifacts to GCS
      if: inputs.on_device == 'true'
      env:
        WORKFLOW: ${{ github.workflow }}
      run: |
        set -eux
        project_name=$(gcloud config get-value project)
        gsutil cp "${GITHUB_WORKSPACE}/src/out/${{ matrix.platform }}_${{ matrix.config }}/**/*.apk" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}/"
      shell: bash

    - name: Create On-Host Test Artifacts Archive
      if: inputs.on_host == 'true'
      run: |
        set -x
        cd src/out/${{ matrix.platform }}_${{ matrix.config }}
        test_deps_file="test.deps"
        for test_binary in $(ls {nplb,*tests}); do
          echo $test_binary
          if [ -f "${test_binary}.runtime_deps" ]; then
            cat "${test_binary}.runtime_deps" >> "${test_deps_file}"
          fi
        done
        tar cvf - -T "${test_deps_file}" | xz -T0 -1 -z - > "${GITHUB_WORKSPACE}/test_artifacts.tar.xz"
      shell: bash
    - name: Upload On-Host Test Artifacts Archive
      if: inputs.on_host == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_artifacts_key }}
        path: test_artifacts.tar.xz
        retention-days: 3
