caption: <ph name="PRODUCT_NAME">Google Cast</ph>
desc: Configure policies for <ph name="PRODUCT_NAME">Google Cast</ph>, a feature that
  allows users to send the contents of tabs, sites or the desktop from the browser
  to remote displays and sound systems.
