name: Upload Nightly Artifacts
description: Archives and uploads nightly artifacts to GCS bucket.
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Set env vars
      run: |
        echo "ARCHIVE_FILE=cobalt-${{matrix.platform}}_${{matrix.config}}.tar.gz" >> $GITHUB_ENV
        echo "ARCHIVE_PATH=$GITHUB_WORKSPACE/cobalt-${{matrix.platform}}_${{matrix.config}}.tar.gz" >> $GITHUB_ENV
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        echo "WORKFLOW=${{github.workflow}}" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      shell: bash
    - name: Copy Out Folder
      run: |
        # Clean up.
        [ -d "${GITHUB_WORKSPACE}/out/upload_out" ] && rm -rf "${GITHUB_WORKSPACE}/out/upload_out"
        [ -f "${ARCHIVE_FILE}" ] && rm -rf "${ARCHIVE_FILE}"
        # Create an archive.
        python3 $GITHUB_WORKSPACE/tools/copy_and_filter_out_dir.py -d $GITHUB_WORKSPACE/out/upload_out/${{matrix.target_platform}}_${{matrix.config}} -s $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}}
      shell: bash
    - name: Create Archive
      run: |
        set -x
        cd "$GITHUB_WORKSPACE"
        python3 $GITHUB_WORKSPACE/tools/create_archive.py --intermediate -d ${{env.ARCHIVE_FILE}} -s out/upload_out
      shell: bash
    - name: Upload Archive
      id: upload-archive
      uses: google-github-actions/upload-cloud-storage@v0.10.2
      with:
        headers: |-
          content-type: application/x-tar
        path: ${{env.ARCHIVE_PATH}}
        destination: ${{env.PROJECT_NAME}}-build-artifacts/${{env.WORKFLOW}}/${{env.TODAY}}/${{env.GITHUB_RUN_NUMBER}}/
