# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Starboard Android shared platform configuration for gyp_cobalt."""

from __future__ import print_function

import imp
import os

import config.base
import gyp_utils
import sdk_utils
from starboard.tools.testing import test_filter


class PlatformConfig(config.base.PlatformConfigBase):
  """Starboard Android platform configuration."""

  # TODO: make ASAN work with NDK tools and enable it by default
  def __init__(self, platform, android_abi, asan_enabled_by_default=False):
    super(PlatformConfig, self).__init__(platform, asan_enabled_by_default)

    self.android_abi = android_abi
    self.ndk_tools = sdk_utils.GetToolsPath(android_abi)
    sdk_utils.InstallSdkIfNeeded(android_abi)

    self.host_compiler_environment = gyp_utils.GetHostCompilerEnvironment()
    self.android_home = sdk_utils.GetSdkPath()
    self.android_ndk_home = sdk_utils.GetNdkPath()

    print('Using Android SDK at {}'.format(self.android_home))
    print('Using Android NDK at {}'.format(self.android_ndk_home))

  def GetBuildFormat(self):
    """Returns the desired build format."""
    # The comma means that ninja and qtcreator_ninja will be chained and use the
    # same input information so that .gyp files will only have to be parsed
    # once.
    return 'ninja,qtcreator_ninja'

  def GetVariables(self, configuration):
    variables = super(PlatformConfig, self).GetVariables(
        configuration, use_clang=1)
    variables.update({
        'ANDROID_HOME': self.android_home,
        'NDK_HOME': self.android_ndk_home,
        'ANDROID_ABI': self.android_abi,
        'enable_remote_debugging': 0,
        'include_path_platform_deploy_gypi':
            'starboard/android/shared/platform_deploy.gypi',
    })
    return variables

  def GetGeneratorVariables(self, configuration):
    _ = configuration
    generator_variables = {
        'qtcreator_session_name_prefix': 'cobalt',
    }
    return generator_variables

  def GetEnvironmentVariables(self):
    env_variables = sdk_utils.GetEnvironmentVariables(self.android_abi)
    env_variables.update(self.host_compiler_environment)
    # Android builds tend to consume significantly more memory than the
    # default settings permit, so cap this at 1 in order to avoid build
    # issues.  Without this, 32GB machines end up getting automatically
    # configured to run 5 at a time, which can be too much for at least
    # android-arm64_debug.
    # TODO: Eventually replace this with something more robust, like an
    #       implementation of the abstract toolchain for Android.
    env_variables.update({'GYP_LINK_CONCURRENCY': '1'})

    return env_variables

  def GetLauncher(self):
    """Gets the module used to launch applications on this platform."""
    module_path = os.path.abspath(os.path.join(
        os.path.dirname(__file__), 'launcher.py'))
    launcher_module = imp.load_source('launcher', module_path)
    return launcher_module

  def GetTestFilters(self):
    """Gets all tests to be excluded from a unit test run.

    Returns:
      A list of initialized TestFilter objects.
    """

    # Android unit tests are enabled on buildbots, but cannot yet run on them,
    # so we filter all of the tests out.
    return [
        test_filter.DISABLE_TESTING
    ]

  # This is a list of unit tests that are confirmed to fail on Android.  When
  # buildbot testing is enabled, return this list of test filters from
  # GetTestFilters().
  _FAILING_TESTS = [
      # This list was generated by tracking crashes and failures from the
      # android-x86 platform using the "devel" configuration.  If any
      # additional failures are found on other platform, create a
      # PlatformConfig ass in its gyp_configuration.py file and override this
      # method.

      # Fails with SpiderMonkey.
      test_filter.TestFilter(
          'bindings_test', ('GlobalInterfaceBindingsTest.'
                            'PropertiesAndOperationsAreOwnProperties')),

      test_filter.TestFilter(
          'starboard_platform_tests', test_filter.FILTER_ALL),
      test_filter.TestFilter(
          'nplb_blitter_pixel_tests', test_filter.FILTER_ALL),

      # Delete when Webdriver Benchmarks for Android are enabled.
      test_filter.TestFilter('webdriver_test', test_filter.FILTER_ALL),

      # Crash occurs on android-x86_devel
      test_filter.TestFilter('nb_test', test_filter.FILTER_ALL),

      # All of the following tests faile on android-x86_devel
      test_filter.TestFilter('net_unittests',
                             'HostResolverImplDnsTest.DnsTaskUnspec'),

      test_filter.TestFilter('nplb', 'SbAudioSinkTest.SomeFramesConsumed'),
      test_filter.TestFilter('nplb', 'SbAudioSinkTest.AllFramesConsumed'),
      test_filter.TestFilter(
          'nplb', 'SbAudioSinkTest.MultipleAppendAndConsume'),
      test_filter.TestFilter('nplb', 'SbAudioSinkTest.Pause'),
      test_filter.TestFilter(
          'nplb', 'Semaphore.ThreadTakesWait_PutBeforeTimeExpires'),
      test_filter.TestFilter('nplb', 'Semaphore.ThreadTakesWait_TimeExpires'),
      test_filter.TestFilter(
          'nplb', 'SpeechRecognizerTest.StartTestSunnyDay'),
      test_filter.TestFilter(
          'nplb',
          'SpeechRecognizerTest.StartRecognizerWithContinuousRecognition'),
      test_filter.TestFilter(
          'nplb', 'SpeechRecognizerTest.StartRecognizerWithInterimResults'),
      test_filter.TestFilter(
          'nplb',
          'SpeechRecognizerTest.StartRecognizerWith10MaxAlternatives'),
      test_filter.TestFilter(
          'nplb', 'SpeechRecognizerTest.StartIsCalledMultipleTimes'),
      test_filter.TestFilter(
          'nplb',
          'SbSocketAddressTypes/SbSocketGetInterfaceAddressTest.'
          'SunnyDayDestination/1'),
      test_filter.TestFilter(
          'nplb',
          'SbSocketAddressTypes/SbSocketGetInterfaceAddressTest.'
          'SunnyDaySourceForDestination/0'),
      test_filter.TestFilter(
          'nplb',
          'SbSocketAddressTypes/SbSocketGetInterfaceAddressTest.'
          'SunnyDaySourceForDestination/1'),
      test_filter.TestFilter(
          'nplb', 'SbSocketAddressTypes/SbSocketGetInterfaceAddressTest.'
          'SunnyDaySourceNotLoopback/1'),

      # Crash occurs on android-x86_devel
      test_filter.TestFilter('poem_unittests', test_filter.FILTER_ALL)
  ]
