FROM python:3.11.14-trixie@sha256:a59271513fb0937fe3aac14c5178ab68b8125c39f7c503628a6ac9e9906c45cf

COPY ./piptools_requirements.txt /piptools_requirements.txt

# Keep this separate from the requirements.txt we are generating in the following step.
RUN pip3 install -r /piptools_requirements.txt

WORKDIR /code

# Generate and overwrite cobalt/tools/requirements.txt.
CMD pip-compile --allow-unsafe --generate-hashes cobalt/tools/requirements.in -o cobalt/tools/requirements.txt
