# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: on_device_tests_gateway.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='on_device_tests_gateway.proto',
  package='on_device_tests_gateway',
  syntax='proto3',
  serialized_pb=_b('\n\x1don_device_tests_gateway.proto\x12\x17on_device_tests_gateway\"r\n\x14OnDeviceTestsCommand\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0e\n\x06labels\x18\x08 \x03(\t\x12;\n\rtest_requests\x18\x18 \x03(\x0b\x32$.on_device_tests_gateway.TestRequest\"\x80\x01\n\x0bTestRequest\x12\x11\n\ttest_args\x18\x01 \x03(\t\x12\x15\n\rtest_cmd_args\x18\x02 \x03(\t\x12\r\n\x05\x66iles\x18\x03 \x03(\t\x12\x0e\n\x06params\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65vice_pool\x18\x06 \x01(\t\"s\n\x19OnDeviceTestsWatchCommand\x12\x0f\n\x07workdir\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x11\n\tchange_id\x18\x04 \x01(\t\x12\x0f\n\x07\x64ry_run\x18\x05 \x01(\x08\")\n\x15OnDeviceTestsResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x8a\x02\n\x17on_device_tests_gateway\x12q\n\x0c\x65xec_command\x12-.on_device_tests_gateway.OnDeviceTestsCommand\x1a..on_device_tests_gateway.OnDeviceTestsResponse\"\x00\x30\x01\x12|\n\x12\x65xec_watch_command\x12\x32.on_device_tests_gateway.OnDeviceTestsWatchCommand\x1a..on_device_tests_gateway.OnDeviceTestsResponse\"\x00\x30\x01\x62\x06proto3')
)




_ONDEVICETESTSCOMMAND = _descriptor.Descriptor(
  name='OnDeviceTestsCommand',
  full_name='on_device_tests_gateway.OnDeviceTestsCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='on_device_tests_gateway.OnDeviceTestsCommand.token', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='on_device_tests_gateway.OnDeviceTestsCommand.labels', index=1,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_requests', full_name='on_device_tests_gateway.OnDeviceTestsCommand.test_requests', index=2,
      number=24, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=172,
)


_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='on_device_tests_gateway.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_args', full_name='on_device_tests_gateway.TestRequest.test_args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_cmd_args', full_name='on_device_tests_gateway.TestRequest.test_cmd_args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='on_device_tests_gateway.TestRequest.files', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='on_device_tests_gateway.TestRequest.params', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='on_device_tests_gateway.TestRequest.device_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_pool', full_name='on_device_tests_gateway.TestRequest.device_pool', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=303,
)


_ONDEVICETESTSWATCHCOMMAND = _descriptor.Descriptor(
  name='OnDeviceTestsWatchCommand',
  full_name='on_device_tests_gateway.OnDeviceTestsWatchCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workdir', full_name='on_device_tests_gateway.OnDeviceTestsWatchCommand.workdir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='on_device_tests_gateway.OnDeviceTestsWatchCommand.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='on_device_tests_gateway.OnDeviceTestsWatchCommand.session_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change_id', full_name='on_device_tests_gateway.OnDeviceTestsWatchCommand.change_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dry_run', full_name='on_device_tests_gateway.OnDeviceTestsWatchCommand.dry_run', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=420,
)


_ONDEVICETESTSRESPONSE = _descriptor.Descriptor(
  name='OnDeviceTestsResponse',
  full_name='on_device_tests_gateway.OnDeviceTestsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='on_device_tests_gateway.OnDeviceTestsResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=463,
)

_ONDEVICETESTSCOMMAND.fields_by_name['test_requests'].message_type = _TESTREQUEST
DESCRIPTOR.message_types_by_name['OnDeviceTestsCommand'] = _ONDEVICETESTSCOMMAND
DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['OnDeviceTestsWatchCommand'] = _ONDEVICETESTSWATCHCOMMAND
DESCRIPTOR.message_types_by_name['OnDeviceTestsResponse'] = _ONDEVICETESTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OnDeviceTestsCommand = _reflection.GeneratedProtocolMessageType('OnDeviceTestsCommand', (_message.Message,), dict(
  DESCRIPTOR = _ONDEVICETESTSCOMMAND,
  __module__ = 'on_device_tests_gateway_pb2'
  # @@protoc_insertion_point(class_scope:on_device_tests_gateway.OnDeviceTestsCommand)
  ))
_sym_db.RegisterMessage(OnDeviceTestsCommand)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), dict(
  DESCRIPTOR = _TESTREQUEST,
  __module__ = 'on_device_tests_gateway_pb2'
  # @@protoc_insertion_point(class_scope:on_device_tests_gateway.TestRequest)
  ))
_sym_db.RegisterMessage(TestRequest)

OnDeviceTestsWatchCommand = _reflection.GeneratedProtocolMessageType('OnDeviceTestsWatchCommand', (_message.Message,), dict(
  DESCRIPTOR = _ONDEVICETESTSWATCHCOMMAND,
  __module__ = 'on_device_tests_gateway_pb2'
  # @@protoc_insertion_point(class_scope:on_device_tests_gateway.OnDeviceTestsWatchCommand)
  ))
_sym_db.RegisterMessage(OnDeviceTestsWatchCommand)

OnDeviceTestsResponse = _reflection.GeneratedProtocolMessageType('OnDeviceTestsResponse', (_message.Message,), dict(
  DESCRIPTOR = _ONDEVICETESTSRESPONSE,
  __module__ = 'on_device_tests_gateway_pb2'
  # @@protoc_insertion_point(class_scope:on_device_tests_gateway.OnDeviceTestsResponse)
  ))
_sym_db.RegisterMessage(OnDeviceTestsResponse)



_ON_DEVICE_TESTS_GATEWAY = _descriptor.ServiceDescriptor(
  name='on_device_tests_gateway',
  full_name='on_device_tests_gateway.on_device_tests_gateway',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=466,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='exec_command',
    full_name='on_device_tests_gateway.on_device_tests_gateway.exec_command',
    index=0,
    containing_service=None,
    input_type=_ONDEVICETESTSCOMMAND,
    output_type=_ONDEVICETESTSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='exec_watch_command',
    full_name='on_device_tests_gateway.on_device_tests_gateway.exec_watch_command',
    index=1,
    containing_service=None,
    input_type=_ONDEVICETESTSWATCHCOMMAND,
    output_type=_ONDEVICETESTSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ON_DEVICE_TESTS_GATEWAY)

DESCRIPTOR.services_by_name['on_device_tests_gateway'] = _ON_DEVICE_TESTS_GATEWAY

# @@protoc_insertion_point(module_scope)
