/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

interface CSSStyleDeclaration {
  // TODO(***REMOVED***): b/19829526. attribute type should be DOMString instead of
  // PropertyValue according to spec.
  //   http://dev.w3.org/csswg/cssom/#the-cssstyledeclaration-interface
  [TreatNullAs=EmptyString] attribute PropertyValue? background;
  [TreatNullAs=EmptyString] attribute PropertyValue? backgroundColor;
  [TreatNullAs=EmptyString] attribute PropertyValue? backgroundImage;
  [TreatNullAs=EmptyString] attribute PropertyValue? borderRadius;
  [TreatNullAs=EmptyString] attribute PropertyValue? color;
  [TreatNullAs=EmptyString] attribute PropertyValue? display;
  [TreatNullAs=EmptyString] attribute PropertyValue? fontFamily;
  [TreatNullAs=EmptyString] attribute PropertyValue? fontSize;
  [TreatNullAs=EmptyString] attribute PropertyValue? fontWeight;
  [TreatNullAs=EmptyString] attribute PropertyValue? height;
  [TreatNullAs=EmptyString] attribute PropertyValue? opacity;
  [TreatNullAs=EmptyString] attribute PropertyValue? overflow;
  [TreatNullAs=EmptyString] attribute PropertyValue? transform;
  [TreatNullAs=EmptyString] attribute PropertyValue? transitionDuration;
  [TreatNullAs=EmptyString] attribute PropertyValue? transitionProperty;
  [TreatNullAs=EmptyString] attribute PropertyValue? width;

  attribute DOMString cssText;

  PropertyValue getPropertyValue(DOMString propertyName);
  void setPropertyValue(DOMString propertyName, PropertyValue propertyValue);
};
