name: coverage

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - feature/*

jobs:
  linux-coverage:
    # TODO(b/286302961): Move back and re-enable this check once sharding is supported.
    # Run on main branch for pushes, PRs and manual invocations.
    # if: |
    #  ${{ github.ref == 'refs/heads/main' &&
    #      (github.event_name == 'push' ||
    #      github.event_name == 'pull_request' ||
    #      (github.event_name == 'workflow_dispatch' && inputs.nightly == 'false')) }}
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: linux-coverage
      nightly: ${{ github.event.inputs.nightly }}
