name: evergreen_21.lts.1+

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, labeled]
    branches:
      - '21.lts.1\+'
  push:
    branches:
      - '21.lts.1\+'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  evergreen-x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x64
      nightly: ${{ github.event.inputs.nightly }}
  evergreen-arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-hardfp
      nightly: ${{ github.event.inputs.nightly }}
  evergreen-arm-softfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-softfp
      nightly: ${{ github.event.inputs.nightly }}
<<<<<<< HEAD:.github/workflows/evergreen_21.lts.1+.yaml
=======
      run_api_leak_detector: true
  evergreen-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm64
      nightly: ${{ github.event.inputs.nightly }}
      run_api_leak_detector: true
>>>>>>> e6dc1dbd45e (Add missing Evergreen-arm64 builds (#470)):.github/workflows/evergreen.yaml
  evergreen-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x86
      nightly: ${{ github.event.inputs.nightly }}
