name: Java Tests

on:
  pull_request:
  push:
    branches:
      - main
      - feature/*

concurrency:
  group: '${{ github.workflow }}-${{ github.event_name }}-${{ inputs.platform }} @ ${{ github.event.pull_request.number || github.sha }}'
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: kaidokert/checkout@v3.5.999
        timeout-minutes: 30
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
