name: nightly_trigger_27.lts

on:
  schedule:
    # GMT timezone.
    - cron: '0 10,12,14 * * *'
  workflow_dispatch:

permissions: {}

env:
  GITHUB_REPO: ${{ github.repository }}

jobs:
  trigger_main:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Nightly
        run: |
          set -x
          gh workflow run android_27.lts --ref main -f nightly=true --repo "${GITHUB_REPO}"
          gh workflow run evergreen_27.lts --ref main -f nightly=true --repo "${GITHUB_REPO}"
          gh workflow run linux_27.lts --ref main -f nightly=true --repo "${GITHUB_REPO}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
