name: raspi-2-modular

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - experimental/*
      - feature/*
  push:
    branches:
      - main
      - experimental/*
      - feature/*
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false
      label_name:
        description: 'Label that triggered this run.'
        required: false
        type: string
        default: ''

permissions: read-all

jobs:
  # This is the raspi build config
  raspi-2-modular:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: raspi-2-modular
      nightly: ${{ github.event.inputs.nightly }}
      label_name: ${{ github.event.inputs.label_name }}
    secrets:
      datadog_api_key: ${{ secrets.DD_API_KEY }}
