name: raspi-2_25.lts.1+

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - '25.lts.1\+'
  push:
    branches:
      - '25.lts.1\+'
  schedule:
    # GMT timezone.
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  raspi-2:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: raspi-2
      nightly: ${{ github.event.inputs.nightly }}
  raspi-2-skia:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: raspi-2-skia
      nightly: ${{ github.event.inputs.nightly }}
