name: stub_24.lts.1+

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, labeled]
    branches:
      - '24.lts.1\+'
  push:
    branches:
      - '24.lts.1\+'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  stub:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: stub
      nightly: 'false'
      run_api_leak_detector: true
      leak_manifest_filename: "gn_built_docker_debian10_manifest"
