name: tvos

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - experimental/*
      - feature/*
  push:
    branches:
      - main
      - experimental/*
      - feature/*
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false
      label_name:
        description: 'Label that triggered this run.'
        required: false
        type: string
        default: ''

permissions: read-all

jobs:
  # This is default Chromium build config
  tvos-arm64-simulator:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: tvos-arm64-simulator
      nightly: ${{ github.event.inputs.nightly }}
      label_name: ${{ github.event.inputs.label_name }}
    secrets:
      datadog_api_key: ${{ secrets.DD_API_KEY }}
      sccache_gcs_key: ${{ secrets.SCCACHE_GCS_KEY_TVOS }}
