name: workflow_trigger

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Branch
        options:
          - '25.lts.1+'
          - '24.lts.1+'
          - '23.lts.1+'
          - '22.lts.1+'
          - '21.lts.1+'
          - '20.lts.1+'
          - '19.lts.1+'
          - 'rc_11'
          - 'COBALT_9'
      workflow:
        type: choice
        description: Workflow name
        options:
          - 'android'
          - 'evergreen'
          - 'linux'
          - 'raspi'
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  trigger:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: kaidokert/checkout@v3.5.999
        with:
          fetch-depth: 1
          ref: ${{ github.event.branch }}
      - name: Trigger Workflow
        run: |
          set -x
          gh workflow run ${{ github.event.inputs.workflow }}_${{ github.event.inputs.branch }} --ref ${{ github.event.inputs.branch }} -f nightly=${{ github.event.inputs.nightly }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
