name: xb1_25.lts.1+

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - '25.lts.1\+'
  push:
    branches:
      - '25.lts.1\+'
  schedule:
    # GTM timezone.
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  xb1:
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: xb1
      nightly: ${{ github.event.inputs.nightly }}
